"""
quant_research/model/kline_feature_volume_price.py

量价关系特征定义 - 36种经典量价形态
命名规范：全部使用 vp_ 前缀（volume-price）
"""
from .kline_feature_model import KLineFeatureDefinition, KLineFeatureType, FeatureComplexity


VOLUME_PRICE_FEATURES = {
    # ====================================================================
    # 基础九宫格（量变 x 价变 = 9种组合）
    # ====================================================================
    "vp_vol_up_price_up": KLineFeatureDefinition(
        name="vp_vol_up_price_up",
        display_name="量增价升",
        feature_type=KLineFeatureType.VOLUME,
        description="成交量放大且价格上涨，多头主导信号，趋势延续确认",
        formula="(volume > volume.rolling(20).mean() * 1.3) & (close > close.shift(1))",
        lookback_period=20,
        complexity=FeatureComplexity.SIMPLE,
        suitable_for_condition=True,
        suitable_for_alpha=True,
    ),
    "vp_vol_up_price_flat": KLineFeatureDefinition(
        name="vp_vol_up_price_flat",
        display_name="量增价平",
        feature_type=KLineFeatureType.VOLUME,
        description="放量但价格不动，多空博弈激烈，可能变盘前兆",
        formula="(volume > volume.rolling(20).mean() * 1.3) & (abs(close - close.shift(1)) / (close.shift(1) + 1e-8) < 0.005)",
        lookback_period=20,
        complexity=FeatureComplexity.SIMPLE,
        suitable_for_condition=True,
    ),
    "vp_vol_up_price_down": KLineFeatureDefinition(
        name="vp_vol_up_price_down",
        display_name="量增价跌",
        feature_type=KLineFeatureType.VOLUME,
        description="放量下跌，空头力量增强，趋势可能加速下行",
        formula="(volume > volume.rolling(20).mean() * 1.3) & (close < close.shift(1))",
        lookback_period=20,
        complexity=FeatureComplexity.SIMPLE,
        suitable_for_condition=True,
    ),
    "vp_vol_flat_price_up": KLineFeatureDefinition(
        name="vp_vol_flat_price_up",
        display_name="量平价升",
        feature_type=KLineFeatureType.VOLUME,
        description="量能平稳价格上涨，温和上涨信号，持续性较好",
        formula="(volume > volume.rolling(20).mean() * 0.8) & (volume < volume.rolling(20).mean() * 1.2) & (close > close.shift(1))",
        lookback_period=20,
        complexity=FeatureComplexity.SIMPLE,
        suitable_for_condition=True,
    ),
    "vp_vol_flat_price_flat": KLineFeatureDefinition(
        name="vp_vol_flat_price_flat",
        display_name="量平价平",
        feature_type=KLineFeatureType.VOLUME,
        description="量价均无变化，市场观望，盘整蓄势阶段",
        formula="(volume > volume.rolling(20).mean() * 0.8) & (volume < volume.rolling(20).mean() * 1.2) & (abs(close - close.shift(1)) / (close.shift(1) + 1e-8) < 0.005)",
        lookback_period=20,
        complexity=FeatureComplexity.SIMPLE,
    ),
    "vp_vol_flat_price_down": KLineFeatureDefinition(
        name="vp_vol_flat_price_down",
        display_name="量平价跌",
        feature_type=KLineFeatureType.VOLUME,
        description="量能平稳价格下跌，阴跌走势，持币者逐步离场",
        formula="(volume > volume.rolling(20).mean() * 0.8) & (volume < volume.rolling(20).mean() * 1.2) & (close < close.shift(1))",
        lookback_period=20,
        complexity=FeatureComplexity.SIMPLE,
        suitable_for_condition=True,
    ),
    "vp_vol_down_price_up": KLineFeatureDefinition(
        name="vp_vol_down_price_up",
        display_name="量缩价升",
        feature_type=KLineFeatureType.VOLUME,
        description="缩量上涨，上涨动能不足，可能见顶回落",
        formula="(volume < volume.rolling(20).mean() * 0.7) & (close > close.shift(1))",
        lookback_period=20,
        complexity=FeatureComplexity.SIMPLE,
        suitable_for_condition=True,
    ),
    "vp_vol_down_price_flat": KLineFeatureDefinition(
        name="vp_vol_down_price_flat",
        display_name="量缩价平",
        feature_type=KLineFeatureType.VOLUME,
        description="缩量横盘，市场极度冷清，关注突破方向",
        formula="(volume < volume.rolling(20).mean() * 0.7) & (abs(close - close.shift(1)) / (close.shift(1) + 1e-8) < 0.005)",
        lookback_period=20,
        complexity=FeatureComplexity.SIMPLE,
    ),
    "vp_vol_down_price_down": KLineFeatureDefinition(
        name="vp_vol_down_price_down",
        display_name="量缩价跌",
        feature_type=KLineFeatureType.VOLUME,
        description="缩量下跌，卖压减弱，可能接近底部或阴跌不止",
        formula="(volume < volume.rolling(20).mean() * 0.7) & (close < close.shift(1))",
        lookback_period=20,
        complexity=FeatureComplexity.SIMPLE,
        suitable_for_condition=True,
    ),

    # ====================================================================
    # 极端形态（5种）
    # ====================================================================
    "vp_sky_vol_sky_price": KLineFeatureDefinition(
        name="vp_sky_vol_sky_price",
        display_name="天量天价",
        feature_type=KLineFeatureType.VOLUME,
        description="成交量创60日新高且价格创60日新高，短期可能见顶",
        formula="(volume >= volume.rolling(60).max()) & (close >= close.rolling(60).max())",
        lookback_period=60,
        complexity=FeatureComplexity.MEDIUM,
        suitable_for_condition=True,
    ),
    "vp_sky_vol_delayed_top": KLineFeatureDefinition(
        name="vp_sky_vol_delayed_top",
        display_name="天量滞涨",
        feature_type=KLineFeatureType.VOLUME,
        description="成交量创60日新高但价格未能创新高，顶部信号",
        formula="(volume >= volume.rolling(60).max()) & (close < high.rolling(10).max())",
        lookback_period=60,
        complexity=FeatureComplexity.MEDIUM,
        suitable_for_condition=True,
    ),
    "vp_ground_vol_ground_price": KLineFeatureDefinition(
        name="vp_ground_vol_ground_price",
        display_name="地量地价",
        feature_type=KLineFeatureType.VOLUME,
        description="成交量创60日新低且价格创60日新低，卖压衰竭底部信号",
        formula="(volume <= volume.rolling(60).min()) & (close <= close.rolling(60).min())",
        lookback_period=60,
        complexity=FeatureComplexity.MEDIUM,
        suitable_for_condition=True,
    ),
    "vp_ground_vol_delayed_bot": KLineFeatureDefinition(
        name="vp_ground_vol_delayed_bot",
        display_name="地量企稳",
        feature_type=KLineFeatureType.VOLUME,
        description="成交量极度萎缩但价格不再创新低，底部企稳",
        formula="(volume <= volume.rolling(60).min() * 1.1) & (close > low.rolling(20).min())",
        lookback_period=60,
        complexity=FeatureComplexity.MEDIUM,
        suitable_for_condition=True,
    ),
    "vp_panic_shrink_bottom": KLineFeatureDefinition(
        name="vp_panic_shrink_bottom",
        display_name="恐慌缩量见底",
        feature_type=KLineFeatureType.VOLUME,
        description="前期放量暴跌后量能骤缩，恐慌结束底部形态",
        formula="(volume < volume.rolling(20).mean() * 0.4) & (close.shift(3) < close.shift(8)) & (volume.shift(3) > volume.rolling(20).mean().shift(3) * 2)",
        lookback_period=20,
        complexity=FeatureComplexity.COMPLEX,
        suitable_for_condition=True,
    ),

    # ====================================================================
    # 放量专题（5种）
    # ====================================================================
    "vp_vol_break": KLineFeatureDefinition(
        name="vp_vol_break",
        display_name="放量突破",
        feature_type=KLineFeatureType.VOLUME,
        description="成交量大幅放大且价格突破20日高点，有效突破信号",
        formula="(volume > volume.rolling(20).mean() * 2.0) & (close > high.rolling(20).max().shift(1))",
        lookback_period=20,
        complexity=FeatureComplexity.MEDIUM,
        suitable_for_condition=True,
        suitable_for_alpha=True,
    ),
    "vp_vol_stall": KLineFeatureDefinition(
        name="vp_vol_stall",
        display_name="放量滞涨",
        feature_type=KLineFeatureType.VOLUME,
        description="巨量换手但涨幅极小，上方压力巨大，高位出货嫌疑",
        formula="(volume > volume.rolling(20).mean() * 2.0) & (abs(close - open) / (open + 1e-8) < 0.01) & (close > close.rolling(20).mean())",
        lookback_period=20,
        complexity=FeatureComplexity.MEDIUM,
        suitable_for_condition=True,
    ),
    "vp_vol_crash": KLineFeatureDefinition(
        name="vp_vol_crash",
        display_name="放量杀跌",
        feature_type=KLineFeatureType.VOLUME,
        description="巨量下跌，恐慌性抛售，短期可能超跌反弹",
        formula="(volume > volume.rolling(20).mean() * 2.0) & ((close - open) / (open + 1e-8) < -0.03)",
        lookback_period=20,
        complexity=FeatureComplexity.MEDIUM,
        suitable_for_condition=True,
    ),
    "vp_vol_retest": KLineFeatureDefinition(
        name="vp_vol_retest",
        display_name="放量回踩确认",
        feature_type=KLineFeatureType.VOLUME,
        description="突破后回踩放量企稳，确认支撑有效",
        formula="(volume > volume.rolling(20).mean() * 1.5) & (low <= close.rolling(20).mean()) & (close > close.rolling(20).mean()) & (close.shift(5) > close.rolling(20).mean().shift(5))",
        lookback_period=20,
        complexity=FeatureComplexity.COMPLEX,
        suitable_for_condition=True,
    ),
    "vp_vol_pulse": KLineFeatureDefinition(
        name="vp_vol_pulse",
        display_name="脉冲放量",
        feature_type=KLineFeatureType.VOLUME,
        description="单日成交量突增3倍以上（相对5日均量），异动信号",
        formula="(volume > volume.rolling(5).mean() * 3.0)",
        lookback_period=5,
        complexity=FeatureComplexity.SIMPLE,
        suitable_for_condition=True,
    ),

    # ====================================================================
    # 缩量专题（5种）
    # ====================================================================
    "vp_shrink_pullback": KLineFeatureDefinition(
        name="vp_shrink_pullback",
        display_name="缩量回调",
        feature_type=KLineFeatureType.VOLUME,
        description="价格回调时成交量萎缩，抛压有限，健康回调",
        formula="(volume < volume.rolling(10).mean() * 0.7) & (close < close.shift(1)) & (close > close.rolling(20).mean())",
        lookback_period=20,
        complexity=FeatureComplexity.MEDIUM,
        suitable_for_condition=True,
        suitable_for_alpha=True,
    ),
    "vp_shrink_drift_down": KLineFeatureDefinition(
        name="vp_shrink_drift_down",
        display_name="缩量阴跌",
        feature_type=KLineFeatureType.VOLUME,
        description="持续缩量下跌，无抵抗式下跌，底部未明",
        formula="(volume < volume.rolling(20).mean() * 0.6) & (close < close.shift(1)) & (close < close.rolling(20).mean())",
        lookback_period=20,
        complexity=FeatureComplexity.MEDIUM,
        suitable_for_condition=True,
    ),
    "vp_shrink_breakout": KLineFeatureDefinition(
        name="vp_shrink_breakout",
        display_name="缩量突破",
        feature_type=KLineFeatureType.VOLUME,
        description="缩量创新高，筹码高度集中，一致看多",
        formula="(volume < volume.rolling(20).mean() * 0.8) & (close >= close.rolling(20).max())",
        lookback_period=20,
        complexity=FeatureComplexity.MEDIUM,
        suitable_for_condition=True,
    ),
    "vp_shrink_limit_up": KLineFeatureDefinition(
        name="vp_shrink_limit_up",
        display_name="缩量涨停",
        feature_type=KLineFeatureType.VOLUME,
        description="极小成交量封涨停，筹码锁定好，后续看涨",
        formula="(volume < volume.rolling(10).mean() * 0.5) & ((close - close.shift(1)) / (close.shift(1) + 1e-8) > 0.095)",
        lookback_period=10,
        complexity=FeatureComplexity.MEDIUM,
        suitable_for_condition=True,
    ),
    "vp_shrink_limit_down": KLineFeatureDefinition(
        name="vp_shrink_limit_down",
        display_name="缩量跌停",
        feature_type=KLineFeatureType.VOLUME,
        description="极小成交量封跌停，无人接盘，恐慌持续",
        formula="(volume < volume.rolling(10).mean() * 0.5) & ((close - close.shift(1)) / (close.shift(1) + 1e-8) < -0.095)",
        lookback_period=10,
        complexity=FeatureComplexity.MEDIUM,
        suitable_for_condition=True,
    ),

    # ====================================================================
    # 量能结构（3种）
    # ====================================================================
    "vp_flat_vol_push": KLineFeatureDefinition(
        name="vp_flat_vol_push",
        display_name="平量推升",
        feature_type=KLineFeatureType.VOLUME,
        description="成交量保持稳定水平，价格稳步上行，健康上涨结构",
        formula="(volume > volume.rolling(10).mean() * 0.9) & (volume < volume.rolling(10).mean() * 1.1) & (close > close.shift(3)) & (close.shift(1) > close.shift(4))",
        lookback_period=10,
        complexity=FeatureComplexity.MEDIUM,
        suitable_for_condition=True,
    ),
    "vp_vol_pile": KLineFeatureDefinition(
        name="vp_vol_pile",
        display_name="堆量",
        feature_type=KLineFeatureType.VOLUME,
        description="成交量逐步放大形成堆积，主力持续建仓信号",
        formula="(volume.rolling(5).mean() > volume.rolling(20).mean() * 1.2) & (volume > volume.shift(1)) & (volume.shift(1) > volume.shift(2))",
        lookback_period=20,
        complexity=FeatureComplexity.MEDIUM,
        suitable_for_condition=True,
    ),
    "vp_vol_pit": KLineFeatureDefinition(
        name="vp_vol_pit",
        display_name="凹量（量坑）",
        feature_type=KLineFeatureType.VOLUME,
        description="成交量先缩后增形成凹槽，洗盘结束放量启动信号",
        formula="(volume > volume.shift(1) * 1.3) & (volume.shift(1) < volume.rolling(20).mean().shift(1) * 0.6) & (volume.shift(2) < volume.rolling(20).mean().shift(2) * 0.6)",
        lookback_period=20,
        complexity=FeatureComplexity.COMPLEX,
        suitable_for_condition=True,
    ),

    # ====================================================================
    # 量价背离（2种）
    # ====================================================================
    "vp_divergence_top": KLineFeatureDefinition(
        name="vp_divergence_top",
        display_name="量价顶背离",
        feature_type=KLineFeatureType.VOLUME,
        description="价格创N日新高但成交量不创新高，上涨动能衰竭",
        formula="(close >= close.rolling(20).max()) & (volume < volume.rolling(20).max() * 0.8)",
        lookback_period=20,
        complexity=FeatureComplexity.MEDIUM,
        suitable_for_condition=True,
    ),
    "vp_divergence_bottom": KLineFeatureDefinition(
        name="vp_divergence_bottom",
        display_name="量价底背离",
        feature_type=KLineFeatureType.VOLUME,
        description="价格创N日新低但成交量萎缩不创新低，卖压枯竭",
        formula="(close <= close.rolling(20).min()) & (volume > volume.rolling(20).min() * 1.2)",
        lookback_period=20,
        complexity=FeatureComplexity.MEDIUM,
        suitable_for_condition=True,
    ),

    # ====================================================================
    # 缺口量价（4种）
    # ====================================================================
    "vp_gap_up_vol_up": KLineFeatureDefinition(
        name="vp_gap_up_vol_up",
        display_name="放量跳空上涨",
        feature_type=KLineFeatureType.VOLUME,
        description="向上跳空开盘且放量，强力看多信号",
        formula="(open > close.shift(1) * 1.01) & (volume > volume.rolling(20).mean() * 1.5)",
        lookback_period=20,
        complexity=FeatureComplexity.SIMPLE,
        suitable_for_condition=True,
    ),
    "vp_gap_down_vol_up": KLineFeatureDefinition(
        name="vp_gap_down_vol_up",
        display_name="放量跳空下跌",
        feature_type=KLineFeatureType.VOLUME,
        description="向下跳空开盘且放量，恐慌性抛售",
        formula="(open < close.shift(1) * 0.99) & (volume > volume.rolling(20).mean() * 1.5)",
        lookback_period=20,
        complexity=FeatureComplexity.SIMPLE,
        suitable_for_condition=True,
    ),
    "vp_gap_up_vol_down": KLineFeatureDefinition(
        name="vp_gap_up_vol_down",
        display_name="缩量跳空上涨",
        feature_type=KLineFeatureType.VOLUME,
        description="向上跳空但缩量，可能假突破或涨停缩量",
        formula="(open > close.shift(1) * 1.01) & (volume < volume.rolling(20).mean() * 0.7)",
        lookback_period=20,
        complexity=FeatureComplexity.SIMPLE,
        suitable_for_condition=True,
    ),
    "vp_gap_down_vol_down": KLineFeatureDefinition(
        name="vp_gap_down_vol_down",
        display_name="缩量跳空下跌",
        feature_type=KLineFeatureType.VOLUME,
        description="向下跳空但缩量，低开企稳或缩量跌停",
        formula="(open < close.shift(1) * 0.99) & (volume < volume.rolling(20).mean() * 0.7)",
        lookback_period=20,
        complexity=FeatureComplexity.SIMPLE,
        suitable_for_condition=True,
    ),

    # ====================================================================
    # 主力行为（3种）
    # ====================================================================
    "vp_fake_vol_churn": KLineFeatureDefinition(
        name="vp_fake_vol_churn",
        display_name="高位对倒放量",
        feature_type=KLineFeatureType.VOLUME,
        description="高位巨量但K线实体极小(上下影线长)，对倒出货嫌疑",
        formula="(volume > volume.rolling(20).mean() * 2.5) & (abs(close - open) / (high - low + 1e-8) < 0.2) & (close > close.rolling(60).mean() * 1.1)",
        lookback_period=60,
        complexity=FeatureComplexity.COMPLEX,
        suitable_for_condition=True,
    ),
    "vp_washout_vol": KLineFeatureDefinition(
        name="vp_washout_vol",
        display_name="洗盘放量",
        feature_type=KLineFeatureType.VOLUME,
        description="趋势中放量长下影线收阳，主力洗盘后拉回",
        formula="(volume > volume.rolling(20).mean() * 1.5) & ((close - low) / (high - low + 1e-8) > 0.6) & (close > open) & (close > close.rolling(20).mean())",
        lookback_period=20,
        complexity=FeatureComplexity.MEDIUM,
        suitable_for_condition=True,
    ),
    "vp_test_vol": KLineFeatureDefinition(
        name="vp_test_vol",
        display_name="试盘放量",
        feature_type=KLineFeatureType.VOLUME,
        description="低位放量长上影线，试探上方压力盘",
        formula="(volume > volume.rolling(20).mean() * 1.5) & ((high - close) / (high - low + 1e-8) > 0.5) & (close < close.rolling(60).mean())",
        lookback_period=60,
        complexity=FeatureComplexity.MEDIUM,
        suitable_for_condition=True,
    ),
}