import pathlib, ast

BASE = pathlib.Path(r'C:\Users\hdec\Documents\GitHub\vnpy\vnpy\vnpy\market_behavior')
ae   = BASE / 'engine' / 'adapter_engine.py'
lines = ae.read_text(encoding='utf-8', errors='replace').splitlines()

# 第592行（0-based 591）是 trend_slope 的最后一行
# 在它后面插入 Phase 11.1 分支 + return False, 0.0
insert_after = 592  # 1-based，插在第592行之后

new_code = [
    '',
    '        # Phase 11.1: MACD 金叉',
    '        if ct == COND_MACD_GOLDEN:',
    '            from .signal_engine import is_golden_cross',
    '            fast   = int(p.get("fast", 12))',
    '            slow_  = int(p.get("slow", 26))',
    '            sig    = int(p.get("signal", 9))',
    '            closes = [b.close for b in bars]',
    '            passed = is_golden_cross(closes, fast, slow_, sig)',
    '            return passed, 1.0 if passed else 0.0',
    '',
    '        # Phase 11.1: MACD 死叉',
    '        if ct == COND_MACD_DEATH:',
    '            from .signal_engine import is_death_cross',
    '            fast   = int(p.get("fast", 12))',
    '            slow_  = int(p.get("slow", 26))',
    '            sig    = int(p.get("signal", 9))',
    '            closes = [b.close for b in bars]',
    '            passed = is_death_cross(closes, fast, slow_, sig)',
    '            return passed, 1.0 if passed else 0.0',
    '',
    '        # Phase 11.1: 周线 MA 斜率向上',
    '        if ct == COND_WEEKLY_MA_SLOPE:',
    '            import math as _math',
    '            ma_period    = int(p.get("ma_period", 13))',
    '            slope_window = int(p.get("slope_window", 5))',
    '            min_slope    = float(p.get("min_slope", 0.0))',
    '            multi_tf     = p.get("multi_tf_engine")',
    '            if multi_tf is None or not bars:',
    '                return False, 0.0',
    '            sym   = bars[0].symbol',
    '            slope = multi_tf.get_weekly_ma_slope(sym, ma_period, slope_window)',
    '            if _math.isnan(slope):',
    '                return False, 0.0',
    '            passed = slope >= min_slope',
    '            score  = min(max((slope - min_slope) / (abs(min_slope) + 0.5), 0.0), 1.0)',
    '            return passed, score if passed else 0.0',
    '',
    '        # Phase 11.1: 回踩检测（mode: pct_drop / from_high / to_ma）',
    '        if ct == COND_PULLBACK:',
    '            from .signal_engine import detect_pullback',
    '            mode       = p.get("mode", "pct_drop")',
    '            window     = int(p.get("window", 10))',
    '            min_drop   = float(p.get("min_drop", -8.0))',
    '            max_drop   = float(p.get("max_drop", -2.0))',
    '            ma_period  = int(p.get("ma_period", 20))',
    '            ma_tol_pct = float(p.get("ma_tol_pct", 2.0))',
    '            closes = [b.close for b in bars]',
    '            highs  = [b.high  for b in bars]',
    '            return detect_pullback(closes, highs, mode, window,',
    '                                   min_drop, max_drop, ma_period, ma_tol_pct)',
    '',
    '        # Phase 11.1: RSI 范围过滤',
    '        if ct == COND_RSI_RANGE:',
    '            import math as _math',
    '            from .signal_engine import rsi as _rsi',
    '            period  = int(p.get("period", 14))',
    '            min_rsi = float(p.get("min", 30.0))',
    '            max_rsi = float(p.get("max", 70.0))',
    '            closes  = [b.close for b in bars]',
    '            val     = _rsi(closes, period)',
    '            if _math.isnan(val):',
    '                return False, 0.0',
    '            passed = min_rsi <= val <= max_rsi',
    '            score  = 1.0 - abs(val - (min_rsi+max_rsi)/2) / ((max_rsi-min_rsi)/2 + 1e-9)',
    '            return passed, max(score, 0.0) if passed else 0.0',
    '',
    '        # Phase 11.1: 布林带宽度',
    '        if ct == COND_BOLL_WIDTH:',
    '            import math as _math',
    '            from .signal_engine import bollinger as _boll',
    '            period    = int(p.get("period", 20))',
    '            std_mult  = float(p.get("std_mult", 2.0))',
    '            min_width = float(p.get("min", 0.0))',
    '            max_width = float(p.get("max", 9999.0))',
    '            closes    = [b.close for b in bars]',
    '            w         = _boll(closes, period, std_mult)["width"]',
    '            if _math.isnan(w):',
    '                return False, 0.0',
    '            passed = min_width <= w <= max_width',
    '            return passed, min(w / (max_width if max_width < 9999 else w+1), 1.0) if passed else 0.0',
    '',
    '        # Phase 11.1: ATR 相对振幅',
    '        if ct == COND_ATR_RATIO:',
    '            import math as _math',
    '            from .signal_engine import atr as _atr',
    '            period    = int(p.get("period", 14))',
    '            min_ratio = float(p.get("min", 0.0))',
    '            max_ratio = float(p.get("max", 9999.0))',
    '            closes    = [b.close for b in bars]',
    '            highs     = [b.high  for b in bars]',
    '            lows      = [b.low   for b in bars]',
    '            atr_val   = _atr(highs, lows, closes, period)',
    '            if _math.isnan(atr_val) or bars[-1].close <= 0:',
    '                return False, 0.0',
    '            ratio  = atr_val / bars[-1].close * 100',
    '            passed = min_ratio <= ratio <= max_ratio',
    '            score  = min(ratio / (min_ratio * 2 if min_ratio > 0 else ratio+1), 1.0)',
    '            return passed, score if passed else 0.0',
    '',
    '        return False, 0.0',
]

for i, line in enumerate(new_code):
    lines.insert(insert_after + i, line)

ae.write_text('\n'.join(lines), encoding='utf-8')
print(f'adapter_engine.py updated: {len(lines)} lines')

try:
    ast.parse('\n'.join(lines))
    print('syntax OK')
except SyntaxError as e:
    print(f'SYNTAX ERROR: {e}')
