import pathlib
P = pathlib.Path(r"c:\Users\11229\Documents\GitHub\vnpy\tests\test_temporal_intelligence.py")
with open(P, "a", encoding="utf-8") as f:
    f.write("\n\nclass TestTransitionEngine:\n")
    f.write("    def _rets(self, n=200, mean=0.001, vol=0.02, seed=3):\n")
    f.write("        import random as rr; rr.seed(seed)\n")
    f.write("        return [rr.gauss(mean, vol) for _ in range(n)]\n")
    f.write("    def _prices(self, rets, p0=100.0):\n")
    f.write("        ps = [p0]\n")
    f.write("        for r in rets: ps.append(ps[-1] * (1 + r))\n")
    f.write("        return ps\n")
    f.write("    def _engine(self):\n")
    f.write("        from vnpy.temporal_intelligence_ai.engine.transition_engine import TransitionEngine\n")
    f.write("        eng = TransitionEngine()\n")
    f.write("        eng.configure(regime_fast=10, regime_slow=40, regime_thresh=1.5,\n")
    f.write("                      vol_short=10, vol_long=40, vol_ratio=1.5,\n")
    f.write("                      liq_short=10, liq_long=40, liq_thresh=1.3)\n")
    f.write("        return eng\n")
    f.write("    def test_detect_returns_state(self):\n")
    f.write("        eng = self._engine(); rets = self._rets(200)\n")
    f.write("        eng.update_series(prices=self._prices(rets), returns=rets)\n")
    f.write("        assert eng.detect() is not None\n")
    f.write("    def test_prob_range(self):\n")
    f.write("        eng = self._engine(); rets = self._rets(200)\n")
    f.write("        eng.update_series(prices=self._prices(rets), returns=rets)\n")
    f.write("        s = eng.detect()\n")
    f.write("        assert 0.0 <= s.transition_prob <= 1.0\n")
    f.write("        assert 0.0 <= s.transition_confidence <= 1.0\n")
    f.write("    def test_regime_probs_sum(self):\n")
    f.write("        eng = self._engine(); rets = self._rets(200)\n")
    f.write("        eng.update_series(prices=self._prices(rets), returns=rets)\n")
    f.write("        total = sum(eng.detect().regime_probs.probabilities.values())\n")
    f.write("        assert total == pytest.approx(1.0, abs=0.02)\n")
    f.write("    def test_context_preserved(self):\n")
    f.write("        from vnpy.temporal_intelligence_ai.constant import RegimeType, CyclePhase\n")
    f.write("        eng = self._engine()\n")
    f.write("        eng.set_context(regime=RegimeType.BEAR_VOLATILE, phase=CyclePhase.CONTRACTION,\n")
    f.write("                        current_vol=0.40, current_trend=-0.15)\n")
    f.write("        rets = self._rets(200)\n")
    f.write("        eng.update_series(prices=self._prices(rets), returns=rets)\n")
    f.write("        assert eng.detect().current_regime == RegimeType.BEAR_VOLATILE\n")
    f.write("    def test_summary_keys(self):\n")
    f.write("        eng = self._engine(); rets = self._rets(200)\n")
    f.write("        eng.update_series(prices=self._prices(rets), returns=rets)\n")
    f.write("        eng.detect()\n")
    f.write("        summ = eng.get_summary()\n")
    f.write("        assert all(k in summ for k in\n")
    f.write("                   ('transition_prob','transition_confidence','is_transitioning','current_regime'))\n")
    f.write("\n\nclass TestValidationEngine:\n")
    f.write("    def _engine(self):\n")
    f.write("        from vnpy.temporal_intelligence_ai.engine.validation_engine import ValidationEngine\n")
    f.write("        return ValidationEngine()\n")
    f.write("    def _rec(self, rid, pred, real=None, realized=False, horizon=5):\n")
    f.write("        from vnpy.temporal_intelligence_ai.model.validation_model import ValidationRecord\n")
    f.write("        return ValidationRecord(record_id=rid, predicted=pred,\n")
    f.write("                                realized=real, is_realized=realized, horizon_bars=horizon)\n")
    f.write("    def test_empty_validate(self):\n")
    f.write("        assert self._engine().validate().metrics.n_records == 0\n")
    f.write("    def test_unrealized_excluded(self):\n")
    f.write("        eng = self._engine()\n")
    f.write("        eng.submit_prediction(self._rec('r1', pred=0.5))\n")
    f.write("        assert eng.validate().metrics.n_realized == 0\n")
    f.write("    def test_realized_included(self):\n")
    f.write("        import random as rr; rr.seed(42)\n")
    f.write("        eng = self._engine()\n")
    f.write("        for i in range(20):\n")
    f.write("            p = rr.gauss(0, 1)\n")
    f.write("            eng.submit_prediction(self._rec(f'r{i}', p, real=p+rr.gauss(0,0.1), realized=True))\n")
    f.write("        assert eng.validate().metrics.n_realized == 20\n")
    f.write("    def test_realize_method(self):\n")
    f.write("        eng = self._engine()\n")
    f.write("        eng.submit_prediction(self._rec('x1', pred=0.3))\n")
    f.write("        eng.realize('x1', 0.28)\n")
    f.write("        assert eng.validate().metrics.n_realized == 1\n")
    f.write("    def test_perfect_predictions(self):\n")
    f.write("        eng = self._engine()\n")
    f.write("        for i in range(30):\n")
    f.write("            v = float(i) * 0.01\n")
    f.write("            eng.submit_prediction(self._rec(f'p{i}', v, real=v, realized=True))\n")
    f.write("        m = eng.validate().metrics\n")
    f.write("        assert m.direction_acc == pytest.approx(1.0, abs=0.01)\n")
    f.write("        assert m.bias == pytest.approx(0.0, abs=1e-6)\n")
    f.write("    def test_good_better_than_bad(self):\n")
    f.write("        import random as rr; rr.seed(7)\n")
    f.write("        eg, eb = self._engine(), self._engine()\n")
    f.write("        for i in range(40):\n")
    f.write("            p = rr.gauss(0, 1)\n")
    f.write("            eg.submit_prediction(self._rec(f'g{i}', p, real=p+rr.gauss(0,0.02), realized=True))\n")
    f.write("            eb.submit_prediction(self._rec(f'b{i}', p, real=-p+rr.gauss(0,0.5), realized=True))\n")
    f.write("        assert eg.validate().metrics.temporal_health > eb.validate().metrics.temporal_health\n")
    f.write("    def test_history_length(self):\n")
    f.write("        eng = self._engine()\n")
    f.write("        for _ in range(5): eng.validate()\n")
    f.write("        assert len(eng.get_history().snapshots) == 5\n")
print("transition+validation appended")
