import pathlib
P = pathlib.Path(r"c:\Users\11229\Documents\GitHub\vnpy\tests\test_temporal_intelligence.py")
with open(P, "a", encoding="utf-8") as f:
    f.write("\n\nclass TestModels:\n")
    f.write("    def test_cycle_state_to_dict(self):\n")
    f.write("        from vnpy.temporal_intelligence_ai.model.cycle_model import CycleMetrics, CycleState\n")
    f.write("        from vnpy.temporal_intelligence_ai.constant import CyclePhase, RegimeType\n")
    f.write("        m = CycleMetrics(volatility=0.20, trend_strength=0.10, momentum=0.05, drawdown=0.08, breadth=0.6)\n")
    f.write("        d = CycleState(phase=CyclePhase.EXPANSION, regime=RegimeType.BULL_QUIET, confidence=0.75, metrics=m).to_dict()\n")
    f.write("        assert d['phase'] == 'expansion'\n")
    f.write("        assert d['confidence'] == pytest.approx(0.75)\n")
    f.write("    def test_decay_state_to_dict(self):\n")
    f.write("        from vnpy.temporal_intelligence_ai.model.decay_model import DecayMetrics, DecayState\n")
    f.write("        from vnpy.temporal_intelligence_ai.constant import DecayMode\n")
    f.write("        m = DecayMetrics(combined_strength=0.65, half_life=20.0, decay_rate=0.05, age_bars=10)\n")
    f.write("        d = DecayState(alpha_id='A1', mode=DecayMode.EXPONENTIAL, metrics=m).to_dict()\n")
    f.write("        assert d['alpha_id'] == 'A1'\n")
    f.write("        assert d['combined_strength'] == pytest.approx(0.65, abs=1e-4)\n")
    f.write("    def test_dependency_matrix_symmetric(self):\n")
    f.write("        from vnpy.temporal_intelligence_ai.model.dependency_model import DependencyMatrix\n")
    f.write("        dm = DependencyMatrix(signal_ids=['a', 'b', 'c'])\n")
    f.write("        dm.set('a', 'b', 0.72)\n")
    f.write("        assert dm.get('a', 'b') == dm.get('b', 'a') == pytest.approx(0.72)\n")
    f.write("        assert dm.get('a', 'c') == 0.0\n")
    f.write("    def test_regime_probability_dominant(self):\n")
    f.write("        from vnpy.temporal_intelligence_ai.model.transition_model import RegimeProbability\n")
    f.write("        from vnpy.temporal_intelligence_ai.constant import RegimeType\n")
    f.write("        rp = RegimeProbability(probabilities={\n")
    f.write("            RegimeType.BULL_QUIET.value: 0.55,\n")
    f.write("            RegimeType.SIDEWAYS.value: 0.30,\n")
    f.write("            RegimeType.BEAR_QUIET.value: 0.15})\n")
    f.write("        assert rp.dominant() == RegimeType.BULL_QUIET.value\n")
    f.write("        assert rp.confidence() == pytest.approx(0.55)\n")
    f.write("    def test_validation_history_max_size(self):\n")
    f.write("        from vnpy.temporal_intelligence_ai.model.validation_model import ValidationHistory, ValidationState\n")
    f.write("        h = ValidationHistory(max_size=5)\n")
    f.write("        for _ in range(10): h.append_snapshot(ValidationState())\n")
    f.write("        assert len(h.snapshots) == 5\n")
    f.write("    def test_decay_curve_strengths(self):\n")
    f.write("        from vnpy.temporal_intelligence_ai.model.decay_model import DecayCurve, DecayCurvePoint\n")
    f.write("        from vnpy.temporal_intelligence_ai.constant import DecayMode\n")
    f.write("        pts = [DecayCurvePoint(bar=i, strength=1.0 - i * 0.05) for i in range(10)]\n")
    f.write("        c = DecayCurve(alpha_id='X', mode=DecayMode.EXPONENTIAL, points=pts)\n")
    f.write("        ss = c.strengths()\n")
    f.write("        assert len(ss) == 10 and ss[0] > ss[-1]\n")

    f.write("\n\nclass TestEndToEnd:\n")
    f.write("    def test_decay_to_validation(self):\n")
    f.write("        import random as rr; rr.seed(42)\n")
    f.write("        import math as mm\n")
    f.write("        from vnpy.temporal_intelligence_ai.engine.decay_engine import DecayEngine\n")
    f.write("        from vnpy.temporal_intelligence_ai.engine.validation_engine import ValidationEngine\n")
    f.write("        from vnpy.temporal_intelligence_ai.datasource.alpha_loader import AlphaRecord\n")
    f.write("        from vnpy.temporal_intelligence_ai.model.validation_model import ValidationRecord\n")
    f.write("        from vnpy.temporal_intelligence_ai.utils.decay_utils import half_life_to_rate\n")
    f.write("        decay_eng = DecayEngine(); val_eng = ValidationEngine()\n")
    f.write("        for i in range(10):\n")
    f.write("            decay_eng.register_alpha(AlphaRecord(alpha_id=f'a{i}', created_bar=0,\n")
    f.write("                base_decay_rate=half_life_to_rate(rr.randint(10, 40))))\n")
    f.write("        pred_s = []\n")
    f.write("        for bar in range(1, 51):\n")
    f.write("            st = decay_eng.compute(bar)\n")
    f.write("            if st: pred_s.append(st[0].metrics.combined_strength)\n")
    f.write("        for i, s in enumerate(pred_s):\n")
    f.write("            val_eng.submit_prediction(ValidationRecord(record_id=f'v{i}', predicted=s,\n")
    f.write("                realized=max(0.0, s + rr.gauss(0, 0.02)), is_realized=True))\n")
    f.write("        state = val_eng.validate()\n")
    f.write("        assert state.metrics.temporal_health > 0\n")
    f.write("        assert state.metrics.n_realized == len(pred_s)\n")

    f.write("    def test_dependency_then_transition(self):\n")
    f.write("        import random as rr; rr.seed(10)\n")
    f.write("        from vnpy.temporal_intelligence_ai.engine.dependency_engine import DependencyEngine\n")
    f.write("        from vnpy.temporal_intelligence_ai.engine.transition_engine import TransitionEngine\n")
    f.write("        n = 250; v = 0.0; series = []\n")
    f.write("        for _ in range(n):\n")
    f.write("            v = 0.8 * v + rr.gauss(0, 1); series.append(v)\n")
    f.write("        rets = [rr.gauss(0.001, 0.02) for _ in range(n)]\n")
    f.write("        prices = [100.0]\n")
    f.write("        for r in rets: prices.append(prices[-1] * (1 + r))\n")
    f.write("        dep_eng = DependencyEngine()\n")
    f.write("        dep_eng.register_signal('s', series)\n")
    f.write("        assert dep_eng.analyze() is not None\n")
    f.write("        tran_eng = TransitionEngine()\n")
    f.write("        tran_eng.configure(regime_fast=10, regime_slow=40,\n")
    f.write("                           vol_short=10, vol_long=40, liq_short=10, liq_long=40)\n")
    f.write("        tran_eng.update_series(prices=prices, returns=rets)\n")
    f.write("        tran_state = tran_eng.detect()\n")
    f.write("        assert tran_state is not None\n")
    f.write("        assert 0 <= tran_state.transition_prob <= 1.0\n")

    f.write("    def test_full_pipeline(self):\n")
    f.write("        import random as rr; rr.seed(99)\n")
    f.write("        import math as mm\n")
    f.write("        from vnpy.temporal_intelligence_ai.engine.decay_engine import DecayEngine\n")
    f.write("        from vnpy.temporal_intelligence_ai.engine.dependency_engine import DependencyEngine\n")
    f.write("        from vnpy.temporal_intelligence_ai.engine.transition_engine import TransitionEngine\n")
    f.write("        from vnpy.temporal_intelligence_ai.engine.validation_engine import ValidationEngine\n")
    f.write("        from vnpy.temporal_intelligence_ai.datasource.alpha_loader import AlphaRecord\n")
    f.write("        from vnpy.temporal_intelligence_ai.model.validation_model import ValidationRecord\n")
    f.write("        from vnpy.temporal_intelligence_ai.utils.decay_utils import half_life_to_rate\n")
    f.write("        from vnpy.temporal_intelligence_ai.constant import RegimeType, CyclePhase, DecayMode\n")
    f.write("        n = 300\n")
    f.write("        rets = [rr.gauss(0.0005, 0.018) for _ in range(n)]\n")
    f.write("        prices = [100.0]\n")
    f.write("        for r in rets: prices.append(prices[-1] * (1 + r))\n")
    f.write("        sig = [sum(rets[max(0, i-5):i+1]) for i in range(n)]\n")
    f.write("        decay_eng = DecayEngine()\n")
    f.write("        decay_eng.configure(mode=DecayMode.REGIME_DEPENDENT)\n")
    f.write("        decay_eng.set_context(regime=RegimeType.BULL_QUIET, phase=CyclePhase.EXPANSION,\n")
    f.write("                              current_vol=0.18, current_bar=0)\n")
    f.write("        for i in range(5):\n")
    f.write("            decay_eng.register_alpha(AlphaRecord(alpha_id=f'a{i}', created_bar=0,\n")
    f.write("                base_decay_rate=half_life_to_rate(20 + i * 5)))\n")
    f.write("        decay_states = decay_eng.compute(bar=50)\n")
    f.write("        assert len(decay_states) == 5\n")
    f.write("        dep_eng = DependencyEngine()\n")
    f.write("        dep_eng.register_signal('rets', rets)\n")
    f.write("        dep_eng.register_signal('cum', sig)\n")
    f.write("        assert dep_eng.analyze() is not None\n")
    f.write("        tran_eng = TransitionEngine()\n")
    f.write("        tran_eng.configure(regime_fast=10, regime_slow=40,\n")
    f.write("                           vol_short=10, vol_long=40, liq_short=10, liq_long=40)\n")
    f.write("        tran_eng.update_series(prices=prices, returns=rets)\n")
    f.write("        assert tran_eng.detect() is not None\n")
    f.write("        val_eng = ValidationEngine()\n")
    f.write("        for i, ds in enumerate(decay_states):\n")
    f.write("            s = ds.metrics.combined_strength\n")
    f.write("            val_eng.submit_prediction(ValidationRecord(record_id=f'v{i}', predicted=s,\n")
    f.write("                realized=s + rr.gauss(0, 0.02), is_realized=True))\n")
    f.write("        pred_s = [mm.exp(-0.05 * t) for t in range(60)]\n")
    f.write("        real_s = [mm.exp(-0.055 * t) for t in range(60)]\n")
    f.write("        val_eng.set_decay_series(pred_s, real_s)\n")
    f.write("        val_state = val_eng.validate()\n")
    f.write("        assert 0 <= val_state.metrics.temporal_health <= 100\n")
    f.write("        assert val_state.metrics.n_realized == 5\n")
print("models+e2e appended")
