"""Append FeatureTab main class to feature_tab.py"""
import pathlib

P = pathlib.Path(
    r"c:\Users\11229\Documents\GitHub\vnpy\vnpy\quant_research\ui\feature_tab.py"
)

LINES = [
    "",
    "",
    "class FeatureTab(QWidget):",
    '    """因子注册中心主 Tab。"""',
    "",
    "    def __init__(self, engine: ResearchEngine, parent=None):",
    "        super().__init__(parent)",
    "        self._engine = engine",
    "        self._all_records: List[FeatureRecord] = []",
    "        self._init_ui()",
    "        self._register_events()",
    "        self._refresh()",
    "",
    "    def _init_ui(self):",
    "        root = QVBoxLayout(self)",
    "        root.setContentsMargins(6, 6, 6, 6)",
    "",
    "        bar1 = QHBoxLayout()",
    "        self._btn_new       = QPushButton('+ 注册因子')",
    "        self._btn_edit      = QPushButton('编辑')",
    "        self._btn_delete    = QPushButton('删除')",
    "        self._btn_ic        = QPushButton('录入 IC')",
    "        self._btn_deprecate = QPushButton('废弃')",
    "        self._btn_restore   = QPushButton('恢复')",
    "        for btn in (self._btn_new, self._btn_edit, self._btn_delete,",
    "                    self._btn_ic, self._btn_deprecate, self._btn_restore):",
    "            bar1.addWidget(btn)",
    "        bar1.addStretch()",
    "        root.addLayout(bar1)",
    "",
    "        bar2 = QHBoxLayout()",
    "        bar2.addWidget(QLabel('状态:'))",
    "        self._status_filter = QComboBox()",
    "        self._status_filter.addItem('全部', None)",
    "        for s in FeatureStatus:",
    "            self._status_filter.addItem(s.value, s)",
    "        self._status_filter.setFixedWidth(130)",
    "        bar2.addWidget(self._status_filter)",
    "        bar2.addWidget(QLabel('分类:'))",
    "        self._category_filter = QComboBox()",
    "        for c in CATEGORIES:",
    "            self._category_filter.addItem(c if c else '全部', c if c else None)",
    "        self._category_filter.setFixedWidth(120)",
    "        bar2.addWidget(self._category_filter)",
    "        self._active_only_cb = QCheckBox('隐藏已废弃')",
    "        bar2.addWidget(self._active_only_cb)",
    "        bar2.addWidget(QLabel('搜索:'))",
    "        self._search_box = QLineEdit()",
    "        self._search_box.setPlaceholderText('名称 / 分类 / 作者 / 公式')",
    "        self._search_box.setFixedWidth(200)",
    "        bar2.addWidget(self._search_box)",
    "        self._btn_search = QPushButton('搜索')",
    "        self._btn_search.setFixedWidth(52)",
    "        bar2.addWidget(self._btn_search)",
    "        self._btn_reset = QPushButton('重置')",
    "        self._btn_reset.setFixedWidth(52)",
    "        bar2.addWidget(self._btn_reset)",
    "        bar2.addStretch()",
    "        root.addLayout(bar2)",
    "",
    "        splitter = QSplitter(Qt.Vertical)",
    "",
    "        self._table = QTableWidget(0, len(HEADERS))",
    "        self._table.setHorizontalHeaderLabels(HEADERS)",
    "        self._table.horizontalHeader().setSectionResizeMode(COL_NAME, QHeaderView.Stretch)",
    "        self._table.horizontalHeader().setSectionResizeMode(COL_ID, QHeaderView.ResizeToContents)",
    "        self._table.setSelectionBehavior(QAbstractItemView.SelectRows)",
    "        self._table.setEditTriggers(QAbstractItemView.NoEditTriggers)",
    "        self._table.setAlternatingRowColors(True)",
    "        self._table.setSortingEnabled(True)",
    "        self._table.verticalHeader().setVisible(False)",
    "        splitter.addWidget(self._table)",
    "",
    "        self._detail = FeatureDetailPanel(self._engine)",
    "        self._detail.setMinimumHeight(200)",
    "        splitter.addWidget(self._detail)",
    "        splitter.setSizes([380, 240])",
    "        root.addWidget(splitter)",
    "",
    "        self._status_bar = QLabel('共 0 条因子')",
    "        root.addWidget(self._status_bar)",
    "",
    "        self._btn_new.clicked.connect(self._on_new)",
    "        self._btn_edit.clicked.connect(self._on_edit)",
    "        self._btn_delete.clicked.connect(self._on_delete)",
    "        self._btn_ic.clicked.connect(self._on_ic)",
    "        self._btn_deprecate.clicked.connect(self._on_deprecate)",
    "        self._btn_restore.clicked.connect(self._on_restore)",
    "        self._btn_search.clicked.connect(self._apply_filter)",
    "        self._btn_reset.clicked.connect(self._reset_filter)",
    "        self._search_box.returnPressed.connect(self._apply_filter)",
    "        self._status_filter.currentIndexChanged.connect(self._apply_filter)",
    "        self._category_filter.currentIndexChanged.connect(self._apply_filter)",
    "        self._active_only_cb.stateChanged.connect(self._apply_filter)",
    "        self._table.currentCellChanged.connect(self._on_row_changed)",
    "        self._table.doubleClicked.connect(self._on_edit)",
    "",
    "    def _register_events(self):",
    "        ee = self._engine.event_engine",
    "        ee.register(EVENT_FEATURE_CREATED, self._on_event)",
    "        ee.register(EVENT_FEATURE_UPDATED, self._on_event)",
    "        ee.register(EVENT_FEATURE_DELETED, self._on_event)",
    "",
    "    def _on_event(self, event: Event):",
    "        self._refresh()",
    "",
    "    def _refresh(self):",
    "        self._all_records = self._engine.list_features()",
    "        self._apply_filter()",
    "",
    "    def _apply_filter(self):",
    "        status      = self._status_filter.currentData()",
    "        category    = self._category_filter.currentData()",
    "        active_only = self._active_only_cb.isChecked()",
    "        keyword     = self._search_box.text().strip()",
    "        if keyword:",
    "            records = self._engine.search_features(keyword)",
    "        else:",
    "            records = self._engine.list_features(",
    "                status=status, category=category, active_only=active_only)",
    "        self._populate_table(records)",
    "",
    "    def _reset_filter(self):",
    "        self._status_filter.setCurrentIndex(0)",
    "        self._category_filter.setCurrentIndex(0)",
    "        self._active_only_cb.setChecked(False)",
    "        self._search_box.clear()",
    "        self._populate_table(self._all_records)",
    "",
    "    def _populate_table(self, records: List[FeatureRecord]):",
    "        self._table.setSortingEnabled(False)",
    "        self._table.setRowCount(0)",
    "        for rec in records:",
    "            r = self._table.rowCount()",
    "            self._table.insertRow(r)",
    "            self._set_row(r, rec)",
    "        self._table.setSortingEnabled(True)",
    "        self._status_bar.setText(f'共 {len(records)} 条因子')",
    "",
    "    def _set_row(self, row: int, rec: FeatureRecord):",
    "        id_item = QTableWidgetItem(rec.feature_id)",
    "        id_item.setData(Qt.UserRole, rec.feature_id)",
    "        self._table.setItem(row, COL_ID, id_item)",
    "        name_item = QTableWidgetItem(rec.name)",
    "        if rec.deprecated_at:",
    "            font = QFont()",
    "            font.setStrikeOut(True)",
    "            name_item.setFont(font)",
    "            name_item.setForeground(QColor('#adb5bd'))",
    "        self._table.setItem(row, COL_NAME, name_item)",
    "        self._table.setItem(row, COL_VERSION, QTableWidgetItem(rec.version))",
    "        status_item = QTableWidgetItem(rec.status.value)",
    "        status_item.setForeground(STATUS_COLORS.get(rec.status, QColor('#333')))",
    "        f = QFont(); f.setBold(True); status_item.setFont(f)",
    "        self._table.setItem(row, COL_STATUS, status_item)",
    "        self._table.setItem(row, COL_CATEGORY, QTableWidgetItem(rec.category))",
    "        self._table.setItem(row, COL_AUTHOR,   QTableWidgetItem(rec.author))",
    "        def _num_item(val, fmt='.4f'):",
    "            item = QTableWidgetItem(f'{val:{fmt}}')",
    "            item.setTextAlignment(Qt.AlignRight | Qt.AlignVCenter)",
    "            if val > 0: item.setForeground(QColor('#198754'))",
    "            elif val < 0: item.setForeground(QColor('#dc3545'))",
    "            return item",
    "        self._table.setItem(row, COL_IC,      _num_item(rec.ic))",
    "        self._table.setItem(row, COL_RANK_IC, _num_item(rec.rank_ic))",
    "        self._table.setItem(row, COL_ICIR,    _num_item(rec.icir))",
    "        self._table.setItem(row, COL_TIME,",
    "            QTableWidgetItem(rec.updated_at.strftime('%Y-%m-%d %H:%M')))",
    "",
    "    def _on_row_changed(self, cur_row, *_):",
    "        rec = self._get_record_at(cur_row)",
    "        if rec:",
    "            self._detail.load(rec)",
    "        else:",
    "            self._detail.clear()",
    "",
    "    def _on_new(self):",
    "        dlg = FeatureCreateDialog(parent=self)",
    "        if dlg.exec() == FeatureCreateDialog.Accepted:",
    "            self._engine.register_feature(",
    "                name=dlg.get_name(), version=dlg.get_version(),",
    "                description=dlg.get_description(), category=dlg.get_category(),",
    "                formula=dlg.get_formula(), author=dlg.get_author(),",
    "                tags=dlg.get_tags(), dependencies=dlg.get_dependencies(),",
    "                dataset_ids=dlg.get_dataset_ids(),",
    "            )",
    "",
    "    def _on_edit(self):",
    "        rec = self._get_selected_record()",
    "        if not rec:",
    "            return",
    "        dlg = FeatureCreateDialog(parent=self, record=rec)",
    "        if dlg.exec() == FeatureCreateDialog.Accepted:",
    "            rec.name         = dlg.get_name()",
    "            rec.version      = dlg.get_version()",
    "            rec.description  = dlg.get_description()",
    "            rec.category     = dlg.get_category()",
    "            rec.formula      = dlg.get_formula()",
    "            rec.author       = dlg.get_author()",
    "            rec.status       = dlg.get_status()",
    "            rec.tags         = dlg.get_tags()",
    "            rec.dependencies = dlg.get_dependencies()",
    "            rec.dataset_ids  = dlg.get_dataset_ids()",
    "            self._engine.update_feature(rec)",
    "",
    "    def _on_delete(self):",
    "        rec = self._get_selected_record()",
    "        if rec:",
    "            self._engine.delete_feature(rec.feature_id)",
    "",
    "    def _on_ic(self):",
    "        rec = self._get_selected_record()",
    "        if not rec:",
    "            return",
    "        dlg = FeatureICDialog(rec.name, parent=self)",
    "        if dlg.exec() == FeatureICDialog.Accepted:",
    "            self._engine.update_ic_metrics(",
    "                rec.feature_id,",
    "                ic=dlg.get_ic(), rank_ic=dlg.get_rank_ic(),",
    "                ir=dlg.get_ir(), icir=dlg.get_icir(),",
    "                coverage=dlg.get_coverage(),",
    "                period=dlg.get_period(), dataset_id=dlg.get_dataset_id(),",
    "            )",
    "",
    "    def _on_deprecate(self):",
    "        rec = self._get_selected_record()",
    "        if not rec or rec.deprecated_at is not None:",
    "            return",
    "        dlg = FeatureDeprecateDialog(rec.name, parent=self)",
    "        if dlg.exec() == FeatureDeprecateDialog.Accepted:",
    "            self._engine.deprecate_feature(rec.feature_id, dlg.get_reason())",
    "",
    "    def _on_restore(self):",
    "        rec = self._get_selected_record()",
    "        if rec and rec.deprecated_at is not None:",
    "            self._engine.restore_feature(rec.feature_id)",
    "",
    "    def _get_record_at(self, row: int) -> Optional[FeatureRecord]:",
    "        item = self._table.item(row, COL_ID)",
    "        if item is None:",
    "            return None",
    "        return self._engine.get_feature(item.data(Qt.UserRole))",
    "",
    "    def _get_selected_record(self) -> Optional[FeatureRecord]:",
    "        return self._get_record_at(self._table.currentRow())",
]

with open(P, "a", encoding="utf-8") as f:
    f.write("\n".join(LINES) + "\n")

print("FeatureTab appended OK, size:", P.stat().st_size)
