"""Append StrategyTab part2"""
import pathlib

P = pathlib.Path(
    r"c:\Users\11229\Documents\GitHub\vnpy\vnpy\quant_research\ui\strategy_tab.py"
)

LINES = [
    "",
    "    def _populate_table(self, records):",
    "        self._table.setSortingEnabled(False)",
    "        self._table.setRowCount(0)",
    "        for rec in records:",
    "            r = self._table.rowCount()",
    "            self._table.insertRow(r)",
    "            self._set_row(r, rec)",
    "        self._table.setSortingEnabled(True)",
    "        self._status_bar.setText(f'共 {len(records)} 条策略')",
    "",
    "    def _set_row(self, row: int, rec: StrategyRecord):",
    "        id_item = QTableWidgetItem(rec.strategy_id)",
    "        id_item.setData(Qt.UserRole, rec.strategy_id)",
    "        self._table.setItem(row, COL_ID, id_item)",
    "        name_item = QTableWidgetItem(rec.name)",
    "        if rec.status == StrategyStatus.RETIRED:",
    "            f = QFont(); f.setStrikeOut(True); name_item.setFont(f)",
    "            name_item.setForeground(QColor('#adb5bd'))",
    "        self._table.setItem(row, COL_NAME, name_item)",
    "        self._table.setItem(row, COL_VERSION, QTableWidgetItem(rec.version))",
    "        self._table.setItem(row, COL_TYPE, QTableWidgetItem(rec.strategy_type))",
    "        st_item = QTableWidgetItem(rec.status.value)",
    "        st_item.setForeground(STATUS_COLORS.get(rec.status, QColor('#333')))",
    "        f2 = QFont(); f2.setBold(True); st_item.setFont(f2)",
    "        self._table.setItem(row, COL_STATUS, st_item)",
    "        def _pct(v, good=True):",
    "            item = QTableWidgetItem(f'{v:.2%}')",
    "            item.setTextAlignment(Qt.AlignRight | Qt.AlignVCenter)",
    "            item.setForeground(QColor('#198754' if (v > 0) == good else '#dc3545'))",
    "            return item",
    "        def _num(v):",
    "            item = QTableWidgetItem(f'{v:.4f}')",
    "            item.setTextAlignment(Qt.AlignRight | Qt.AlignVCenter)",
    "            item.setForeground(QColor('#198754' if v > 0 else '#dc3545' if v < 0 else '#333'))",
    "            return item",
    "        self._table.setItem(row, COL_RETURN, _pct(rec.annual_return, True))",
    "        self._table.setItem(row, COL_DD,     _pct(rec.max_drawdown, False))",
    "        self._table.setItem(row, COL_SHARPE, _num(rec.sharpe))",
    "        self._table.setItem(row, COL_AUTHOR, QTableWidgetItem(rec.author))",
    "        self._table.setItem(row, COL_TIME,",
    "            QTableWidgetItem(rec.updated_at.strftime('%Y-%m-%d %H:%M')))",
    "",
    "    def _on_row_changed(self, cur_row, *_):",
    "        rec = self._get_record_at(cur_row)",
    "        if rec: self._detail.load(rec)",
    "        else:   self._detail.clear()",
    "",
    "    def _on_new(self):",
    "        dlg = StrategyCreateDialog(parent=self)",
    "        if dlg.exec() == StrategyCreateDialog.Accepted:",
    "            self._engine.register_strategy(",
    "                name=dlg.get_name(), version=dlg.get_version(),",
    "                description=dlg.get_description(),",
    "                strategy_type=dlg.get_strategy_type(),",
    "                author=dlg.get_author(), universe=dlg.get_universe(),",
    "                code_path=dlg.get_code_path(), params=dlg.get_params(),",
    "                tags=dlg.get_tags(), feature_ids=dlg.get_feature_ids(),",
    "                dataset_ids=dlg.get_dataset_ids(),",
    "            )",
    "",
    "    def _on_edit(self):",
    "        rec = self._get_selected_record()",
    "        if not rec: return",
    "        dlg = StrategyCreateDialog(parent=self, record=rec)",
    "        if dlg.exec() == StrategyCreateDialog.Accepted:",
    "            rec.name          = dlg.get_name()",
    "            rec.version       = dlg.get_version()",
    "            rec.description   = dlg.get_description()",
    "            rec.strategy_type = dlg.get_strategy_type()",
    "            rec.author        = dlg.get_author()",
    "            rec.status        = dlg.get_status()",
    "            rec.universe      = dlg.get_universe()",
    "            rec.code_path     = dlg.get_code_path()",
    "            rec.params        = dlg.get_params()",
    "            rec.tags          = dlg.get_tags()",
    "            rec.feature_ids   = dlg.get_feature_ids()",
    "            rec.dataset_ids   = dlg.get_dataset_ids()",
    "            self._engine.update_strategy(rec)",
    "",
    "    def _on_delete(self):",
    "        rec = self._get_selected_record()",
    "        if rec: self._engine.delete_strategy(rec.strategy_id)",
    "",
    "    def _on_perf(self):",
    "        rec = self._get_selected_record()",
    "        if not rec: return",
    "        dlg = StrategyPerformanceDialog(rec.name, parent=self)",
    "        if dlg.exec() == StrategyPerformanceDialog.Accepted:",
    "            self._engine.update_performance(",
    "                rec.strategy_id,",
    "                annual_return=dlg.get_annual_return(),",
    "                max_drawdown=dlg.get_max_drawdown(),",
    "                sharpe=dlg.get_sharpe(), sortino=dlg.get_sortino(),",
    "                calmar=dlg.get_calmar(), win_rate=dlg.get_win_rate(),",
    "                turnover=dlg.get_turnover(),",
    "                profit_factor=dlg.get_profit_factor(),",
    "            )",
    "",
    "    def _on_version(self):",
    "        rec = self._get_selected_record()",
    "        if not rec: return",
    "        dlg = StrategyVersionDialog(rec.name, parent=self)",
    "        if dlg.exec() == StrategyVersionDialog.Accepted:",
    "            self._engine.add_strategy_version(",
    "                rec.strategy_id,",
    "                note=dlg.get_note(), created_by=dlg.get_author(),",
    "            )",
    "",
    "    def _on_publish(self):",
    "        rec = self._get_selected_record()",
    "        if rec: self._engine.publish_strategy(rec.strategy_id)",
    "",
    "    def _on_testing(self):",
    "        rec = self._get_selected_record()",
    "        if rec: self._engine.set_strategy_testing(rec.strategy_id)",
    "",
    "    def _on_retire(self):",
    "        rec = self._get_selected_record()",
    "        if rec: self._engine.retire_strategy(rec.strategy_id)",
    "",
    "    def _get_record_at(self, row):",
    "        item = self._table.item(row, COL_ID)",
    "        if item is None: return None",
    "        return self._engine.get_strategy(item.data(Qt.UserRole))",
    "",
    "    def _get_selected_record(self):",
    "        return self._get_record_at(self._table.currentRow())",
]

# replace placeholder
txt = P.read_text(encoding="utf-8")
txt = txt.replace("# PLACEHOLDER_PART2", "\n".join(LINES))
P.write_text(txt, encoding="utf-8")
print("Part2 merged OK, size:", P.stat().st_size)
