"""Append DatasetTab main class to dataset_tab.py"""
import pathlib

P = pathlib.Path(
    r"c:\Users\11229\Documents\GitHub\vnpy\vnpy\quant_research\ui\dataset_tab.py"
)

LINES = [
    "",
    "",
    "class DatasetTab(QWidget):",
    '    """数据集注册中心主 Tab。"""',
    "",
    "    def __init__(self, engine: ResearchEngine, parent=None):",
    "        super().__init__(parent)",
    "        self._engine = engine",
    "        self._all_records: List[DatasetRecord] = []",
    "        self._init_ui()",
    "        self._register_events()",
    "        self._refresh()",
    "",
    "    def _init_ui(self):",
    "        root = QVBoxLayout(self)",
    "        root.setContentsMargins(6, 6, 6, 6)",
    "",
    "        bar1 = QHBoxLayout()",
    "        self._btn_new      = QPushButton('+ 注册数据集')",
    "        self._btn_edit     = QPushButton('编辑')",
    "        self._btn_delete   = QPushButton('删除')",
    "        self._btn_snapshot = QPushButton('拍摄快照')",
    "        for btn in (self._btn_new, self._btn_edit,",
    "                    self._btn_delete, self._btn_snapshot):",
    "            bar1.addWidget(btn)",
    "        bar1.addStretch()",
    "        root.addLayout(bar1)",
    "",
    "        bar2 = QHBoxLayout()",
    "        bar2.addWidget(QLabel('状态:'))",
    "        self._status_filter = QComboBox()",
    "        self._status_filter.addItem('全部', None)",
    "        for s in DatasetStatus:",
    "            self._status_filter.addItem(s.value, s)",
    "        self._status_filter.setFixedWidth(120)",
    "        bar2.addWidget(self._status_filter)",
    "        bar2.addWidget(QLabel('来源:'))",
    "        self._source_filter = QLineEdit()",
    "        self._source_filter.setPlaceholderText('来源关键词')",
    "        self._source_filter.setFixedWidth(140)",
    "        bar2.addWidget(self._source_filter)",
    "        bar2.addWidget(QLabel('搜索:'))",
    "        self._search_box = QLineEdit()",
    "        self._search_box.setPlaceholderText('名称 / 标签 / 标的')",
    "        self._search_box.setFixedWidth(180)",
    "        bar2.addWidget(self._search_box)",
    "        self._btn_search = QPushButton('搜索')",
    "        self._btn_search.setFixedWidth(52)",
    "        bar2.addWidget(self._btn_search)",
    "        self._btn_reset = QPushButton('重置')",
    "        self._btn_reset.setFixedWidth(52)",
    "        bar2.addWidget(self._btn_reset)",
    "        bar2.addStretch()",
    "        root.addLayout(bar2)",
    "",
    "        splitter = QSplitter(Qt.Vertical)",
    "",
    "        self._table = QTableWidget(0, len(HEADERS))",
    "        self._table.setHorizontalHeaderLabels(HEADERS)",
    "        self._table.horizontalHeader().setSectionResizeMode(COL_NAME, QHeaderView.Stretch)",
    "        self._table.horizontalHeader().setSectionResizeMode(COL_ID, QHeaderView.ResizeToContents)",
    "        self._table.setSelectionBehavior(QAbstractItemView.SelectRows)",
    "        self._table.setEditTriggers(QAbstractItemView.NoEditTriggers)",
    "        self._table.setAlternatingRowColors(True)",
    "        self._table.setSortingEnabled(True)",
    "        self._table.verticalHeader().setVisible(False)",
    "        splitter.addWidget(self._table)",
    "",
    "        self._detail = DatasetDetailPanel(self._engine)",
    "        self._detail.setMinimumHeight(200)",
    "        splitter.addWidget(self._detail)",
    "        splitter.setSizes([380, 240])",
    "        root.addWidget(splitter)",
    "",
    "        self._status_bar = QLabel('共 0 条数据集')",
    "        root.addWidget(self._status_bar)",
    "",
    "        self._btn_new.clicked.connect(self._on_new)",
    "        self._btn_edit.clicked.connect(self._on_edit)",
    "        self._btn_delete.clicked.connect(self._on_delete)",
    "        self._btn_snapshot.clicked.connect(self._on_snapshot)",
    "        self._btn_search.clicked.connect(self._apply_filter)",
    "        self._btn_reset.clicked.connect(self._reset_filter)",
    "        self._search_box.returnPressed.connect(self._apply_filter)",
    "        self._status_filter.currentIndexChanged.connect(self._apply_filter)",
    "        self._source_filter.returnPressed.connect(self._apply_filter)",
    "        self._table.currentCellChanged.connect(self._on_row_changed)",
    "        self._table.doubleClicked.connect(self._on_edit)",
    "",
    "    def _register_events(self):",
    "        ee = self._engine.event_engine",
    "        ee.register(EVENT_DATASET_CREATED, self._on_event)",
    "        ee.register(EVENT_DATASET_UPDATED, self._on_event)",
    "        ee.register(EVENT_DATASET_DELETED, self._on_event)",
    "",
    "    def _on_event(self, event: Event):",
    "        self._refresh()",
    "",
    "    def _refresh(self):",
    "        self._all_records = self._engine.list_datasets()",
    "        self._apply_filter()",
    "",
    "    def _apply_filter(self):",
    "        status  = self._status_filter.currentData()",
    "        source  = self._source_filter.text().strip() or None",
    "        keyword = self._search_box.text().strip()",
    "        if keyword:",
    "            records = self._engine.search_datasets(keyword)",
    "        else:",
    "            records = self._engine.list_datasets(status=status, source=source)",
    "        self._populate_table(records)",
    "",
    "    def _reset_filter(self):",
    "        self._status_filter.setCurrentIndex(0)",
    "        self._source_filter.clear()",
    "        self._search_box.clear()",
    "        self._populate_table(self._all_records)",
    "",
    "    def _populate_table(self, records: List[DatasetRecord]):",
    "        self._table.setSortingEnabled(False)",
    "        self._table.setRowCount(0)",
    "        for rec in records:",
    "            r = self._table.rowCount()",
    "            self._table.insertRow(r)",
    "            self._set_row(r, rec)",
    "        self._table.setSortingEnabled(True)",
    "        self._status_bar.setText(f'共 {len(records)} 条数据集')",
    "",
    "    def _set_row(self, row: int, rec: DatasetRecord):",
    "        id_item = QTableWidgetItem(rec.dataset_id)",
    "        id_item.setData(Qt.UserRole, rec.dataset_id)",
    "        self._table.setItem(row, COL_ID, id_item)",
    "        self._table.setItem(row, COL_NAME, QTableWidgetItem(rec.name))",
    "        self._table.setItem(row, COL_VERSION, QTableWidgetItem(rec.version))",
    "        status_item = QTableWidgetItem(rec.status.value)",
    "        status_item.setForeground(STATUS_COLORS.get(rec.status, QColor('#333')))",
    "        f = QFont(); f.setBold(True); status_item.setFont(f)",
    "        self._table.setItem(row, COL_STATUS, status_item)",
    "        self._table.setItem(row, COL_SOURCE, QTableWidgetItem(rec.source))",
    "        rows_item = QTableWidgetItem(f'{rec.row_count:,}')",
    "        rows_item.setTextAlignment(Qt.AlignRight | Qt.AlignVCenter)",
    "        self._table.setItem(row, COL_ROWS, rows_item)",
    "        score_pct = int(rec.quality_score * 100)",
    "        q_item = QTableWidgetItem(f'{score_pct}%')",
    "        q_item.setTextAlignment(Qt.AlignCenter)",
    "        q_color = (QColor('#d4edda') if score_pct >= 80",
    "                   else QColor('#fff3cd') if score_pct >= 50",
    "                   else QColor('#f8d7da') if score_pct > 0",
    "                   else QColor('#f8f9fa'))",
    "        q_item.setBackground(q_color)",
    "        self._table.setItem(row, COL_QUALITY, q_item)",
    "        self._table.setItem(row, COL_TIME,",
    "            QTableWidgetItem(rec.updated_at.strftime('%Y-%m-%d %H:%M')))",
    "",
    "    def _on_row_changed(self, cur_row, *_):",
    "        rec = self._get_record_at(cur_row)",
    "        if rec:",
    "            self._detail.load(rec)",
    "        else:",
    "            self._detail.clear()",
    "",
    "    def _on_new(self):",
    "        dlg = DatasetCreateDialog(parent=self)",
    "        if dlg.exec() == DatasetCreateDialog.Accepted:",
    "            self._engine.register_dataset(",
    "                name=dlg.get_name(), version=dlg.get_version(),",
    "                description=dlg.get_description(), source=dlg.get_source(),",
    "                symbols=dlg.get_symbols(), start_date=dlg.get_start_date(),",
    "                end_date=dlg.get_end_date(), fields=dlg.get_fields(),",
    "                row_count=dlg.get_row_count(), size_mb=dlg.get_size_mb(),",
    "                tags=dlg.get_tags(), created_by=dlg.get_author(),",
    "            )",
    "",
    "    def _on_edit(self):",
    "        rec = self._get_selected_record()",
    "        if not rec:",
    "            return",
    "        dlg = DatasetCreateDialog(parent=self, record=rec)",
    "        if dlg.exec() == DatasetCreateDialog.Accepted:",
    "            rec.name        = dlg.get_name()",
    "            rec.version     = dlg.get_version()",
    "            rec.description = dlg.get_description()",
    "            rec.source      = dlg.get_source()",
    "            rec.status      = dlg.get_status()",
    "            rec.symbols     = dlg.get_symbols()",
    "            rec.start_date  = dlg.get_start_date()",
    "            rec.end_date    = dlg.get_end_date()",
    "            rec.fields      = dlg.get_fields()",
    "            rec.row_count   = dlg.get_row_count()",
    "            rec.size_mb     = dlg.get_size_mb()",
    "            rec.tags        = dlg.get_tags()",
    "            rec.created_by  = dlg.get_author()",
    "            self._engine.update_dataset(rec)",
    "",
    "    def _on_delete(self):",
    "        rec = self._get_selected_record()",
    "        if rec:",
    "            self._engine.delete_dataset(rec.dataset_id)",
    "",
    "    def _on_snapshot(self):",
    "        rec = self._get_selected_record()",
    "        if rec:",
    "            self._engine.take_snapshot(rec.dataset_id)",
    "",
    "    def _get_record_at(self, row: int) -> Optional[DatasetRecord]:",
    "        item = self._table.item(row, COL_ID)",
    "        if item is None:",
    "            return None",
    "        return self._engine.get_dataset(item.data(Qt.UserRole))",
    "",
    "    def _get_selected_record(self) -> Optional[DatasetRecord]:",
    "        return self._get_record_at(self._table.currentRow())",
]

with open(P, "a", encoding="utf-8") as f:
    f.write("\n".join(LINES) + "\n")

print("DatasetTab appended OK, size:", P.stat().st_size)
