"""Append ExperimentCompareDialog to experiment_dialogs.py"""
import pathlib

P = pathlib.Path(
    r"c:\Users\11229\Documents\GitHub\vnpy\vnpy\quant_research\ui\experiment_dialogs.py"
)

LINES = [
    "",
    "",
    "class ExperimentCompareDialog(QDialog):",
    '    """多实验 metrics / params 横向对比对话框。"""',
    "",
    "    def __init__(self, records: list, parent=None):",
    "        super().__init__(parent)",
    "        self._records = records",
    "        self.setWindowTitle(f'实验对比（{len(records)} 个）')",
    "        self.resize(900, 560)",
    "        self._init_ui()",
    "",
    "    def _init_ui(self):",
    "        root = QVBoxLayout(self)",
    "",
    "        ids = '  |  '.join(r.experiment_id for r in self._records)",
    "        header = QLabel(f'对比实验：{ids}')",
    "        header.setWordWrap(True)",
    "        root.addWidget(header)",
    "",
    "        from PySide6.QtWidgets import QTabWidget",
    "        tabs = QTabWidget()",
    "",
    "        metrics_tab = QWidget()",
    "        mv = QVBoxLayout(metrics_tab)",
    "        mv.addWidget(self._build_compare_table('metrics'))",
    "        tabs.addTab(metrics_tab, 'Metrics 指标')",
    "",
    "        params_tab = QWidget()",
    "        pv = QVBoxLayout(params_tab)",
    "        pv.addWidget(self._build_compare_table('params'))",
    "        tabs.addTab(params_tab, 'Params 参数')",
    "",
    "        info_tab = QWidget()",
    "        iv = QVBoxLayout(info_tab)",
    "        iv.addWidget(self._build_info_table())",
    "        tabs.addTab(info_tab, '基本信息')",
    "",
    "        root.addWidget(tabs)",
    "",
    "        btn = QPushButton('关闭')",
    "        btn.clicked.connect(self.accept)",
    "        root.addWidget(btn)",
    "",
    "    def _build_compare_table(self, field: str) -> QTableWidget:",
    "        all_keys: list = []",
    "        for r in self._records:",
    "            d = getattr(r, field, {})",
    "            for k in d:",
    "                if k not in all_keys:",
    "                    all_keys.append(k)",
    "",
    "        n_cols = 1 + len(self._records)",
    "        table = QTableWidget(len(all_keys), n_cols)",
    "        headers = ['指标'] + [r.experiment_id for r in self._records]",
    "        table.setHorizontalHeaderLabels(headers)",
    "        table.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)",
    "        table.setEditTriggers(QAbstractItemView.NoEditTriggers)",
    "        table.setAlternatingRowColors(True)",
    "",
    "        for row, key in enumerate(all_keys):",
    "            table.setItem(row, 0, QTableWidgetItem(key))",
    "            values = []",
    "            for col, record in enumerate(self._records):",
    "                d = getattr(record, field, {})",
    "                raw = d.get(key, '—')",
    "                if isinstance(raw, float):",
    "                    text = f'{raw:.6f}'",
    "                else:",
    "                    text = str(raw)",
    "                item = QTableWidgetItem(text)",
    "                item.setTextAlignment(Qt.AlignCenter)",
    "                table.setItem(row, col + 1, item)",
    "                values.append(raw)",
    "",
    "            num_vals = [v for v in values if isinstance(v, (int, float))]",
    "            if len(num_vals) >= 2:",
    "                best  = max(num_vals)",
    "                worst = min(num_vals)",
    "                for col, record in enumerate(self._records):",
    "                    d = getattr(record, field, {})",
    "                    v = d.get(key)",
    "                    item = table.item(row, col + 1)",
    "                    if item and isinstance(v, (int, float)):",
    "                        if v == best:",
    "                            item.setBackground(QColor('#d4edda'))",
    "                        elif v == worst:",
    "                            item.setBackground(QColor('#f8d7da'))",
    "",
    "        return table",
    "",
    "    def _build_info_table(self) -> QTableWidget:",
    "        fields = [",
    "            ('ID',      'experiment_id'),",
    "            ('名称',    'name'),",
    "            ('状态',    'status'),",
    "            ('标签',    'tags'),",
    "            ('创建人',  'created_by'),",
    "            ('创建时间','created_at'),",
    "        ]",
    "        n_cols = 1 + len(self._records)",
    "        table = QTableWidget(len(fields), n_cols)",
    "        table.setHorizontalHeaderLabels(",
    "            ['字段'] + [r.experiment_id for r in self._records])",
    "        table.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)",
    "        table.setEditTriggers(QAbstractItemView.NoEditTriggers)",
    "        table.setAlternatingRowColors(True)",
    "",
    "        for row, (label, attr) in enumerate(fields):",
    "            table.setItem(row, 0, QTableWidgetItem(label))",
    "            for col, record in enumerate(self._records):",
    "                val = getattr(record, attr, '—')",
    "                if hasattr(val, 'value'):",
    "                    val = val.value",
    "                elif isinstance(val, list):",
    "                    val = ', '.join(str(x) for x in val)",
    "                elif hasattr(val, 'isoformat'):",
    "                    val = val.strftime('%Y-%m-%d %H:%M')",
    "                item = QTableWidgetItem(str(val))",
    "                item.setTextAlignment(Qt.AlignCenter)",
    "                table.setItem(row, col + 1, item)",
    "",
    "        return table",
]

with open(P, "a", encoding="utf-8") as f:
    f.write("\n".join(LINES) + "\n")

print("appended OK, size:", P.stat().st_size)
