"""Append StrategyTab part1"""
import pathlib

P = pathlib.Path(
    r"c:\Users\11229\Documents\GitHub\vnpy\vnpy\quant_research\ui\strategy_tab.py"
)

LINES = [
    "",
    "",
    "class StrategyTab(QWidget):",
    '    """策略注册中心主 Tab。"""',
    "",
    "    def __init__(self, engine: ResearchEngine, parent=None):",
    "        super().__init__(parent)",
    "        self._engine = engine",
    "        self._all_records: List[StrategyRecord] = []",
    "        self._init_ui()",
    "        self._register_events()",
    "        self._refresh()",
    "",
    "    def _init_ui(self):",
    "        root = QVBoxLayout(self)",
    "        root.setContentsMargins(6, 6, 6, 6)",
    "        bar1 = QHBoxLayout()",
    "        self._btn_new     = QPushButton('+ 注册策略')",
    "        self._btn_edit    = QPushButton('编辑')",
    "        self._btn_delete  = QPushButton('删除')",
    "        self._btn_perf    = QPushButton('录入绩效')",
    "        self._btn_version = QPushButton('新增版本快照')",
    "        self._btn_publish = QPushButton('发布上线')",
    "        self._btn_testing = QPushButton('移入测试')",
    "        self._btn_retire  = QPushButton('下线')",
    "        for btn in (self._btn_new, self._btn_edit, self._btn_delete,",
    "                    self._btn_perf, self._btn_version,",
    "                    self._btn_publish, self._btn_testing, self._btn_retire):",
    "            bar1.addWidget(btn)",
    "        bar1.addStretch()",
    "        root.addLayout(bar1)",
    "        bar2 = QHBoxLayout()",
    "        bar2.addWidget(QLabel('状态:'))",
    "        self._status_filter = QComboBox()",
    "        self._status_filter.addItem('全部', None)",
    "        for s in StrategyStatus:",
    "            self._status_filter.addItem(s.value, s)",
    "        self._status_filter.setFixedWidth(110)",
    "        bar2.addWidget(self._status_filter)",
    "        bar2.addWidget(QLabel('类型:'))",
    "        self._type_filter = QComboBox()",
    "        self._type_filter.addItem('全部', None)",
    "        for t in STRATEGY_TYPES:",
    "            self._type_filter.addItem(t, t)",
    "        self._type_filter.setFixedWidth(130)",
    "        bar2.addWidget(self._type_filter)",
    "        bar2.addWidget(QLabel('搜索:'))",
    "        self._search_box = QLineEdit()",
    "        self._search_box.setPlaceholderText('名称 / 类型 / 作者')",
    "        self._search_box.setFixedWidth(180)",
    "        bar2.addWidget(self._search_box)",
    "        self._btn_search = QPushButton('搜索')",
    "        self._btn_search.setFixedWidth(52)",
    "        bar2.addWidget(self._btn_search)",
    "        self._btn_reset = QPushButton('重置')",
    "        self._btn_reset.setFixedWidth(52)",
    "        bar2.addWidget(self._btn_reset)",
    "        bar2.addStretch()",
    "        root.addLayout(bar2)",
    "        splitter = QSplitter(Qt.Vertical)",
    "        self._table = QTableWidget(0, len(HEADERS))",
    "        self._table.setHorizontalHeaderLabels(HEADERS)",
    "        self._table.horizontalHeader().setSectionResizeMode(COL_NAME, QHeaderView.Stretch)",
    "        self._table.horizontalHeader().setSectionResizeMode(COL_ID, QHeaderView.ResizeToContents)",
    "        self._table.setSelectionBehavior(QAbstractItemView.SelectRows)",
    "        self._table.setEditTriggers(QAbstractItemView.NoEditTriggers)",
    "        self._table.setAlternatingRowColors(True)",
    "        self._table.setSortingEnabled(True)",
    "        self._table.verticalHeader().setVisible(False)",
    "        splitter.addWidget(self._table)",
    "        self._detail = StrategyDetailPanel(self._engine)",
    "        self._detail.setMinimumHeight(220)",
    "        splitter.addWidget(self._detail)",
    "        splitter.setSizes([380, 260])",
    "        root.addWidget(splitter)",
    "        self._status_bar = QLabel('共 0 条策略')",
    "        root.addWidget(self._status_bar)",
    "        self._btn_new.clicked.connect(self._on_new)",
    "        self._btn_edit.clicked.connect(self._on_edit)",
    "        self._btn_delete.clicked.connect(self._on_delete)",
    "        self._btn_perf.clicked.connect(self._on_perf)",
    "        self._btn_version.clicked.connect(self._on_version)",
    "        self._btn_publish.clicked.connect(self._on_publish)",
    "        self._btn_testing.clicked.connect(self._on_testing)",
    "        self._btn_retire.clicked.connect(self._on_retire)",
    "        self._btn_search.clicked.connect(self._apply_filter)",
    "        self._btn_reset.clicked.connect(self._reset_filter)",
    "        self._search_box.returnPressed.connect(self._apply_filter)",
    "        self._status_filter.currentIndexChanged.connect(self._apply_filter)",
    "        self._type_filter.currentIndexChanged.connect(self._apply_filter)",
    "        self._table.currentCellChanged.connect(self._on_row_changed)",
    "        self._table.doubleClicked.connect(self._on_edit)",
    "",
    "    def _register_events(self):",
    "        ee = self._engine.event_engine",
    "        ee.register(EVENT_STRATEGY_CREATED, self._on_event)",
    "        ee.register(EVENT_STRATEGY_UPDATED, self._on_event)",
    "        ee.register(EVENT_STRATEGY_DELETED, self._on_event)",
    "",
    "    def _on_event(self, event: Event):",
    "        self._refresh()",
    "",
    "    def _refresh(self):",
    "        self._all_records = self._engine.list_strategies()",
    "        self._apply_filter()",
    "",
    "    def _apply_filter(self):",
    "        status  = self._status_filter.currentData()",
    "        stype   = self._type_filter.currentData()",
    "        keyword = self._search_box.text().strip()",
    "        if keyword:",
    "            records = self._engine.search_strategies(keyword)",
    "        else:",
    "            records = self._engine.list_strategies(status=status, strategy_type=stype)",
    "        self._populate_table(records)",
    "",
    "    def _reset_filter(self):",
    "        self._status_filter.setCurrentIndex(0)",
    "        self._type_filter.setCurrentIndex(0)",
    "        self._search_box.clear()",
    "        self._populate_table(self._all_records)",
    "# PLACEHOLDER_PART2",
]

with open(P, "a", encoding="utf-8") as f:
    f.write("\n".join(LINES) + "\n")

print("Part1 appended OK, size:", P.stat().st_size)
