"""Append ReportTab main class"""
import pathlib
P = pathlib.Path(
    r"c:\Users\11229\Documents\GitHub\vnpy\vnpy\quant_research\ui\report_tab.py"
)

LINES = [
    "","",
    "class ReportTab(QWidget):",
    '    """报告中心主 Tab。"""',
    "    def __init__(self, engine: ResearchEngine, parent=None):",
    "        super().__init__(parent)",
    "        self._engine = engine",
    "        self._all_records: List[ReportRecord] = []",
    "        self._init_ui()",
    "        self._register_events()",
    "        self._refresh()",
    "    def _init_ui(self):",
    "        root = QVBoxLayout(self); root.setContentsMargins(6,6,6,6)",
    "        bar1 = QHBoxLayout()",
    "        self._btn_new     = QPushButton('+ 新建报告')",
    "        self._btn_edit    = QPushButton('编辑')",
    "        self._btn_delete  = QPushButton('删除')",
    "        self._btn_publish = QPushButton('发布')",
    "        self._btn_unpub   = QPushButton('取消发布')",
    "        self._btn_section = QPushButton('添加章节')",
    "        for btn in (self._btn_new, self._btn_edit, self._btn_delete,",
    "                    self._btn_publish, self._btn_unpub, self._btn_section):",
    "            bar1.addWidget(btn)",
    "        bar1.addStretch(); root.addLayout(bar1)",
    "        bar2 = QHBoxLayout()",
    "        bar2.addWidget(QLabel('类型:'))",
    "        self._type_filter = QComboBox()",
    "        self._type_filter.addItem('全部', None)",
    "        for t in REPORT_TYPES: self._type_filter.addItem(t, t)",
    "        self._type_filter.setFixedWidth(110); bar2.addWidget(self._type_filter)",
    "        bar2.addWidget(QLabel('搜索:'))",
    "        self._search_box = QLineEdit()",
    "        self._search_box.setPlaceholderText('标题 / 作者 / 摘要')",
    "        self._search_box.setFixedWidth(180); bar2.addWidget(self._search_box)",
    "        self._btn_search = QPushButton('搜索'); self._btn_search.setFixedWidth(52)",
    "        bar2.addWidget(self._btn_search)",
    "        self._btn_reset = QPushButton('重置'); self._btn_reset.setFixedWidth(52)",
    "        bar2.addWidget(self._btn_reset)",
    "        bar2.addStretch(); root.addLayout(bar2)",
    "        splitter = QSplitter(Qt.Vertical)",
    "        self._table = QTableWidget(0, len(HEADERS))",
    "        self._table.setHorizontalHeaderLabels(HEADERS)",
    "        self._table.horizontalHeader().setSectionResizeMode(COL_TITLE, QHeaderView.Stretch)",
    "        self._table.horizontalHeader().setSectionResizeMode(COL_ID, QHeaderView.ResizeToContents)",
    "        self._table.setSelectionBehavior(QAbstractItemView.SelectRows)",
    "        self._table.setEditTriggers(QAbstractItemView.NoEditTriggers)",
    "        self._table.setAlternatingRowColors(True)",
    "        self._table.setSortingEnabled(True)",
    "        self._table.verticalHeader().setVisible(False)",
    "        splitter.addWidget(self._table)",
    "        self._detail = ReportDetailPanel(self._engine)",
    "        self._detail.setMinimumHeight(220)",
    "        splitter.addWidget(self._detail)",
    "        splitter.setSizes([340, 260]); root.addWidget(splitter)",
    "        self._status_bar = QLabel('共 0 条报告'); root.addWidget(self._status_bar)",
    "        self._btn_new.clicked.connect(self._on_new)",
    "        self._btn_edit.clicked.connect(self._on_edit)",
    "        self._btn_delete.clicked.connect(self._on_delete)",
    "        self._btn_publish.clicked.connect(self._on_publish)",
    "        self._btn_unpub.clicked.connect(self._on_unpublish)",
    "        self._btn_section.clicked.connect(self._on_add_section)",
    "        self._btn_search.clicked.connect(self._apply_filter)",
    "        self._btn_reset.clicked.connect(self._reset_filter)",
    "        self._search_box.returnPressed.connect(self._apply_filter)",
    "        self._type_filter.currentIndexChanged.connect(self._apply_filter)",
    "        self._table.currentCellChanged.connect(self._on_row_changed)",
    "        self._table.doubleClicked.connect(self._on_edit)",
    "    def _register_events(self):",
    "        ee = self._engine.event_engine",
    "        ee.register(EVENT_REPORT_CREATED, self._on_event)",
    "        ee.register(EVENT_REPORT_UPDATED, self._on_event)",
    "    def _on_event(self, event: Event): self._refresh()",
    "    def _refresh(self):",
    "        self._all_records = self._engine.list_reports()",
    "        self._apply_filter()",
    "    def _apply_filter(self):",
    "        rtype   = self._type_filter.currentData()",
    "        keyword = self._search_box.text().strip()",
    "        records = self._engine.search_reports(keyword) if keyword else self._engine.list_reports(report_type=rtype)",
    "        self._populate_table(records)",
    "    def _reset_filter(self):",
    "        self._type_filter.setCurrentIndex(0); self._search_box.clear()",
    "        self._populate_table(self._all_records)",
    "    def _populate_table(self, records):",
    "        self._table.setSortingEnabled(False); self._table.setRowCount(0)",
    "        for rec in records:",
    "            r = self._table.rowCount(); self._table.insertRow(r); self._set_row(r, rec)",
    "        self._table.setSortingEnabled(True)",
    "        self._status_bar.setText(f'共 {len(records)} 条报告')",
    "    def _set_row(self, row: int, rec: ReportRecord):",
    "        id_item = QTableWidgetItem(rec.report_id)",
    "        id_item.setData(Qt.UserRole, rec.report_id)",
    "        self._table.setItem(row, COL_ID, id_item)",
    "        self._table.setItem(row, COL_TITLE,  QTableWidgetItem(rec.title))",
    "        self._table.setItem(row, COL_TYPE,   QTableWidgetItem(rec.report_type))",
    "        self._table.setItem(row, COL_AUTHOR, QTableWidgetItem(rec.author))",
    "        pub_item = QTableWidgetItem('✓' if rec.is_published else '—')",
    "        pub_item.setTextAlignment(Qt.AlignCenter)",
    "        pub_item.setForeground(PUB_COLOR if rec.is_published else UNPUB_COLOR)",
    "        self._table.setItem(row, COL_PUB, pub_item)",
    "        v_item = QTableWidgetItem(str(rec.view_count))",
    "        v_item.setTextAlignment(Qt.AlignCenter)",
    "        self._table.setItem(row, COL_VIEWS, v_item)",
    "        self._table.setItem(row, COL_TIME,",
    "            QTableWidgetItem(rec.updated_at.strftime('%Y-%m-%d %H:%M')))",
    "    def _on_row_changed(self, cur_row, *_):",
    "        rec = self._get_record_at(cur_row)",
    "        if rec: self._detail.load(rec)",
    "        else:   self._detail.clear()",
    "    def _on_new(self):",
    "        dlg = ReportCreateDialog(parent=self)",
    "        if dlg.exec() == ReportCreateDialog.Accepted:",
    "            self._engine.create_report(",
    "                title=dlg.get_title(), report_type=dlg.get_type(),",
    "                description=dlg.get_description(), author=dlg.get_author(),",
    "                summary=dlg.get_summary(), output_path=dlg.get_output_path(),",
    "                experiment_id=dlg.get_experiment_id(),",
    "                strategy_id=dlg.get_strategy_id(),",
    "                backtest_id=dlg.get_backtest_id(),",
    "                feature_ids=dlg.get_feature_ids(),",
    "                model_ids=dlg.get_model_ids(),",
    "                tags=dlg.get_tags(),",
    "            )",
    "    def _on_edit(self):",
    "        rec = self._get_selected_record()",
    "        if not rec: return",
    "        dlg = ReportCreateDialog(parent=self, record=rec)",
    "        if dlg.exec() == ReportCreateDialog.Accepted:",
    "            rec.title         = dlg.get_title()",
    "            rec.report_type   = dlg.get_type()",
    "            rec.description   = dlg.get_description()",
    "            rec.author        = dlg.get_author()",
    "            rec.summary       = dlg.get_summary()",
    "            rec.output_path   = dlg.get_output_path()",
    "            rec.experiment_id = dlg.get_experiment_id()",
    "            rec.strategy_id   = dlg.get_strategy_id()",
    "            rec.backtest_id   = dlg.get_backtest_id()",
    "            rec.feature_ids   = dlg.get_feature_ids()",
    "            rec.model_ids     = dlg.get_model_ids()",
    "            rec.tags          = dlg.get_tags()",
    "            self._engine.update_report(rec)",
    "    def _on_delete(self):",
    "        rec = self._get_selected_record()",
    "        if rec: self._engine.delete_report(rec.report_id)",
    "    def _on_publish(self):",
    "        rec = self._get_selected_record()",
    "        if rec: self._engine.publish_report(rec.report_id)",
    "    def _on_unpublish(self):",
    "        rec = self._get_selected_record()",
    "        if rec: self._engine.unpublish_report(rec.report_id)",
    "    def _on_add_section(self):",
    "        rec = self._get_selected_record()",
    "        if not rec: return",
    "        from PySide6.QtWidgets import QInputDialog",
    "        title, ok = QInputDialog.getText(self, '添加章节', '章节标题：')",
    "        if ok and title.strip():",
    "            self._engine.add_report_section(rec.report_id, title.strip())",
    "    def _get_record_at(self, row):",
    "        item = self._table.item(row, COL_ID)",
    "        if item is None: return None",
    "        return self._engine.get_report(item.data(Qt.UserRole))",
    "    def _get_selected_record(self):",
    "        return self._get_record_at(self._table.currentRow())",
]

with open(P, "a", encoding="utf-8") as f:
    f.write("\n".join(LINES) + "\n")
print("ReportTab appended OK, size:", P.stat().st_size)
