"""Append ArtifactTab main class"""
import pathlib
P = pathlib.Path(
    r"c:\Users\11229\Documents\GitHub\vnpy\vnpy\quant_research\ui\artifact_tab.py"
)

LINES = [
    "","",
    "class ArtifactTab(QWidget):",
    '    """成果中心主 Tab。"""',
    "    def __init__(self, engine: ResearchEngine, parent=None):",
    "        super().__init__(parent)",
    "        self._engine = engine",
    "        self._all_records: List[ArtifactRecord] = []",
    "        self._init_ui()",
    "        self._register_events()",
    "        self._refresh()",
    "    def _init_ui(self):",
    "        root = QVBoxLayout(self); root.setContentsMargins(6,6,6,6)",
    "        bar1 = QHBoxLayout()",
    "        self._btn_new      = QPushButton('+ 注册成果')",
    "        self._btn_edit     = QPushButton('编辑')",
    "        self._btn_delete   = QPushButton('删除')",
    "        self._btn_archive  = QPushButton('归档')",
    "        self._btn_unarch   = QPushButton('取消归档')",
    "        self._btn_download = QPushButton('记录下载')",
    "        for btn in (self._btn_new, self._btn_edit, self._btn_delete,",
    "                    self._btn_archive, self._btn_unarch, self._btn_download):",
    "            bar1.addWidget(btn)",
    "        bar1.addStretch()",
    "        self._size_lbl = QLabel('总大小：0 KB')",
    "        self._size_lbl.setStyleSheet('color:#6c757d; padding:2px 8px;')",
    "        bar1.addWidget(self._size_lbl)",
    "        root.addLayout(bar1)",
    "        bar2 = QHBoxLayout()",
    "        bar2.addWidget(QLabel('类型:'))",
    "        self._type_filter = QComboBox()",
    "        self._type_filter.addItem('全部', None)",
    "        for at in ArtifactType:",
    "            self._type_filter.addItem(ARTIFACT_TYPE_LABELS.get(at, at.value), at)",
    "        self._type_filter.setFixedWidth(100); bar2.addWidget(self._type_filter)",
    "        bar2.addWidget(QLabel('归档:'))",
    "        self._arch_filter = QComboBox()",
    "        self._arch_filter.addItem('全部', None)",
    "        self._arch_filter.addItem('活跃', False)",
    "        self._arch_filter.addItem('已归档', True)",
    "        self._arch_filter.setFixedWidth(80); bar2.addWidget(self._arch_filter)",
    "        bar2.addWidget(QLabel('搜索:'))",
    "        self._search_box = QLineEdit()",
    "        self._search_box.setPlaceholderText('名称 / 作者 / 路径')",
    "        self._search_box.setFixedWidth(180); bar2.addWidget(self._search_box)",
    "        self._btn_search = QPushButton('搜索'); self._btn_search.setFixedWidth(52)",
    "        bar2.addWidget(self._btn_search)",
    "        self._btn_reset = QPushButton('重置'); self._btn_reset.setFixedWidth(52)",
    "        bar2.addWidget(self._btn_reset)",
    "        bar2.addStretch(); root.addLayout(bar2)",
    "        splitter = QSplitter(Qt.Vertical)",
    "        self._table = QTableWidget(0, len(HEADERS))",
    "        self._table.setHorizontalHeaderLabels(HEADERS)",
    "        self._table.horizontalHeader().setSectionResizeMode(COL_NAME, QHeaderView.Stretch)",
    "        self._table.horizontalHeader().setSectionResizeMode(COL_ID, QHeaderView.ResizeToContents)",
    "        self._table.setSelectionBehavior(QAbstractItemView.SelectRows)",
    "        self._table.setEditTriggers(QAbstractItemView.NoEditTriggers)",
    "        self._table.setAlternatingRowColors(True)",
    "        self._table.setSortingEnabled(True)",
    "        self._table.verticalHeader().setVisible(False)",
    "        splitter.addWidget(self._table)",
    "        self._detail = ArtifactDetailPanel(self._engine)",
    "        self._detail.setMinimumHeight(200)",
    "        splitter.addWidget(self._detail)",
    "        splitter.setSizes([340, 220]); root.addWidget(splitter)",
    "        self._status_bar = QLabel('共 0 个成果'); root.addWidget(self._status_bar)",
    "        self._btn_new.clicked.connect(self._on_new)",
    "        self._btn_edit.clicked.connect(self._on_edit)",
    "        self._btn_delete.clicked.connect(self._on_delete)",
    "        self._btn_archive.clicked.connect(self._on_archive)",
    "        self._btn_unarch.clicked.connect(self._on_unarchive)",
    "        self._btn_download.clicked.connect(self._on_download)",
    "        self._btn_search.clicked.connect(self._apply_filter)",
    "        self._btn_reset.clicked.connect(self._reset_filter)",
    "        self._search_box.returnPressed.connect(self._apply_filter)",
    "        self._type_filter.currentIndexChanged.connect(self._apply_filter)",
    "        self._arch_filter.currentIndexChanged.connect(self._apply_filter)",
    "        self._table.currentCellChanged.connect(self._on_row_changed)",
    "        self._table.doubleClicked.connect(self._on_edit)",
    "    def _register_events(self):",
    "        ee = self._engine.event_engine",
    "        ee.register(EVENT_ARTIFACT_CREATED, self._on_event)",
    "        ee.register(EVENT_ARTIFACT_DELETED, self._on_event)",
    "    def _on_event(self, event: Event): self._refresh()",
    "    def _refresh(self):",
    "        self._all_records = self._engine.list_artifacts()",
    "        total_kb = self._engine.artifact_total_size_kb()",
    "        self._size_lbl.setText(f'总大小：{total_kb:.1f} KB')",
    "        self._apply_filter()",
    "    def _apply_filter(self):",
    "        atype    = self._type_filter.currentData()",
    "        archived = self._arch_filter.currentData()",
    "        keyword  = self._search_box.text().strip()",
    "        if keyword:",
    "            records = self._engine.search_artifacts(keyword)",
    "        else:",
    "            records = self._engine.list_artifacts(artifact_type=atype, archived=archived)",
    "        self._populate_table(records)",
    "    def _reset_filter(self):",
    "        self._type_filter.setCurrentIndex(0)",
    "        self._arch_filter.setCurrentIndex(0)",
    "        self._search_box.clear()",
    "        self._populate_table(self._all_records)",
    "    def _populate_table(self, records):",
    "        self._table.setSortingEnabled(False); self._table.setRowCount(0)",
    "        for rec in records:",
    "            r = self._table.rowCount(); self._table.insertRow(r); self._set_row(r, rec)",
    "        self._table.setSortingEnabled(True)",
    "        self._status_bar.setText(f'共 {len(records)} 个成果')",
    "    def _set_row(self, row: int, rec: ArtifactRecord):",
    "        id_item = QTableWidgetItem(rec.artifact_id)",
    "        id_item.setData(Qt.UserRole, rec.artifact_id)",
    "        self._table.setItem(row, COL_ID, id_item)",
    "        self._table.setItem(row, COL_NAME, QTableWidgetItem(rec.name))",
    "        type_lbl = ARTIFACT_TYPE_LABELS.get(rec.artifact_type, rec.artifact_type.value)",
    "        t_item = QTableWidgetItem(type_lbl)",
    "        t_item.setForeground(TYPE_COLORS.get(rec.artifact_type, QColor('#333')))",
    "        f = QFont(); f.setBold(True); t_item.setFont(f)",
    "        self._table.setItem(row, COL_TYPE, t_item)",
    "        self._table.setItem(row, COL_VERSION, QTableWidgetItem(rec.version))",
    "        self._table.setItem(row, COL_AUTHOR, QTableWidgetItem(rec.author))",
    "        sz_item = QTableWidgetItem(f'{rec.file_size_kb:.1f}')",
    "        sz_item.setTextAlignment(Qt.AlignRight | Qt.AlignVCenter)",
    "        self._table.setItem(row, COL_SIZE, sz_item)",
    "        dl_item = QTableWidgetItem(str(rec.download_count))",
    "        dl_item.setTextAlignment(Qt.AlignCenter)",
    "        self._table.setItem(row, COL_DL, dl_item)",
    "        arch_item = QTableWidgetItem('✓' if rec.is_archived else '—')",
    "        arch_item.setTextAlignment(Qt.AlignCenter)",
    "        arch_item.setForeground(QColor('#6c757d') if rec.is_archived else QColor('#198754'))",
    "        self._table.setItem(row, COL_ARCH, arch_item)",
    "        self._table.setItem(row, COL_TIME, QTableWidgetItem(rec.created_at.strftime('%Y-%m-%d %H:%M')))",
    "    def _on_row_changed(self, cur_row, *_):",
    "        rec = self._get_record_at(cur_row)",
    "        if rec: self._detail.load(rec)",
    "        else:   self._detail.clear()",
    "    def _on_new(self):",
    "        dlg = ArtifactCreateDialog(parent=self)",
    "        if dlg.exec() == ArtifactCreateDialog.Accepted:",
    "            self._engine.register_artifact(",
    "                name=dlg.get_name(), artifact_type=dlg.get_type(),",
    "                description=dlg.get_description(), author=dlg.get_author(),",
    "                file_path=dlg.get_path(), file_size_kb=dlg.get_size(),",
    "                checksum=dlg.get_checksum(), version=dlg.get_version(),",
    "                experiment_id=dlg.get_experiment_id(),",
    "                pipeline_id=dlg.get_pipeline_id(),",
    "                strategy_id=dlg.get_strategy_id(),",
    "                model_id=dlg.get_model_id(),",
    "                backtest_id=dlg.get_backtest_id(),",
    "                report_id=dlg.get_report_id(),",
    "                tags=dlg.get_tags(),",
    "            )",
    "    def _on_edit(self):",
    "        rec = self._get_selected_record()",
    "        if not rec: return",
    "        dlg = ArtifactCreateDialog(parent=self, record=rec)",
    "        if dlg.exec() == ArtifactCreateDialog.Accepted:",
    "            rec.name          = dlg.get_name()",
    "            rec.artifact_type = dlg.get_type()",
    "            rec.description   = dlg.get_description()",
    "            rec.author        = dlg.get_author()",
    "            rec.file_path     = dlg.get_path()",
    "            rec.file_size_kb  = dlg.get_size()",
    "            rec.checksum      = dlg.get_checksum()",
    "            rec.version       = dlg.get_version()",
    "            rec.experiment_id = dlg.get_experiment_id()",
    "            rec.pipeline_id   = dlg.get_pipeline_id()",
    "            rec.strategy_id   = dlg.get_strategy_id()",
    "            rec.model_id      = dlg.get_model_id()",
    "            rec.backtest_id   = dlg.get_backtest_id()",
    "            rec.report_id     = dlg.get_report_id()",
    "            rec.tags          = dlg.get_tags()",
    "            self._engine.update_artifact(rec)",
    "            self._refresh()",
    "    def _on_delete(self):",
    "        rec = self._get_selected_record()",
    "        if rec: self._engine.delete_artifact(rec.artifact_id)",
    "    def _on_archive(self):",
    "        rec = self._get_selected_record()",
    "        if rec: self._engine.archive_artifact(rec.artifact_id); self._refresh()",
    "    def _on_unarchive(self):",
    "        rec = self._get_selected_record()",
    "        if rec: self._engine.unarchive_artifact(rec.artifact_id); self._refresh()",
    "    def _on_download(self):",
    "        rec = self._get_selected_record()",
    "        if rec: self._engine.download_artifact(rec.artifact_id); self._refresh()",
    "    def _get_record_at(self, row):",
    "        item = self._table.item(row, COL_ID)",
    "        if item is None: return None",
    "        return self._engine.get_artifact(item.data(Qt.UserRole))",
    "    def _get_selected_record(self):",
    "        return self._get_record_at(self._table.currentRow())",
]

with open(P, "a", encoding="utf-8") as f:
    f.write("\n".join(LINES) + "\n")
print("ArtifactTab appended OK, size:", P.stat().st_size)
