"""Append ModelEvalDialog + ModelTrainingRunDialog + ModelDeployDialog"""
import pathlib

P = pathlib.Path(
    r"c:\Users\11229\Documents\GitHub\vnpy\vnpy\quant_research\ui\model_dialogs.py"
)

LINES = [
    "",
    "",
    "class ModelEvalDialog(QDialog):",
    '    """录入评估指标对话框。"""',
    "",
    "    def __init__(self, model_name: str, parent=None):",
    "        super().__init__(parent)",
    "        self.setWindowTitle(f'录入评估指标 — {model_name}')",
    "        self.setMinimumWidth(420)",
    "        self._init_ui()",
    "",
    "    def _init_ui(self):",
    "        root = QVBoxLayout(self)",
    "        form = QFormLayout()",
    "        def _spin(lo=0.0, hi=1.0, dec=6):",
    "            s = QDoubleSpinBox()",
    "            s.setRange(lo, hi); s.setDecimals(dec); s.setSingleStep(0.001)",
    "            return s",
    "        self._acc_spin  = _spin()",
    "        self._auc_spin  = _spin()",
    "        self._f1_spin   = _spin()",
    "        self._rmse_spin = _spin(0.0, 1e9, 6); self._rmse_spin.setSingleStep(0.01)",
    "        self._mae_spin  = _spin(0.0, 1e9, 6); self._mae_spin.setSingleStep(0.01)",
    "        form.addRow('Accuracy', self._acc_spin)",
    "        form.addRow('AUC',      self._auc_spin)",
    "        form.addRow('F1',       self._f1_spin)",
    "        form.addRow('RMSE',     self._rmse_spin)",
    "        form.addRow('MAE',      self._mae_spin)",
    "        root.addLayout(form)",
    "        root.addWidget(QLabel('自定义指标（JSON格式，如 {\"ic\": 0.05}）：'))",
    "        self._custom_edit = QPlainTextEdit()",
    "        self._custom_edit.setPlaceholderText('{}')",
    "        self._custom_edit.setFixedHeight(60)",
    "        root.addWidget(self._custom_edit)",
    "        buttons = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel)",
    "        buttons.button(QDialogButtonBox.Ok).setText('确认')",
    "        buttons.button(QDialogButtonBox.Cancel).setText('取消')",
    "        buttons.accepted.connect(self.accept)",
    "        buttons.rejected.connect(self.reject)",
    "        root.addWidget(buttons)",
    "",
    "    def get_accuracy(self) -> float: return self._acc_spin.value()",
    "    def get_auc(self)      -> float: return self._auc_spin.value()",
    "    def get_f1(self)       -> float: return self._f1_spin.value()",
    "    def get_rmse(self)     -> float: return self._rmse_spin.value()",
    "    def get_mae(self)      -> float: return self._mae_spin.value()",
    "",
    "    def get_custom_metrics(self):",
    "        try:",
    "            return json.loads(self._custom_edit.toPlainText() or '{}')",
    "        except Exception:",
    "            return {}",
    "",
    "",
    "class ModelTrainingRunDialog(QDialog):",
    '    """录入训练历史对话框。"""',
    "",
    "    def __init__(self, model_name: str, parent=None):",
    "        super().__init__(parent)",
    "        self.setWindowTitle(f'录入训练记录 — {model_name}')",
    "        self.setMinimumWidth(440)",
    "        self._init_ui()",
    "",
    "    def _init_ui(self):",
    "        root = QVBoxLayout(self)",
    "        form = QFormLayout()",
    "        self._note_edit    = QLineEdit()",
    "        self._note_edit.setPlaceholderText('训练说明')",
    "        self._dataset_edit = QLineEdit()",
    "        self._dataset_edit.setPlaceholderText('数据集 ID（可选）')",
    "        self._author_edit  = QLineEdit()",
    "        self._author_edit.setPlaceholderText('操作人（可选）')",
    "        self._dur_spin     = QDoubleSpinBox()",
    "        self._dur_spin.setRange(0, 86400); self._dur_spin.setDecimals(1)",
    "        self._dur_spin.setSuffix('  秒')",
    "        form.addRow('训练说明',  self._note_edit)",
    "        form.addRow('数据集 ID', self._dataset_edit)",
    "        form.addRow('操作人',    self._author_edit)",
    "        form.addRow('耗时',      self._dur_spin)",
    "        root.addLayout(form)",
    "        root.addWidget(QLabel('超参数（JSON格式）：'))",
    "        self._hp_edit = QPlainTextEdit()",
    "        self._hp_edit.setPlaceholderText('{\"n_estimators\": 500}')",
    "        self._hp_edit.setFixedHeight(56)",
    "        root.addWidget(self._hp_edit)",
    "        root.addWidget(QLabel('训练指标（JSON格式）：'))",
    "        self._metrics_edit = QPlainTextEdit()",
    "        self._metrics_edit.setPlaceholderText('{\"train_auc\": 0.92, \"val_auc\": 0.88}')",
    "        self._metrics_edit.setFixedHeight(56)",
    "        root.addWidget(self._metrics_edit)",
    "        buttons = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel)",
    "        buttons.button(QDialogButtonBox.Ok).setText('确认')",
    "        buttons.button(QDialogButtonBox.Cancel).setText('取消')",
    "        buttons.accepted.connect(self.accept)",
    "        buttons.rejected.connect(self.reject)",
    "        root.addWidget(buttons)",
    "",
    "    def get_note(self)       -> str:   return self._note_edit.text().strip()",
    "    def get_dataset_id(self) -> str:   return self._dataset_edit.text().strip()",
    "    def get_author(self)     -> str:   return self._author_edit.text().strip()",
    "    def get_duration(self)   -> float: return self._dur_spin.value()",
    "",
    "    def get_hyperparams(self):",
    "        try: return json.loads(self._hp_edit.toPlainText() or '{}')",
    "        except Exception: return {}",
    "",
    "    def get_metrics(self):",
    "        try: return json.loads(self._metrics_edit.toPlainText() or '{}')",
    "        except Exception: return {}",
    "",
    "",
    "class ModelDeployDialog(QDialog):",
    '    """部署信息对话框。"""',
    "",
    "    def __init__(self, model_name: str, parent=None):",
    "        super().__init__(parent)",
    "        self.setWindowTitle(f'部署模型 — {model_name}')",
    "        self.setMinimumWidth(380)",
    "        self._init_ui()",
    "",
    "    def _init_ui(self):",
    "        root = QVBoxLayout(self)",
    "        form = QFormLayout()",
    "        self._env_edit      = QLineEdit()",
    "        self._env_edit.setPlaceholderText('如 prod / staging / sim')",
    "        self._endpoint_edit = QLineEdit()",
    "        self._endpoint_edit.setPlaceholderText('服务地址（可选）')",
    "        form.addRow('部署环境', self._env_edit)",
    "        form.addRow('Endpoint', self._endpoint_edit)",
    "        root.addLayout(form)",
    "        buttons = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel)",
    "        buttons.button(QDialogButtonBox.Ok).setText('确认部署')",
    "        buttons.button(QDialogButtonBox.Cancel).setText('取消')",
    "        buttons.accepted.connect(self.accept)",
    "        buttons.rejected.connect(self.reject)",
    "        root.addWidget(buttons)",
    "",
    "    def get_env(self)      -> str: return self._env_edit.text().strip()",
    "    def get_endpoint(self) -> str: return self._endpoint_edit.text().strip()",
]

with open(P, "a", encoding="utf-8") as f:
    f.write("\n".join(LINES) + "\n")

print("model_dialogs appended OK, size:", P.stat().st_size)
