"""Append ModelTab main class to model_tab.py"""
import pathlib

P = pathlib.Path(
    r"c:\Users\11229\Documents\GitHub\vnpy\vnpy\quant_research\ui\model_tab.py"
)

LINES = [
    "",
    "",
    "class ModelTab(QWidget):",
    '    """模型注册中心主 Tab。"""',
    "",
    "    def __init__(self, engine: ResearchEngine, parent=None):",
    "        super().__init__(parent)",
    "        self._engine = engine",
    "        self._all_records: List[MLModelRecord] = []",
    "        self._init_ui()",
    "        self._register_events()",
    "        self._refresh()",
    "",
    "    def _init_ui(self):",
    "        root = QVBoxLayout(self)",
    "        root.setContentsMargins(6, 6, 6, 6)",
    "        bar1 = QHBoxLayout()",
    "        self._btn_new    = QPushButton('+ 注册模型')",
    "        self._btn_edit   = QPushButton('编辑')",
    "        self._btn_delete = QPushButton('删除')",
    "        self._btn_eval   = QPushButton('录入评估')",
    "        self._btn_run    = QPushButton('录入训练')",
    "        self._btn_deploy = QPushButton('部署')",
    "        self._btn_eval_s = QPushButton('标记已评估')",
    "        self._btn_retire = QPushButton('退役')",
    "        for btn in (self._btn_new, self._btn_edit, self._btn_delete,",
    "                    self._btn_eval, self._btn_run, self._btn_deploy,",
    "                    self._btn_eval_s, self._btn_retire):",
    "            bar1.addWidget(btn)",
    "        bar1.addStretch()",
    "        root.addLayout(bar1)",
    "        bar2 = QHBoxLayout()",
    "        bar2.addWidget(QLabel('状态:'))",
    "        self._status_filter = QComboBox()",
    "        self._status_filter.addItem('全部', None)",
    "        for s in ModelStatus:",
    "            self._status_filter.addItem(s.value, s)",
    "        self._status_filter.setFixedWidth(120)",
    "        bar2.addWidget(self._status_filter)",
    "        bar2.addWidget(QLabel('类型:'))",
    "        self._type_filter = QComboBox()",
    "        self._type_filter.addItem('全部', None)",
    "        for t in MODEL_TYPES:",
    "            self._type_filter.addItem(t, t)",
    "        self._type_filter.setFixedWidth(120)",
    "        bar2.addWidget(self._type_filter)",
    "        bar2.addWidget(QLabel('搜索:'))",
    "        self._search_box = QLineEdit()",
    "        self._search_box.setPlaceholderText('名称 / 类型 / 作者 / 框架')",
    "        self._search_box.setFixedWidth(180)",
    "        bar2.addWidget(self._search_box)",
    "        self._btn_search = QPushButton('搜索'); self._btn_search.setFixedWidth(52)",
    "        bar2.addWidget(self._btn_search)",
    "        self._btn_reset = QPushButton('重置'); self._btn_reset.setFixedWidth(52)",
    "        bar2.addWidget(self._btn_reset)",
    "        bar2.addStretch()",
    "        root.addLayout(bar2)",
    "        splitter = QSplitter(Qt.Vertical)",
    "        self._table = QTableWidget(0, len(HEADERS))",
    "        self._table.setHorizontalHeaderLabels(HEADERS)",
    "        self._table.horizontalHeader().setSectionResizeMode(COL_NAME, QHeaderView.Stretch)",
    "        self._table.horizontalHeader().setSectionResizeMode(COL_ID, QHeaderView.ResizeToContents)",
    "        self._table.setSelectionBehavior(QAbstractItemView.SelectRows)",
    "        self._table.setEditTriggers(QAbstractItemView.NoEditTriggers)",
    "        self._table.setAlternatingRowColors(True)",
    "        self._table.setSortingEnabled(True)",
    "        self._table.verticalHeader().setVisible(False)",
    "        splitter.addWidget(self._table)",
    "        self._detail = ModelDetailPanel(self._engine)",
    "        self._detail.setMinimumHeight(240)",
    "        splitter.addWidget(self._detail)",
    "        splitter.setSizes([360, 280])",
    "        root.addWidget(splitter)",
    "        self._status_bar = QLabel('共 0 条模型')",
    "        root.addWidget(self._status_bar)",
    "        self._btn_new.clicked.connect(self._on_new)",
    "        self._btn_edit.clicked.connect(self._on_edit)",
    "        self._btn_delete.clicked.connect(self._on_delete)",
    "        self._btn_eval.clicked.connect(self._on_eval)",
    "        self._btn_run.clicked.connect(self._on_run)",
    "        self._btn_deploy.clicked.connect(self._on_deploy)",
    "        self._btn_eval_s.clicked.connect(self._on_set_evaluated)",
    "        self._btn_retire.clicked.connect(self._on_retire)",
    "        self._btn_search.clicked.connect(self._apply_filter)",
    "        self._btn_reset.clicked.connect(self._reset_filter)",
    "        self._search_box.returnPressed.connect(self._apply_filter)",
    "        self._status_filter.currentIndexChanged.connect(self._apply_filter)",
    "        self._type_filter.currentIndexChanged.connect(self._apply_filter)",
    "        self._table.currentCellChanged.connect(self._on_row_changed)",
    "        self._table.doubleClicked.connect(self._on_edit)",
    "",
    "    def _register_events(self):",
    "        ee = self._engine.event_engine",
    "        ee.register(EVENT_MODEL_CREATED, self._on_event)",
    "        ee.register(EVENT_MODEL_UPDATED, self._on_event)",
    "        ee.register(EVENT_MODEL_DELETED, self._on_event)",
    "",
    "    def _on_event(self, event: Event):",
    "        self._refresh()",
    "",
    "    def _refresh(self):",
    "        self._all_records = self._engine.list_models()",
    "        self._apply_filter()",
    "",
    "    def _apply_filter(self):",
    "        status  = self._status_filter.currentData()",
    "        mtype   = self._type_filter.currentData()",
    "        keyword = self._search_box.text().strip()",
    "        if keyword:",
    "            records = self._engine.search_models(keyword)",
    "        else:",
    "            records = self._engine.list_models(status=status, model_type=mtype)",
    "        self._populate_table(records)",
    "",
    "    def _reset_filter(self):",
    "        self._status_filter.setCurrentIndex(0)",
    "        self._type_filter.setCurrentIndex(0)",
    "        self._search_box.clear()",
    "        self._populate_table(self._all_records)",
    "",
    "    def _populate_table(self, records):",
    "        self._table.setSortingEnabled(False)",
    "        self._table.setRowCount(0)",
    "        for rec in records:",
    "            r = self._table.rowCount()",
    "            self._table.insertRow(r)",
    "            self._set_row(r, rec)",
    "        self._table.setSortingEnabled(True)",
    "        self._status_bar.setText(f'共 {len(records)} 条模型')",
    "",
    "    def _set_row(self, row: int, rec: MLModelRecord):",
    "        id_item = QTableWidgetItem(rec.model_id)",
    "        id_item.setData(Qt.UserRole, rec.model_id)",
    "        self._table.setItem(row, COL_ID, id_item)",
    "        name_item = QTableWidgetItem(rec.name)",
    "        if rec.status == ModelStatus.RETIRED:",
    "            f = QFont(); f.setStrikeOut(True); name_item.setFont(f)",
    "            name_item.setForeground(QColor('#adb5bd'))",
    "        self._table.setItem(row, COL_NAME, name_item)",
    "        self._table.setItem(row, COL_VERSION, QTableWidgetItem(rec.version))",
    "        self._table.setItem(row, COL_TYPE,    QTableWidgetItem(rec.model_type))",
    "        st_item = QTableWidgetItem(rec.status.value)",
    "        st_item.setForeground(STATUS_COLORS.get(rec.status, QColor('#333')))",
    "        f2 = QFont(); f2.setBold(True); st_item.setFont(f2)",
    "        self._table.setItem(row, COL_STATUS, st_item)",
    "        def _num(v, fmt='.4f'):",
    "            item = QTableWidgetItem(f'{v:{fmt}}')",
    "            item.setTextAlignment(Qt.AlignRight | Qt.AlignVCenter)",
    "            item.setForeground(QColor('#198754' if v > 0 else '#333'))",
    "            return item",
    "        self._table.setItem(row, COL_ACC,    _num(rec.accuracy))",
    "        self._table.setItem(row, COL_AUC,    _num(rec.auc))",
    "        self._table.setItem(row, COL_F1,     _num(rec.f1))",
    "        self._table.setItem(row, COL_AUTHOR, QTableWidgetItem(rec.author))",
    "        self._table.setItem(row, COL_TIME,",
    "            QTableWidgetItem(rec.updated_at.strftime('%Y-%m-%d %H:%M')))",
    "",
    "    def _on_row_changed(self, cur_row, *_):",
    "        rec = self._get_record_at(cur_row)",
    "        if rec: self._detail.load(rec)",
    "        else:   self._detail.clear()",
    "",
    "    def _on_new(self):",
    "        dlg = ModelCreateDialog(parent=self)",
    "        if dlg.exec() == ModelCreateDialog.Accepted:",
    "            self._engine.register_model(",
    "                name=dlg.get_name(), version=dlg.get_version(),",
    "                description=dlg.get_description(),",
    "                model_type=dlg.get_model_type(),",
    "                author=dlg.get_author(), framework=dlg.get_framework(),",
    "                model_path=dlg.get_model_path(),",
    "                config_path=dlg.get_config_path(),",
    "                hyperparams=dlg.get_hyperparams(),",
    "                tags=dlg.get_tags(), feature_ids=dlg.get_feature_ids(),",
    "                dataset_ids=dlg.get_dataset_ids(),",
    "            )",
    "",
    "    def _on_edit(self):",
    "        rec = self._get_selected_record()",
    "        if not rec: return",
    "        dlg = ModelCreateDialog(parent=self, record=rec)",
    "        if dlg.exec() == ModelCreateDialog.Accepted:",
    "            rec.name        = dlg.get_name()",
    "            rec.version     = dlg.get_version()",
    "            rec.description = dlg.get_description()",
    "            rec.model_type  = dlg.get_model_type()",
    "            rec.author      = dlg.get_author()",
    "            rec.status      = dlg.get_status()",
    "            rec.framework   = dlg.get_framework()",
    "            rec.model_path  = dlg.get_model_path()",
    "            rec.config_path = dlg.get_config_path()",
    "            rec.hyperparams = dlg.get_hyperparams()",
    "            rec.tags        = dlg.get_tags()",
    "            rec.feature_ids = dlg.get_feature_ids()",
    "            rec.dataset_ids = dlg.get_dataset_ids()",
    "            self._engine.update_model(rec)",
    "",
    "    def _on_delete(self):",
    "        rec = self._get_selected_record()",
    "        if rec: self._engine.delete_model(rec.model_id)",
    "",
    "    def _on_eval(self):",
    "        rec = self._get_selected_record()",
    "        if not rec: return",
    "        dlg = ModelEvalDialog(rec.name, parent=self)",
    "        if dlg.exec() == ModelEvalDialog.Accepted:",
    "            self._engine.update_eval_metrics(",
    "                rec.model_id,",
    "                accuracy=dlg.get_accuracy(), auc=dlg.get_auc(),",
    "                rmse=dlg.get_rmse(), mae=dlg.get_mae(),",
    "                f1=dlg.get_f1(),",
    "                custom_metrics=dlg.get_custom_metrics(),",
    "            )",
    "",
    "    def _on_run(self):",
    "        rec = self._get_selected_record()",
    "        if not rec: return",
    "        dlg = ModelTrainingRunDialog(rec.name, parent=self)",
    "        if dlg.exec() == ModelTrainingRunDialog.Accepted:",
    "            self._engine.add_training_run(",
    "                rec.model_id,",
    "                run_note=dlg.get_note(),",
    "                hyperparams=dlg.get_hyperparams(),",
    "                metrics=dlg.get_metrics(),",
    "                dataset_id=dlg.get_dataset_id(),",
    "                duration_sec=dlg.get_duration(),",
    "                created_by=dlg.get_author(),",
    "            )",
    "",
    "    def _on_deploy(self):",
    "        rec = self._get_selected_record()",
    "        if not rec: return",
    "        dlg = ModelDeployDialog(rec.name, parent=self)",
    "        if dlg.exec() == ModelDeployDialog.Accepted:",
    "            self._engine.deploy_model(",
    "                rec.model_id,",
    "                env=dlg.get_env(), endpoint=dlg.get_endpoint(),",
    "            )",
    "",
    "    def _on_set_evaluated(self):",
    "        rec = self._get_selected_record()",
    "        if rec: self._engine.set_model_evaluated(rec.model_id)",
    "",
    "    def _on_retire(self):",
    "        rec = self._get_selected_record()",
    "        if rec: self._engine.retire_model(rec.model_id)",
    "",
    "    def _get_record_at(self, row):",
    "        item = self._table.item(row, COL_ID)",
    "        if item is None: return None",
    "        return self._engine.get_model(item.data(Qt.UserRole))",
    "",
    "    def _get_selected_record(self):",
    "        return self._get_record_at(self._table.currentRow())",
]

with open(P, "a", encoding="utf-8") as f:
    f.write("\n".join(LINES) + "\n")

print("ModelTab appended OK, size:", P.stat().st_size)
