"""Append engine tests (part A) to test_temporal_intelligence.py"""
import pathlib

P = pathlib.Path(r"c:\Users\11229\Documents\GitHub\vnpy\tests\test_temporal_intelligence.py")

PART_A = (
    "\n\nclass TestDecayEngine:\n"
    "    def _engine(self):\n"
    "        from vnpy.temporal_intelligence_ai.engine.decay_engine import DecayEngine\n"
    "        from vnpy.temporal_intelligence_ai.constant import DecayMode\n"
    "        eng = DecayEngine()\n"
    "        eng.configure(mode=DecayMode.EXPONENTIAL)\n"
    "        return eng\n"
    "\n"
    "    def _rec(self, aid, created_bar=0, hl=20):\n"
    "        from vnpy.temporal_intelligence_ai.datasource.alpha_loader import AlphaRecord\n"
    "        from vnpy.temporal_intelligence_ai.utils.decay_utils import half_life_to_rate\n"
    "        return AlphaRecord(alpha_id=aid, created_bar=created_bar,\n"
    "                           base_decay_rate=half_life_to_rate(hl))\n"
    "\n"
    "    def test_register_and_compute(self):\n"
    "        eng = self._engine()\n"
    "        eng.register_alpha(self._rec('a1'))\n"
    "        states = eng.compute(bar=10)\n"
    "        assert len(states) == 1\n"
    "        assert 0 < states[0].metrics.combined_strength <= 1.0\n"
    "\n"
    "    def test_multiple_alphas(self):\n"
    "        eng = self._engine()\n"
    "        for i in range(5):\n"
    "            eng.register_alpha(self._rec(f'a{i}'))\n"
    "        assert len(eng.compute(bar=5)) == 5\n"
    "\n"
    "    def test_older_alpha_weaker(self):\n"
    "        eng = self._engine()\n"
    "        eng.register_alpha(self._rec('young', created_bar=90))\n"
    "        eng.register_alpha(self._rec('old', created_bar=0))\n"
    "        by_id = {s.alpha_id: s for s in eng.compute(bar=100)}\n"
    "        assert by_id['young'].metrics.combined_strength > by_id['old'].metrics.combined_strength\n"
    "\n"
    "    def test_expired_flag(self):\n"
    "        from vnpy.temporal_intelligence_ai.datasource.alpha_loader import AlphaRecord\n"
    "        from vnpy.temporal_intelligence_ai.utils.decay_utils import half_life_to_rate\n"
    "        eng = self._engine()\n"
    "        eng.configure(min_threshold=0.5)\n"
    "        eng.register_alpha(AlphaRecord(alpha_id='fast', created_bar=0,\n"
    "                                       base_decay_rate=half_life_to_rate(2)))\n"
    "        assert eng.compute(bar=20)[0].is_expired\n"
    "\n"
    "    def test_curves_generated(self):\n"
    "        eng = self._engine()\n"
    "        eng.register_alpha(self._rec('c1'))\n"
    "        eng.compute(bar=5)\n"
    "        assert 'c1' in eng.get_curves()\n"
    "\n"
    "    def test_summary_keys(self):\n"
    "        eng = self._engine()\n"
    "        eng.register_alpha(self._rec('s1'))\n"
    "        eng.compute(bar=5)\n"
    "        summ = eng.get_summary()\n"
    "        assert all(k in summ for k in ('active_alphas', 'avg_strength', 'expired_count'))\n"
    "\n"
    "    def test_crisis_context_weaker(self):\n"
    "        from vnpy.temporal_intelligence_ai.constant import RegimeType, CyclePhase\n"
    "        eng = self._engine()\n"
    "        eng.register_alpha(self._rec('x'))\n"
    "        eng.set_context(regime=RegimeType.BULL_QUIET, phase=CyclePhase.EXPANSION,\n"
    "                        current_vol=0.15, current_bar=0)\n"
    "        s_bull = eng.compute(bar=20)[0].metrics.combined_strength\n"
    "        eng.set_context(regime=RegimeType.CRISIS, phase=CyclePhase.CONTRACTION,\n"
    "                        current_vol=0.60, current_bar=0)\n"
    "        s_crisis = eng.compute(bar=20)[0].metrics.combined_strength\n"
    "        assert s_crisis < s_bull\n"
    "\n"
    "\n"
    "class TestDependencyEngine:\n"
    "    def _ar1(self, n=300, phi=0.7, seed=1):\n"
    "        random.seed(seed); xs = [0.0]\n"
    "        for _ in range(n - 1):\n"
    "            xs.append(phi * xs[-1] + random.gauss(0, 1))\n"
    "        return xs\n"
    "\n"
    "    def test_analyze_single(self):\n"
    "        from vnpy.temporal_intelligence_ai.engine.dependency_engine import DependencyEngine\n"
    "        eng = DependencyEngine()\n"
    "        eng.register_signal('s1', self._ar1(300))\n"
    "        state = eng.analyze()\n"
    "        assert state is not None\n"
    "        assert 's1' in state.autocorr_results\n"
    "        assert state.overall_memory > 0\n"
    "\n"
    "    def test_two_signals(self):\n"
    "        from vnpy.temporal_intelligence_ai.engine.dependency_engine import DependencyEngine\n"
    "        eng = DependencyEngine()\n"
    "        eng.register_signal('a', self._ar1(300, phi=0.8, seed=1))\n"
    "        eng.register_signal('b', self._ar1(300, phi=0.6, seed=2))\n"
    "        assert len(eng.analyze().crosscorr_results) == 1\n"
    "\n"
    "    def test_horizon_sums(self):\n"
    "        from vnpy.temporal_intelligence_ai.engine.dependency_engine import DependencyEngine\n"
    "        eng = DependencyEngine()\n"
    "        eng.register_signal('s', self._ar1(300))\n"
    "        h = eng.analyze().horizon_decomp\n"
    "        total = h.short_term_weight + h.mid_term_weight + h.long_term_weight\n"
    "        assert total == pytest.approx(1.0, abs=0.02)\n"
    "\n"
    "    def test_high_phi_higher_memory(self):\n"
    "        from vnpy.temporal_intelligence_ai.engine.dependency_engine import DependencyEngine\n"
    "        e1, e2 = DependencyEngine(), DependencyEngine()\n"
    "        e1.register_signal('s', self._ar1(300, phi=0.9))\n"
    "        e2.register_signal('s', self._ar1(300, phi=0.1))\n"
    "        assert e1.analyze().overall_memory > e2.analyze().overall_memory\n"
    "\n"
    "    def test_history_accumulates(self):\n"
    "        from vnpy.temporal_intelligence_ai.engine.dependency_engine import DependencyEngine\n"
    "        eng = DependencyEngine()\n"
    "        eng.register_signal('s', self._ar1(300))\n"
    "        for _ in range(3):\n"
    "            eng.analyze()\n"
    "        assert len(eng.get_history().records) == 3\n"
)

with open(P, "a", encoding="utf-8") as f:
    f.write(PART_A)
print("part_A appended:", P.stat().st_size)
