"""Append BacktestTab part1"""
import pathlib
P = pathlib.Path(
    r"c:\Users\11229\Documents\GitHub\vnpy\vnpy\quant_research\ui\backtest_tab.py"
)
LINES = [
    "","",
    "class BacktestTab(QWidget):",
    '    """回测注册中心主 Tab。"""',
    "    def __init__(self, engine: ResearchEngine, parent=None):",
    "        super().__init__(parent)",
    "        self._engine = engine",
    "        self._all_records: List[BacktestRecord] = []",
    "        self._init_ui()",
    "        self._register_events()",
    "        self._refresh()",
    "    def _init_ui(self):",
    "        root = QVBoxLayout(self)",
    "        root.setContentsMargins(6, 6, 6, 6)",
    "        bar1 = QHBoxLayout()",
    "        self._btn_new      = QPushButton('+ 提交回测')",
    "        self._btn_edit     = QPushButton('编辑')",
    "        self._btn_delete   = QPushButton('删除')",
    "        self._btn_run      = QPushButton('标记运行中')",
    "        self._btn_complete = QPushButton('填入结果')",
    "        self._btn_fail     = QPushButton('标记失败')",
    "        self._btn_compare  = QPushButton('对比选中')",
    "        for btn in (self._btn_new, self._btn_edit, self._btn_delete,",
    "                    self._btn_run, self._btn_complete,",
    "                    self._btn_fail, self._btn_compare):",
    "            bar1.addWidget(btn)",
    "        bar1.addStretch()",
    "        root.addLayout(bar1)",
    "        bar2 = QHBoxLayout()",
    "        bar2.addWidget(QLabel('状态:'))",
    "        self._status_filter = QComboBox()",
    "        self._status_filter.addItem('全部', None)",
    "        for s in BacktestStatus:",
    "            self._status_filter.addItem(s.value, s)",
    "        self._status_filter.setFixedWidth(120)",
    "        bar2.addWidget(self._status_filter)",
    "        bar2.addWidget(QLabel('搜索:'))",
    "        self._search_box = QLineEdit()",
    "        self._search_box.setPlaceholderText('名称 / 策略 / 标的池')",
    "        self._search_box.setFixedWidth(200)",
    "        bar2.addWidget(self._search_box)",
    "        self._btn_search = QPushButton('搜索'); self._btn_search.setFixedWidth(52)",
    "        bar2.addWidget(self._btn_search)",
    "        self._btn_reset = QPushButton('重置'); self._btn_reset.setFixedWidth(52)",
    "        bar2.addWidget(self._btn_reset)",
    "        bar2.addStretch()",
    "        root.addLayout(bar2)",
    "        splitter = QSplitter(Qt.Vertical)",
    "        self._table = QTableWidget(0, len(HEADERS))",
    "        self._table.setHorizontalHeaderLabels(HEADERS)",
    "        self._table.horizontalHeader().setSectionResizeMode(COL_NAME, QHeaderView.Stretch)",
    "        self._table.horizontalHeader().setSectionResizeMode(COL_ID, QHeaderView.ResizeToContents)",
    "        self._table.setSelectionBehavior(QAbstractItemView.SelectRows)",
    "        self._table.setEditTriggers(QAbstractItemView.NoEditTriggers)",
    "        self._table.setAlternatingRowColors(True)",
    "        self._table.setSortingEnabled(True)",
    "        self._table.verticalHeader().setVisible(False)",
    "        self._table.setSelectionMode(QAbstractItemView.ExtendedSelection)",
    "        splitter.addWidget(self._table)",
    "        self._detail = BacktestDetailPanel(self._engine)",
    "        self._detail.setMinimumHeight(260)",
    "        splitter.addWidget(self._detail)",
    "        splitter.setSizes([360, 300])",
    "        root.addWidget(splitter)",
    "        self._status_bar = QLabel('共 0 条回测')",
    "        root.addWidget(self._status_bar)",
    "        self._btn_new.clicked.connect(self._on_new)",
    "        self._btn_edit.clicked.connect(self._on_edit)",
    "        self._btn_delete.clicked.connect(self._on_delete)",
    "        self._btn_run.clicked.connect(self._on_run)",
    "        self._btn_complete.clicked.connect(self._on_complete)",
    "        self._btn_fail.clicked.connect(self._on_fail)",
    "        self._btn_compare.clicked.connect(self._on_compare)",
    "        self._btn_search.clicked.connect(self._apply_filter)",
    "        self._btn_reset.clicked.connect(self._reset_filter)",
    "        self._search_box.returnPressed.connect(self._apply_filter)",
    "        self._status_filter.currentIndexChanged.connect(self._apply_filter)",
    "        self._table.currentCellChanged.connect(self._on_row_changed)",
    "        self._table.doubleClicked.connect(self._on_edit)",
    "    def _register_events(self):",
    "        ee = self._engine.event_engine",
    "        ee.register(EVENT_BACKTEST_CREATED, self._on_event)",
    "        ee.register(EVENT_BACKTEST_UPDATED, self._on_event)",
    "        ee.register(EVENT_BACKTEST_DELETED, self._on_event)",
    "    def _on_event(self, event: Event): self._refresh()",
    "    def _refresh(self):",
    "        self._all_records = self._engine.list_backtests()",
    "        self._apply_filter()",
    "    def _apply_filter(self):",
    "        status  = self._status_filter.currentData()",
    "        keyword = self._search_box.text().strip()",
    "        records = self._engine.search_backtests(keyword) if keyword else self._engine.list_backtests(status=status)",
    "        self._populate_table(records)",
    "    def _reset_filter(self):",
    "        self._status_filter.setCurrentIndex(0)",
    "        self._search_box.clear()",
    "        self._populate_table(self._all_records)",
    "    def _populate_table(self, records):",
    "        self._table.setSortingEnabled(False)",
    "        self._table.setRowCount(0)",
    "        for rec in records:",
    "            r = self._table.rowCount(); self._table.insertRow(r); self._set_row(r, rec)",
    "        self._table.setSortingEnabled(True)",
    "        self._status_bar.setText(f'共 {len(records)} 条回测')",
    "    def _set_row(self, row: int, rec: BacktestRecord):",
    "        id_item = QTableWidgetItem(rec.backtest_id)",
    "        id_item.setData(Qt.UserRole, rec.backtest_id)",
    "        self._table.setItem(row, COL_ID, id_item)",
    "        self._table.setItem(row, COL_NAME, QTableWidgetItem(rec.name))",
    "        st_item = QTableWidgetItem(rec.status.value)",
    "        st_item.setForeground(STATUS_COLORS.get(rec.status, QColor('#333')))",
    "        f = QFont(); f.setBold(True); st_item.setFont(f)",
    "        self._table.setItem(row, COL_STATUS, st_item)",
    "        self._table.setItem(row, COL_STRATEGY, QTableWidgetItem(rec.strategy_name or rec.strategy_id))",
    "        def _pct(v, good=True):",
    "            item = QTableWidgetItem(f'{v:.2%}')",
    "            item.setTextAlignment(Qt.AlignRight | Qt.AlignVCenter)",
    "            item.setForeground(QColor('#198754' if (v > 0) == good else '#dc3545'))",
    "            return item",
    "        def _num(v):",
    "            item = QTableWidgetItem(f'{v:.4f}')",
    "            item.setTextAlignment(Qt.AlignRight | Qt.AlignVCenter)",
    "            item.setForeground(QColor('#198754' if v > 0 else '#dc3545' if v < 0 else '#333'))",
    "            return item",
    "        self._table.setItem(row, COL_RETURN, _pct(rec.annual_return, True))",
    "        self._table.setItem(row, COL_DD,     _pct(rec.max_drawdown, False))",
    "        self._table.setItem(row, COL_SHARPE, _num(rec.sharpe))",
    "        self._table.setItem(row, COL_DATES, QTableWidgetItem(f'{rec.start_date} ~ {rec.end_date}'))",
    "        self._table.setItem(row, COL_TIME, QTableWidgetItem(rec.created_at.strftime('%Y-%m-%d %H:%M')))",
    "    def _on_row_changed(self, cur_row, *_):",
    "        rec = self._get_record_at(cur_row)",
    "        if rec: self._detail.load(rec)",
    "        else:   self._detail.clear()",
    "# PLACEHOLDER_BT_PART2",
]
with open(P, "a", encoding="utf-8") as f:
    f.write("\n".join(LINES) + "\n")
print("BT Part1 OK, size:", P.stat().st_size)
