"""Append BacktestTab part2"""
import pathlib
P = pathlib.Path(
    r"c:\Users\11229\Documents\GitHub\vnpy\vnpy\quant_research\ui\backtest_tab.py"
)

LINES = [
    "    def _on_new(self):",
    "        dlg = BacktestSubmitDialog(parent=self)",
    "        if dlg.exec() == BacktestSubmitDialog.Accepted:",
    "            self._engine.submit_backtest(",
    "                name=dlg.get_name(), strategy_id=dlg.get_strategy_id(),",
    "                strategy_name=dlg.get_strategy_name(),",
    "                description=dlg.get_description(),",
    "                start_date=dlg.get_start_date(), end_date=dlg.get_end_date(),",
    "                initial_capital=dlg.get_initial_capital(),",
    "                commission=dlg.get_commission(), slippage=dlg.get_slippage(),",
    "                universe=dlg.get_universe(), tags=dlg.get_tags(),",
    "                feature_ids=dlg.get_feature_ids(),",
    "                dataset_ids=dlg.get_dataset_ids(),",
    "                model_ids=dlg.get_model_ids(),",
    "                created_by=dlg.get_author(),",
    "            )",
    "    def _on_edit(self):",
    "        rec = self._get_selected_record()",
    "        if not rec: return",
    "        dlg = BacktestSubmitDialog(parent=self, record=rec)",
    "        if dlg.exec() == BacktestSubmitDialog.Accepted:",
    "            rec.name            = dlg.get_name()",
    "            rec.strategy_id     = dlg.get_strategy_id()",
    "            rec.strategy_name   = dlg.get_strategy_name()",
    "            rec.description     = dlg.get_description()",
    "            rec.start_date      = dlg.get_start_date()",
    "            rec.end_date        = dlg.get_end_date()",
    "            rec.initial_capital = dlg.get_initial_capital()",
    "            rec.commission      = dlg.get_commission()",
    "            rec.slippage        = dlg.get_slippage()",
    "            rec.universe        = dlg.get_universe()",
    "            rec.tags            = dlg.get_tags()",
    "            rec.feature_ids     = dlg.get_feature_ids()",
    "            rec.dataset_ids     = dlg.get_dataset_ids()",
    "            rec.model_ids       = dlg.get_model_ids()",
    "            self._engine.update_backtest(rec)",
    "    def _on_delete(self):",
    "        rec = self._get_selected_record()",
    "        if rec: self._engine.delete_backtest(rec.backtest_id)",
    "    def _on_run(self):",
    "        rec = self._get_selected_record()",
    "        if rec: self._engine.run_backtest(rec.backtest_id)",
    "    def _on_complete(self):",
    "        rec = self._get_selected_record()",
    "        if not rec: return",
    "        dlg = BacktestCompleteDialog(rec.name, parent=self)",
    "        if dlg.exec() == BacktestCompleteDialog.Accepted:",
    "            self._engine.complete_backtest(",
    "                rec.backtest_id,",
    "                annual_return=dlg.get_annual_return(),",
    "                max_drawdown=dlg.get_max_drawdown(),",
    "                sharpe=dlg.get_sharpe(), sortino=dlg.get_sortino(),",
    "                calmar=dlg.get_calmar(), win_rate=dlg.get_win_rate(),",
    "                turnover=dlg.get_turnover(),",
    "                profit_factor=dlg.get_profit_factor(),",
    "                total_return=dlg.get_total_return(),",
    "                alpha=dlg.get_alpha(), beta=dlg.get_beta(),",
    "                information_ratio=dlg.get_information_ratio(),",
    "                total_trades=dlg.get_total_trades(),",
    "                avg_holding_days=dlg.get_avg_holding_days(),",
    "                max_position_conc=dlg.get_max_position_conc(),",
    "                monthly_returns=dlg.get_monthly_returns(),",
    "            )",
    "    def _on_fail(self):",
    "        rec = self._get_selected_record()",
    "        if not rec: return",
    "        from PySide6.QtWidgets import QInputDialog",
    "        msg, ok = QInputDialog.getText(self, '标记失败', '错误信息（可留空）：')",
    "        if ok: self._engine.fail_backtest(rec.backtest_id, msg)",
    "    def _on_compare(self):",
    "        rows = {idx.row() for idx in self._table.selectedIndexes()}",
    "        ids = []",
    "        for r in rows:",
    "            item = self._table.item(r, COL_ID)",
    "            if item: ids.append(item.data(Qt.UserRole))",
    "        if len(ids) < 2: return",
    "        records = self._engine.compare_backtests(ids)",
    "        self._show_compare(records)",
    "    def _show_compare(self, records):",
    "        from PySide6.QtWidgets import QDialog, QVBoxLayout",
    "        dlg = QDialog(self)",
    "        dlg.setWindowTitle(f'对比 {len(records)} 条回测')",
    "        dlg.setMinimumSize(820, 400)",
    "        lyt = QVBoxLayout(dlg)",
    "        cols = ['名称','年化%','最大回撤%','Sharpe','Sortino','胜率%','换手率','总收益%']",
    "        tbl = QTableWidget(len(records), len(cols))",
    "        tbl.setHorizontalHeaderLabels(cols)",
    "        tbl.horizontalHeader().setSectionResizeMode(0, QHeaderView.Stretch)",
    "        tbl.setEditTriggers(QAbstractItemView.NoEditTriggers)",
    "        for i, rec in enumerate(records):",
    "            vals = [rec.name, f'{rec.annual_return:.2%}',",
    "                    f'{rec.max_drawdown:.2%}', f'{rec.sharpe:.4f}',",
    "                    f'{rec.sortino:.4f}', f'{rec.win_rate:.2%}',",
    "                    f'{rec.turnover:.2f}', f'{rec.total_return:.2%}']",
    "            for j, v in enumerate(vals):",
    "                item = QTableWidgetItem(v)",
    "                item.setTextAlignment(Qt.AlignCenter)",
    "                tbl.setItem(i, j, item)",
    "        lyt.addWidget(tbl)",
    "        dlg.exec()",
    "    def _get_record_at(self, row):",
    "        item = self._table.item(row, COL_ID)",
    "        if item is None: return None",
    "        return self._engine.get_backtest(item.data(Qt.UserRole))",
    "    def _get_selected_record(self):",
    "        return self._get_record_at(self._table.currentRow())",
]

txt = P.read_text(encoding="utf-8")
txt = txt.replace("# PLACEHOLDER_BT_PART2", "\n".join(LINES))
P.write_text(txt, encoding="utf-8")
print("BT Part2 merged OK, size:", P.stat().st_size)
