"""Script that writes test_temporal_intelligence.py as valid UTF-8."""
import pathlib

LINES = [
    "from __future__ import annotations",
    "import math, random",
    "import pytest",
    "from datetime import datetime",
    "",
    "# utils layer",
    "",
    "class TestCycleUtils:",
    "    def _prices(self, n=100, trend=0.001, vol=0.02, seed=42):",
    "        random.seed(seed); ps = [100.0]",
    "        for _ in range(n-1): ps.append(ps[-1]*(1+trend+random.gauss(0,vol)))",
    "        return ps",
    "",
    "    def test_rolling_returns(self):",
    "        from vnpy.temporal_intelligence_ai.utils.cycle_utils import rolling_returns",
    "        rets = rolling_returns(self._prices(50), window=10)",
    "        assert len(rets) == 50",
    "        assert all(r == 0.0 for r in rets[:10])",
    "        assert any(r != 0.0 for r in rets[10:])",
    "",
    "    def test_annualized_volatility(self):",
    "        from vnpy.temporal_intelligence_ai.utils.cycle_utils import annualized_volatility",
    "        vol = annualized_volatility(self._prices(100), window=20)",
    "        assert 0.0 < vol < 2.0",
    "",
    "    def test_trend_strength(self):",
    "        from vnpy.temporal_intelligence_ai.utils.cycle_utils import trend_strength",
    "        ts = trend_strength(self._prices(60), fast=5, slow=20)",
    "        assert -1.0 <= ts <= 1.0",
    "",
    "    def test_max_drawdown(self):",
    "        from vnpy.temporal_intelligence_ai.utils.cycle_utils import max_drawdown",
    "        dd = max_drawdown([100,110,90,95,80,100])",
    "        assert 0.0 < dd <= 1.0",
    "",
    "    def test_identify_cycle_phase(self):",
    "        from vnpy.temporal_intelligence_ai.utils.cycle_utils import identify_cycle_phase",
    "        from vnpy.temporal_intelligence_ai.constant import CyclePhase",
    "        phase, conf = identify_cycle_phase(volatility=0.15, trend=0.25,",
    "                                           momentum=0.3, drawdown=0.05, breadth=0.6)",
    "        assert isinstance(phase, CyclePhase)",
    "        assert 0.0 <= conf <= 1.0",
    "",
    "class TestDecayUtils:",
    "    def test_exponential_decay(self):",
    "        from vnpy.temporal_intelligence_ai.utils.decay_utils import exponential_decay",
    "        assert exponential_decay(1.0, 0.05, 0) == pytest.approx(1.0)",
    "        assert 0 < exponential_decay(1.0, 0.05, 10) < 1.0",
    "",
    "    def test_half_life_roundtrip(self):",
    "        from vnpy.temporal_intelligence_ai.utils.decay_utils import half_life_to_rate, rate_to_half_life",
    "        assert rate_to_half_life(half_life_to_rate(20.0)) == pytest.approx(20.0, rel=1e-6)",
    "",
    "    def test_compute_decay_metrics(self):",
    "        from vnpy.temporal_intelligence_ai.utils.decay_utils import compute_decay_metrics",
    "        from vnpy.temporal_intelligence_ai.constant import RegimeType, CyclePhase",
    "        m = compute_decay_metrics(10, 0.05, regime=RegimeType.BULL_QUIET, phase=CyclePhase.EXPANSION)",
    "        assert 0 < m.combined_strength <= 1.0",
    "        assert m.half_life > 0",
    "",
    "    def test_older_weaker(self):",
    "        from vnpy.temporal_intelligence_ai.utils.decay_utils import compute_decay_metrics",
    "        m1 = compute_decay_metrics(5, 0.05)",
    "        m2 = compute_decay_metrics(50, 0.05)",
    "        assert m2.combined_strength < m1.combined_strength",
    "",
    "    def test_crisis_weaker_than_bull(self):",
    "        from vnpy.temporal_intelligence_ai.utils.decay_utils import compute_decay_metrics",
    "        from vnpy.temporal_intelligence_ai.constant import RegimeType, CyclePhase",
    "        bull   = compute_decay_metrics(10, 0.05, regime=RegimeType.BULL_QUIET)",
    "        crisis = compute_decay_metrics(10, 0.05, regime=RegimeType.CRISIS)",
    "        assert crisis.combined_strength < bull.combined_strength",
    "",
    "    def test_build_decay_curve_monotone(self):",
    "        from vnpy.temporal_intelligence_ai.utils.decay_utils import build_decay_curve",
    "        from vnpy.temporal_intelligence_ai.constant import DecayMode",
    "        c = build_decay_curve('A1', DecayMode.EXPONENTIAL, 0, 0.05, horizon=20)",
    "        ss = c.strengths()",
    "        assert len(ss) == 21",
    "        assert ss[0] >= ss[-1]",
    "",
    "class TestDependencyUtils:",
    "    def _ar1(self, n=300, phi=0.7, seed=1):",
    "        random.seed(seed); xs = [0.0]",
    "        for _ in range(n-1): xs.append(phi*xs[-1]+random.gauss(0,1))",
    "        return xs",
    "",
    "    def test_autocorr_at_lag1(self):",
    "        from vnpy.temporal_intelligence_ai.utils.dependency_utils import autocorrelation_at_lag",
    "        r1 = autocorrelation_at_lag(self._ar1(500, phi=0.8), 1)",
    "        assert r1 > 0.6",
    "",
    "    def test_compute_autocorr(self):",
    "        from vnpy.temporal_intelligence_ai.utils.dependency_utils import compute_autocorr",
    "        result = compute_autocorr('sig1', self._ar1(200), max_lag=20)",
    "        assert result.signal_id == 'sig1'",
    "        assert len(result.lags) == 20",
    "        assert 0 <= result.memory_score <= 1.0",
    "",
    "    def test_crosscorr_lead_lag(self):",
    "        from vnpy.temporal_intelligence_ai.utils.dependency_utils import compute_crosscorr",
    "        random.seed(5); n = 300",
    "        a = [random.gauss(0,1) for _ in range(n)]",
    "        b = [0.0]*3 + a[:n-3]",
    "        result = compute_crosscorr('a', a, 'b', b, max_lag=10)",
    "        assert result.lead_lag == 3",
    "",
    "    def test_horizons_sum_to_one(self):",
    "        from vnpy.temporal_intelligence_ai.utils.dependency_utils import decompose_horizons",
    "        h = decompose_horizons(self._ar1(300))",
    "        total = h.short_term_weight + h.mid_term_weight + h.long_term_weight",
    "        assert total == pytest.approx(1.0, abs=0.02)",
    "",
    "class TestTransitionUtils:",
    "    def _rets(self, n=200, mean=0.001, vol=0.02, seed=3):",
    "        random.seed(seed)",
    "        return [random.gauss(mean,vol) for _ in range(n)]",
    "",
    "    def _prices(self, rets, p0=100.0):",
    "        ps=[p0]",
    "        for r in rets: ps.append(ps[-1]*(1+r))",
    "        return ps",
    "",
    "    def test_regime_shift_range(self):",
    "        from vnpy.temporal_intelligence_ai.utils.transition_utils import detect_regime_shift",
    "        sig = detect_regime_shift(self._rets(200))",
    "        assert 0.0 <= sig.strength <= 1.0",
    "",
    "    def test_volatility_break_range(self):",
    "        from vnpy.temporal_intelligence_ai.utils.transition_utils import detect_volatility_break",
    "        rets = self._rets(60, vol=0.005) + self._rets(20, vol=0.08)",
    "        sig  = detect_volatility_break(self._prices(rets))",
    "        assert sig.strength >= 0.0",
    "",
    "    def test_regime_probs_sum_to_one(self):",
    "        from vnpy.temporal_intelligence_ai.utils.transition_utils import estimate_regime_probabilities",
    "        probs = estimate_regime_probabilities(0.20, 0.15, 0.3, 0.2)",
    "        assert sum(probs.probabilities.values()) == pytest.approx(1.0, abs=0.01)",
    "",
    "    def test_transition_prob_range(self):",
    "        from vnpy.temporal_intelligence_ai.utils.transition_utils import (",
    "            compute_transition_probability, detect_regime_shift,",
    "            detect_volatility_break, detect_liquidity_regime)",
    "        rets = self._rets(200)",
    "        tp, tc = compute_transition_probability(",
    "            detect_regime_shift(rets),",
    "            detect_volatility_break(self._prices(rets)),",
    "            detect_liquidity_regime([1.0]*200, rets))",
    "        assert 0.0 <= tp <= 1.0",
    "        assert 0.0 <= tc <= 1.0",
    "",
    "class TestTemporalUtils:",
    "    def _records(self, n=20, noise=0.05, seed=9):",
    "        from vnpy.temporal_intelligence_ai.model.validation_model import ValidationRecord",
    "        random.seed(seed); recs = []",
    "        for i in range(n):",
    "            p = random.gauss(0, 0.5)",
    "            recs.append(ValidationRecord(record_id=f'r{i}', predicted=p,",
    "                                         realized=p+random.gauss(0,noise), is_realized=True))",
    "        return recs",
    "",
    "    def test_mae_nonneg(self):",
    "        from vnpy.temporal_intelligence_ai.utils.temporal_utils import compute_errors, compute_mae",
    "        assert compute_mae(compute_errors(self._records(50))) >= 0",
    "",
    "    def test_rmse_ge_mae(self):",
    "        from vnpy.temporal_intelligence_ai.utils.temporal_utils import compute_errors, compute_mae, compute_rmse",
    "        res = compute_errors(self._records(50))",
    "        assert compute_rmse(res) >= compute_mae(res)",
    "",
    "    def test_direction_acc_range(self):",
    "        from vnpy.temporal_intelligence_ai.utils.temporal_utils import compute_errors, compute_direction_accuracy",
    "        acc = compute_direction_accuracy(compute_errors(self._records(100)))",
    "        assert 0.0 <= acc <= 1.0",
    "",
    "    def test_health_score_range(self):",
    "        from vnpy.temporal_intelligence_ai.utils.temporal_utils import compute_temporal_health",
    "        s = compute_temporal_health(0.6, 0.7, 0.5, 30, 0.02)",
    "        assert 0.0 <= s <= 100.0",
    "",
    "    def test_decay_alignment_perfect(self):",
    "        from vnpy.temporal_intelligence_ai.utils.temporal_utils import compute_decay_alignment",
    "        s = [1.0, 0.9, 0.8, 0.5, 0.2, 0.04]",
    "        align, _ = compute_decay_alignment(s, s)",
    "        assert align == pytest.approx(1.0)",
    "",
    "    def test_build_metrics(self):",
    "        from vnpy.temporal_intelligence_ai.utils.temporal_utils import build_validation_metrics",
    "        m = build_validation_metrics(self._records(30))",
    "        assert m.n_records == 30 and m.mae >= 0",
    "        assert 0 <= m.temporal_health <= 100",
]

out = pathlib.Path(__file__).parent / "test_temporal_intelligence.py"
out.write_text("\n".join(LINES) + "\n", encoding="utf-8")
print(f"Written {len(LINES)} lines to {out}")
