"""Generate test_temporal_intelligence.py as clean UTF-8."""
import pathlib

P = pathlib.Path(r"c:\Users\11229\Documents\GitHub\vnpy\tests\test_temporal_intelligence.py")

PART1 = (
    "from __future__ import annotations\n"
    "import math, random\n"
    "import pytest\n"
    "\n"
    "\n"
    "class TestCycleUtils:\n"
    "    def _prices(self, n=100, trend=0.001, vol=0.02, seed=42):\n"
    "        random.seed(seed); ps = [100.0]\n"
    "        for _ in range(n-1): ps.append(ps[-1]*(1+trend+random.gauss(0,vol)))\n"
    "        return ps\n"
    "\n"
    "    def test_rolling_returns(self):\n"
    "        from vnpy.temporal_intelligence_ai.utils.cycle_utils import rolling_returns\n"
    "        rets = rolling_returns(self._prices(50), window=10)\n"
    "        assert len(rets) == 50\n"
    "        assert all(r == 0.0 for r in rets[:10])\n"
    "        assert any(r != 0.0 for r in rets[10:])\n"
    "\n"
    "    def test_annualized_volatility(self):\n"
    "        from vnpy.temporal_intelligence_ai.utils.cycle_utils import annualized_volatility\n"
    "        assert 0.0 < annualized_volatility(self._prices(100), window=20) < 2.0\n"
    "\n"
    "    def test_trend_strength(self):\n"
    "        from vnpy.temporal_intelligence_ai.utils.cycle_utils import trend_strength\n"
    "        ts = trend_strength(self._prices(60), fast=5, slow=20)\n"
    "        assert -1.0 <= ts <= 1.0\n"
    "\n"
    "    def test_max_drawdown(self):\n"
    "        from vnpy.temporal_intelligence_ai.utils.cycle_utils import max_drawdown\n"
    "        assert 0.0 < max_drawdown([100, 110, 90, 95, 80, 100]) <= 1.0\n"
    "\n"
    "    def test_identify_cycle_phase(self):\n"
    "        from vnpy.temporal_intelligence_ai.utils.cycle_utils import identify_cycle_phase\n"
    "        from vnpy.temporal_intelligence_ai.constant import CyclePhase\n"
    "        phase, conf = identify_cycle_phase(\n"
    "            volatility=0.15, trend=0.25, momentum=0.3, drawdown=0.05, breadth=0.6)\n"
    "        assert isinstance(phase, CyclePhase)\n"
    "        assert 0.0 <= conf <= 1.0\n"
    "\n"
    "\n"
    "class TestDecayUtils:\n"
    "    def test_exponential_decay(self):\n"
    "        from vnpy.temporal_intelligence_ai.utils.decay_utils import exponential_decay\n"
    "        assert exponential_decay(1.0, 0.05, 0) == pytest.approx(1.0)\n"
    "        assert 0 < exponential_decay(1.0, 0.05, 10) < 1.0\n"
    "\n"
    "    def test_half_life_roundtrip(self):\n"
    "        from vnpy.temporal_intelligence_ai.utils.decay_utils import half_life_to_rate, rate_to_half_life\n"
    "        assert rate_to_half_life(half_life_to_rate(20.0)) == pytest.approx(20.0, rel=1e-6)\n"
    "\n"
    "    def test_compute_decay_metrics(self):\n"
    "        from vnpy.temporal_intelligence_ai.utils.decay_utils import compute_decay_metrics\n"
    "        from vnpy.temporal_intelligence_ai.constant import RegimeType, CyclePhase\n"
    "        m = compute_decay_metrics(\n"
    "            10, 0.05, regime=RegimeType.BULL_QUIET, phase=CyclePhase.EXPANSION)\n"
    "        assert 0 < m.combined_strength <= 1.0\n"
    "        assert m.half_life > 0\n"
    "\n"
    "    def test_older_weaker(self):\n"
    "        from vnpy.temporal_intelligence_ai.utils.decay_utils import compute_decay_metrics\n"
    "        assert (compute_decay_metrics(50, 0.05).combined_strength\n"
    "                < compute_decay_metrics(5, 0.05).combined_strength)\n"
    "\n"
    "    def test_crisis_weaker(self):\n"
    "        from vnpy.temporal_intelligence_ai.utils.decay_utils import compute_decay_metrics\n"
    "        from vnpy.temporal_intelligence_ai.constant import RegimeType\n"
    "        bull   = compute_decay_metrics(10, 0.05, regime=RegimeType.BULL_QUIET)\n"
    "        crisis = compute_decay_metrics(10, 0.05, regime=RegimeType.CRISIS)\n"
    "        assert crisis.combined_strength < bull.combined_strength\n"
    "\n"
    "    def test_build_decay_curve(self):\n"
    "        from vnpy.temporal_intelligence_ai.utils.decay_utils import build_decay_curve\n"
    "        from vnpy.temporal_intelligence_ai.constant import DecayMode\n"
    "        c = build_decay_curve('A1', DecayMode.EXPONENTIAL, 0, 0.05, horizon=20)\n"
    "        ss = c.strengths()\n"
    "        assert len(ss) == 21\n"
    "        assert ss[0] >= ss[-1]\n"
    "\n"
    "\n"
    "class TestDependencyUtils:\n"
    "    def _ar1(self, n=300, phi=0.7, seed=1):\n"
    "        random.seed(seed); xs = [0.0]\n"
    "        for _ in range(n - 1): xs.append(phi * xs[-1] + random.gauss(0, 1))\n"
    "        return xs\n"
    "\n"
    "    def test_autocorr_lag1(self):\n"
    "        from vnpy.temporal_intelligence_ai.utils.dependency_utils import autocorrelation_at_lag\n"
    "        assert autocorrelation_at_lag(self._ar1(500, phi=0.8), 1) > 0.6\n"
    "\n"
    "    def test_compute_autocorr(self):\n"
    "        from vnpy.temporal_intelligence_ai.utils.dependency_utils import compute_autocorr\n"
    "        r = compute_autocorr('sig1', self._ar1(200), max_lag=20)\n"
    "        assert r.signal_id == 'sig1'\n"
    "        assert len(r.lags) == 20\n"
    "        assert 0 <= r.memory_score <= 1.0\n"
    "\n"
    "    def test_crosscorr_lead_lag(self):\n"
    "        from vnpy.temporal_intelligence_ai.utils.dependency_utils import compute_crosscorr\n"
    "        random.seed(5); n = 300\n"
    "        a = [random.gauss(0, 1) for _ in range(n)]\n"
    "        b = [0.0] * 3 + a[:n - 3]\n"
    "        assert compute_crosscorr('a', a, 'b', b, max_lag=10).lead_lag == 3\n"
    "\n"
    "    def test_horizons_sum(self):\n"
    "        from vnpy.temporal_intelligence_ai.utils.dependency_utils import decompose_horizons\n"
    "        h = decompose_horizons(self._ar1(300))\n"
    "        assert (h.short_term_weight + h.mid_term_weight + h.long_term_weight) == pytest.approx(1.0, abs=0.02)\n"
    "\n"
    "\n"
    "class TestTransitionUtils:\n"
    "    def _rets(self, n=200, mean=0.001, vol=0.02, seed=3):\n"
    "        random.seed(seed)\n"
    "        return [random.gauss(mean, vol) for _ in range(n)]\n"
    "\n"
    "    def _prices(self, rets, p0=100.0):\n"
    "        ps = [p0]\n"
    "        for r in rets: ps.append(ps[-1] * (1 + r))\n"
    "        return ps\n"
    "\n"
    "    def test_regime_shift_range(self):\n"
    "        from vnpy.temporal_intelligence_ai.utils.transition_utils import detect_regime_shift\n"
    "        sig = detect_regime_shift(self._rets(200))\n"
    "        assert 0.0 <= sig.strength <= 1.0\n"
    "\n"
    "    def test_volatility_break_range(self):\n"
    "        from vnpy.temporal_intelligence_ai.utils.transition_utils import detect_volatility_break\n"
    "        rets = self._rets(60, vol=0.005) + self._rets(20, vol=0.08)\n"
    "        assert detect_volatility_break(self._prices(rets)).strength >= 0.0\n"
    "\n"
    "    def test_regime_probs_sum(self):\n"
    "        from vnpy.temporal_intelligence_ai.utils.transition_utils import estimate_regime_probabilities\n"
    "        probs = estimate_regime_probabilities(0.20, 0.15, 0.3, 0.2)\n"
    "        assert sum(probs.probabilities.values()) == pytest.approx(1.0, abs=0.01)\n"
    "\n"
    "    def test_transition_prob_range(self):\n"
    "        from vnpy.temporal_intelligence_ai.utils.transition_utils import (\n"
    "            compute_transition_probability, detect_regime_shift,\n"
    "            detect_volatility_break, detect_liquidity_regime)\n"
    "        rets = self._rets(200)\n"
    "        tp, tc = compute_transition_probability(\n"
    "            detect_regime_shift(rets),\n"
    "            detect_volatility_break(self._prices(rets)),\n"
    "            detect_liquidity_regime([1.0] * 200, rets))\n"
    "        assert 0.0 <= tp <= 1.0\n"
    "        assert 0.0 <= tc <= 1.0\n"
    "\n"
    "\n"
    "class TestTemporalUtils:\n"
    "    def _records(self, n=20, noise=0.05, seed=9):\n"
    "        from vnpy.temporal_intelligence_ai.model.validation_model import ValidationRecord\n"
    "        random.seed(seed); recs = []\n"
    "        for i in range(n):\n"
    "            p = random.gauss(0, 0.5)\n"
    "            recs.append(ValidationRecord(\n"
    "                record_id=f'r{i}', predicted=p,\n"
    "                realized=p + random.gauss(0, noise), is_realized=True))\n"
    "        return recs\n"
    "\n"
    "    def test_mae_nonneg(self):\n"
    "        from vnpy.temporal_intelligence_ai.utils.temporal_utils import compute_errors, compute_mae\n"
    "        assert compute_mae(compute_errors(self._records(50))) >= 0\n"
    "\n"
    "    def test_rmse_ge_mae(self):\n"
    "        from vnpy.temporal_intelligence_ai.utils.temporal_utils import (\n"
    "            compute_errors, compute_mae, compute_rmse)\n"
    "        res = compute_errors(self._records(50))\n"
    "        assert compute_rmse(res) >= compute_mae(res)\n"
    "\n"
    "    def test_direction_acc_range(self):\n"
    "        from vnpy.temporal_intelligence_ai.utils.temporal_utils import (\n"
    "            compute_errors, compute_direction_accuracy)\n"
    "        assert 0.0 <= compute_direction_accuracy(compute_errors(self._records(100))) <= 1.0\n"
    "\n"
    "    def test_health_score_range(self):\n"
    "        from vnpy.temporal_intelligence_ai.utils.temporal_utils import compute_temporal_health\n"
    "        assert 0.0 <= compute_temporal_health(0.6, 0.7, 0.5, 30, 0.02) <= 100.0\n"
    "\n"
    "    def test_decay_alignment_perfect(self):\n"
    "        from vnpy.temporal_intelligence_ai.utils.temporal_utils import compute_decay_alignment\n"
    "        s = [1.0, 0.9, 0.8, 0.5, 0.2, 0.04]\n"
    "        align, _ = compute_decay_alignment(s, s)\n"
    "        assert align == pytest.approx(1.0)\n"
    "\n"
    "    def test_build_metrics(self):\n"
    "        from vnpy.temporal_intelligence_ai.utils.temporal_utils import build_validation_metrics\n"
    "        m = build_validation_metrics(self._records(30))\n"
    "        assert m.n_records == 30 and m.mae >= 0\n"
    "        assert 0 <= m.temporal_health <= 100\n"
)

P.write_text(PART1, encoding="utf-8")
print("part1 written", P.stat().st_size, "bytes")
