"""fix_dash_events.py — 修正 dashboard_tab.py 的事件 import"""
import pathlib, ast

P = pathlib.Path(
    r"c:\Users\11229\Documents\GitHub\vnpy\vnpy\research_ops\ui\dashboard_tab.py"
)
src = P.read_text(encoding="utf-8")

OLD_IMPORT = """from ..event import (
    EVENT_RO_EXP_CREATED, EVENT_RO_EXP_UPDATED, EVENT_RO_EXP_DELETED,
    EVENT_RO_RUN_STARTED, EVENT_RO_RUN_COMPLETED, EVENT_RO_RUN_FAILED,
    EVENT_RO_PL_CREATED, EVENT_RO_PL_STARTED, EVENT_RO_PL_COMPLETED, EVENT_RO_PL_FAILED,
    EVENT_RO_RPT_CREATED, EVENT_RO_RPT_PUBLISHED,
    EVENT_RO_KB_CREATED, EVENT_RO_KB_UPDATED,
    EVENT_RO_DS_CREATED, EVENT_RO_DS_REGISTERED,
    EVENT_RO_MODEL_REGISTERED, EVENT_RO_MODEL_DEPLOYED,
    EVENT_RO_FEAT_REGISTERED,
    EVENT_RO_STRAT_REGISTERED,
)"""

NEW_IMPORT = """from ..event import (
    EVENT_RO_EXP_CREATED, EVENT_RO_EXP_UPDATED, EVENT_RO_EXP_DELETED,
    EVENT_RO_EXP_STARTED, EVENT_RO_EXP_COMPLETED, EVENT_RO_EXP_FAILED,
    EVENT_RO_RUN_CREATED, EVENT_RO_RUN_COMPLETED, EVENT_RO_RUN_FAILED,
    EVENT_RO_PL_CREATED, EVENT_RO_PL_STARTED, EVENT_RO_PL_COMPLETED, EVENT_RO_PL_FAILED,
    EVENT_RO_RPT_CREATED, EVENT_RO_RPT_PUBLISHED,
    EVENT_RO_KB_CREATED, EVENT_RO_KB_UPDATED,
    EVENT_RO_DS_CREATED, EVENT_RO_DS_REGISTERED,
    EVENT_RO_ML_REGISTERED, EVENT_RO_ML_DEPLOYED,
    EVENT_RO_FT_REGISTERED,
    EVENT_RO_ST_REGISTERED,
)"""

assert OLD_IMPORT in src, "import block not found"
src = src.replace(OLD_IMPORT, NEW_IMPORT)

# fix EVENT_ALL list
OLD_ALL = """EVENT_ALL = [
    EVENT_RO_EXP_CREATED, EVENT_RO_EXP_UPDATED, EVENT_RO_EXP_DELETED,
    EVENT_RO_RUN_STARTED,  EVENT_RO_RUN_COMPLETED, EVENT_RO_RUN_FAILED,
    EVENT_RO_PL_CREATED,   EVENT_RO_PL_STARTED,
    EVENT_RO_PL_COMPLETED, EVENT_RO_PL_FAILED,
    EVENT_RO_RPT_CREATED,  EVENT_RO_RPT_PUBLISHED,
    EVENT_RO_KB_CREATED,   EVENT_RO_KB_UPDATED,
    EVENT_RO_DS_CREATED,   EVENT_RO_DS_REGISTERED,
    EVENT_RO_MODEL_REGISTERED, EVENT_RO_MODEL_DEPLOYED,
    EVENT_RO_FEAT_REGISTERED,
    EVENT_RO_STRAT_REGISTERED,
]"""

NEW_ALL = """EVENT_ALL = [
    EVENT_RO_EXP_CREATED,  EVENT_RO_EXP_UPDATED,    EVENT_RO_EXP_DELETED,
    EVENT_RO_EXP_STARTED,  EVENT_RO_EXP_COMPLETED,  EVENT_RO_EXP_FAILED,
    EVENT_RO_RUN_CREATED,  EVENT_RO_RUN_COMPLETED,  EVENT_RO_RUN_FAILED,
    EVENT_RO_PL_CREATED,   EVENT_RO_PL_STARTED,
    EVENT_RO_PL_COMPLETED, EVENT_RO_PL_FAILED,
    EVENT_RO_RPT_CREATED,  EVENT_RO_RPT_PUBLISHED,
    EVENT_RO_KB_CREATED,   EVENT_RO_KB_UPDATED,
    EVENT_RO_DS_CREATED,   EVENT_RO_DS_REGISTERED,
    EVENT_RO_ML_REGISTERED, EVENT_RO_ML_DEPLOYED,
    EVENT_RO_FT_REGISTERED,
    EVENT_RO_ST_REGISTERED,
]"""

assert OLD_ALL in src, "EVENT_ALL block not found"
src = src.replace(OLD_ALL, NEW_ALL)

# fix _EV_MAP references
RENAMES = [
    ("EVENT_RO_RUN_STARTED",      "EVENT_RO_RUN_CREATED"),
    ("EVENT_RO_MODEL_REGISTERED", "EVENT_RO_ML_REGISTERED"),
    ("EVENT_RO_MODEL_DEPLOYED",   "EVENT_RO_ML_DEPLOYED"),
    ("EVENT_RO_FEAT_REGISTERED",  "EVENT_RO_FT_REGISTERED"),
    ("EVENT_RO_STRAT_REGISTERED", "EVENT_RO_ST_REGISTERED"),
]
for old, new in RENAMES:
    src = src.replace(old, new)

ast.parse(src)
P.write_text(src, encoding="utf-8")
print("events fixed OK, size:", P.stat().st_size)
