"""Deviation 均线偏离类条件 Insight 数据"""
from ...constant import ConditionIndicator
from ..schema import ConditionInsight, ConditionRole, ParamInsight

DEVIATION_INSIGHTS = {
    ConditionIndicator.DEV_MA5: ConditionInsight(
        name="MA5乖离率",
        category="Deviation",
        roles=[ConditionRole.RISK_FILTER],
        description="价格与MA5的偏离程度，过滤短期超涨或超跌。",
        formula="BIAS = (Close - MA5) / MA5 × 100",
        trigger="BIAS在指定范围内",
        parameters=[
            ParamInsight("max_bias", "乖离上限%", "最大正乖离", 8.0, 0, 20,
                         "5-8", "8-10", "5-8"),
        ],
        scenarios_good=["过滤超涨票", "控制追高风险"],
        scenarios_bad=["强势连板股乖离可以很大"],
        combinations=["均线多头排列", "回踩MA10"],
        combo_model="乖离过滤模型",
        risks=["强势股乖离可持续扩大"],
        experience="MA5乖离>8%为短期超涨，回调概率增大。",
    ),
    ConditionIndicator.DEV_MA10: ConditionInsight(
        name="MA10乖离率",
        category="Deviation",
        roles=[ConditionRole.RISK_FILTER],
        description="价格与MA10的偏离程度。",
        formula="BIAS = (Close - MA10) / MA10 × 100",
        trigger="BIAS在指定范围内",
        parameters=[
            ParamInsight("max_bias", "乖离上限%", "最大正乖离", 10.0, 0, 30,
                         "8-10", "10-15", "8-12"),
        ],
        scenarios_good=["中短线超涨过滤"],
        scenarios_bad=["趋势加速期"],
        combinations=["均线多头排列"],
        combo_model="乖离风控模型",
        risks=["乖离过滤会错过趋势加速段"],
        experience="MA10乖离>10%建议等回踩再买入。",
    ),
    ConditionIndicator.DEV_MA20: ConditionInsight(
        name="MA20乖离率",
        category="Deviation",
        roles=[ConditionRole.RISK_FILTER],
        description="价格与MA20的偏离程度，中期超涨/超跌过滤。",
        formula="BIAS = (Close - MA20) / MA20 × 100",
        trigger="BIAS在指定范围内",
        parameters=[
            ParamInsight("max_bias", "乖离上限%", "最大正乖离", 15.0, 0, 50,
                         "10-15", "15-20", "12-15"),
        ],
        scenarios_good=["中线超涨过滤"],
        scenarios_bad=["中期趋势加速"],
        combinations=["回踩MA20"],
        combo_model="中线乖离风控",
        risks=["乖离率过滤在牛市中可能过于保守"],
        experience="MA20乖离>15%属于中期超涨，回调压力大。",
    ),
    ConditionIndicator.DEV_MA10_MA20: ConditionInsight(
        name="MA10-MA20距离",
        category="Deviation",
        roles=[ConditionRole.RISK_FILTER],
        description="两条均线之间的距离百分比，判断均线发散程度。",
        formula="距离 = (MA10 - MA20) / MA20 × 100",
        trigger="距离 <= max_distpct",
        parameters=[
            ParamInsight("max_dist_pct", "距离上限%", "MA10与MA20最大间距",
                         5.0, 0, 15, "3-5", "5-8", "4-6"),
        ],
        scenarios_good=["均线未过度发散时买入更安全"],
        scenarios_bad=["趋势加速初期均线快速发散"],
        combinations=["回踩MA10", "均线多头排列"],
        combo_model="均线距离过滤模型",
        risks=["均线距离过大时回调幅度可能较大"],
        experience="MA10-MA20距离<5%说明均线还未过度发散，回调风险可控。",
    ),
    ConditionIndicator.DEV_OVERBOUGHT: ConditionInsight(
        name="超涨过滤",
        category="Deviation",
        roles=[ConditionRole.RISK_FILTER],
        description="综合乖离率判断是否超涨，用于排除过高位置的票。",
        formula="综合MA5/MA10/MA20乖离率",
        trigger="乖离率未超限",
        parameters=[],
        scenarios_good=["风险控制", "避免追高"],
        scenarios_bad=["可能错过趋势加速"],
        combinations=["回踩MA10", "缩量回调"],
        combo_model="安全买入过滤模型",
        risks=["过于保守可能降低收益"],
        experience="综合乖离过滤可以有效降低追高风险。",
    ),
    ConditionIndicator.DEV_MA_DISTANCE: ConditionInsight(
        name="均线距离过滤",
        category="Deviation",
        roles=[ConditionRole.RISK_FILTER],
        description="过滤均线间距过大的标的，避免在均线过度发散时介入。",
        formula="相邻均线距离百分比",
        trigger="所有相邻均线间距 <= threshold",
        parameters=[
            ParamInsight("max_gap", "间距上限%", "相邻均线最大间距", 5.0, 1, 15,
                         "3-5", "5-8", "4-6"),
        ],
        scenarios_good=["均线收敛时买入更安全"],
        scenarios_bad=["趋势加速期均线会快速发散"],
        combinations=["均线多头排列", "回踩MA10"],
        combo_model="安全趋势买入模型",
        risks=["限制了趋势加速阶段的买入"],
        experience="均线距离过滤确保买入时均线结构紧凑，回调空间有限。",
    ),
}