"""Kline K线形态类条件 Insight 数据"""
from ...constant import ConditionIndicator
from ..schema import ConditionInsight, ConditionRole, ParamInsight

KLINE_INSIGHTS = {
    ConditionIndicator.KLINE_YIN: ConditionInsight(
        name="阴线",
        category="Kline",
        roles=[ConditionRole.CONFIRMATION],
        description="收盘价低于开盘价，当日下跌K线。",
        formula="Close < Open",
        trigger="收阴线",
        parameters=[],
        scenarios_good=["回调买入确认（缩量阴线）", "判断调整状态"],
        scenarios_bad=["单独使用意义不大"],
        combinations=["缩量调整", "回踩MA10"],
        combo_model="缩量阴线低吸模型",
        risks=["阴线本身不是买入信号", "需配合量能和趋势使用"],
        experience="缩量阴线=惜售；放量阴线=抛压。区别对待。",
    ),
    ConditionIndicator.KLINE_YANG: ConditionInsight(
        name="阳线",
        category="Kline",
        roles=[ConditionRole.CONFIRMATION],
        description="收盘价高于开盘价，当日上涨K线。",
        formula="Close > Open",
        trigger="收阳线",
        parameters=[],
        scenarios_good=["反弹确认", "趋势延续确认"],
        scenarios_bad=["单独使用意义不大"],
        combinations=["放量上涨", "均线多头排列"],
        combo_model="放量阳线突破模型",
        risks=["阳线不代表趋势转好", "高位阳线可能是诱多"],
        experience="底部放量大阳线是最强的反转信号之一。",
    ),
    ConditionIndicator.KLINE_SHRINK_YIN: ConditionInsight(
        name="缩量阴线",
        category="Kline",
        roles=[ConditionRole.ENTRY_TRIGGER, ConditionRole.CONFIRMATION],
        description="收阴线且成交量低于均量，表明下跌无卖压、筹码惜售。",
        formula="Close < Open 且 volume < MA(volume, 5)",
        trigger="阴线 + 缩量",
        parameters=[
            ParamInsight("vol_period", "均量周期", "比较用的均量周期", 5, 3, 20,
                         "5", "5-10", "5"),
            ParamInsight("vol_ratio", "缩量比例", "量/均量的上限", 0.8, 0.3, 1.0,
                         "0.6-0.8", "0.7-0.8", "0.7"),
        ],
        scenarios_good=["强势股回调惜售", "低吸经典形态"],
        scenarios_bad=["持续缩量阴跌", "空头趋势中"],
        combinations=["回踩MA10", "均线多头排列", "趋势未破坏"],
        combo_model="强势股缩量回调低吸模型",
        risks=["必须在上升趋势中使用", "持续缩量阴线可能是阴跌"],
        experience="这是低吸策略中最核心的K线形态。"
                   "强势股回调出现缩量阴线，通常是最佳买点。",
    ),
    ConditionIndicator.KLINE_VOL_YIN: ConditionInsight(
        name="放量阴线",
        category="Kline",
        roles=[ConditionRole.RISK_FILTER],
        description="收阴线且成交量大于均量，表明有主动抛压。用于风险过滤。",
        formula="Close < Open 且 volume > MA(volume, 5)",
        trigger="阴线 + 放量（作为排除条件）",
        parameters=[
            ParamInsight("vol_period", "均量周期", "比较用的均量周期", 5, 3, 20,
                         "5", "5", "5"),
            ParamInsight("vol_ratio", "放量比例", "量/均量的下限", 1.2, 1.0, 3.0,
                         "1.2-1.5", "1.5", "1.2"),
        ],
        scenarios_good=["过滤有抛压的票", "识别出货日"],
        scenarios_bad=["底部放量阴线可能是最后一跌"],
        combinations=["趋势未破坏（排除用）"],
        combo_model="风险过滤模型",
        risks=["放量阴线不一定是出货，可能是洗盘",
               "底部放量阴线可能是恐慌盘最后释放"],
        experience="高位放量阴线是最危险的信号之一。"
                   "低位放量阴线可能是空方衰竭，需综合判断。",
    ),
    ConditionIndicator.KLINE_LONG_LOWER: ConditionInsight(
        name="长下影线",
        category="Kline",
        roles=[ConditionRole.ENTRY_TRIGGER, ConditionRole.CONFIRMATION],
        description="下影线长度超过实体N倍，表明盘中有强力买盘支撑。",
        formula="下影线 = min(Open,Close) - Low",
        trigger="下影线 >= 实体 × ratio",
        parameters=[
            ParamInsight("shadow_ratio", "影线比例", "下影线/实体的最小倍数",
                         2.0, 1.0, 5.0, "1.5-2", "2-3", "2"),
        ],
        scenarios_good=["回调见底信号", "支撑位确认"],
        scenarios_bad=["连续长下影（支撑在消耗）"],
        combinations=["回踩MA10", "缩量调整"],
        combo_model="长下影止跌确认模型",
        risks=["长下影不一定止跌", "高位长下影可能是诱多"],
        experience="回调后出现长下影线=多方反击。"
                   "在支撑位附近的长下影更有意义。",
    ),
    ConditionIndicator.KLINE_DOJI: ConditionInsight(
        name="十字星",
        category="Kline",
        roles=[ConditionRole.CONFIRMATION],
        description="开收盘价接近，实体极小，表明多空平衡、市场犹豫。",
        formula="abs(Close - Open) / (High - Low) < ratio",
        trigger="实体/振幅 < threshold",
        parameters=[
            ParamInsight("body_ratio", "实体比例", "实体占振幅的最大比例",
                         0.1, 0.01, 0.3, "0.05-0.1", "0.1", "0.1"),
        ],
        scenarios_good=["变盘信号", "回调末期的犹豫信号"],
        scenarios_bad=["趋势明确时出现十字星意义不大"],
        combinations=["回踩MA10", "缩量调整"],
        combo_model="十字星变盘模型",
        risks=["十字星后方向不确定", "需等待次日确认"],
        experience="回调后缩量十字星是经典的止跌信号。"
                   "但必须等次日阳线确认方向后再入场。",
    ),
    ConditionIndicator.KLINE_BIG_YANG: ConditionInsight(
        name="大阳线",
        category="Kline",
        roles=[ConditionRole.ENTRY_TRIGGER, ConditionRole.CONFIRMATION],
        description="涨幅超过阈值的阳线，表明多方力量强劲。",
        formula="(Close - Open) / Open × 100 >= min_pct",
        trigger="实体涨幅 >= min_pct",
        parameters=[
            ParamInsight("min_pct", "最小涨幅%", "大阳线的最小实体涨幅",
                         5.0, 3.0, 10.0, "5-7", "5", "5"),
        ],
        scenarios_good=["突破确认", "趋势启动", "底部反转"],
        scenarios_bad=["高位大阳可能是最后一涨"],
        combinations=["放量上涨", "N日新高"],
        combo_model="放量大阳突破模型",
        risks=["高位大阳线可能是拉高出货", "追涨风险"],
        experience="底部放量大阳线是最强的突破信号。"
                   "首次大阳线后缩量回踩是经典买点。",
    ),
    ConditionIndicator.KLINE_LIMIT_UP: ConditionInsight(
        name="涨停K线",
        category="Kline",
        roles=[ConditionRole.CONFIRMATION],
        description="当日收盘涨幅达到涨停板（A股10%或20%），强势特征。",
        formula="(Close - prev_Close) / prev_Close >= 0.095",
        trigger="涨幅 >= 涨停阈值",
        parameters=[
            ParamInsight("limit_pct", "涨停阈值%", "涨停幅度", 9.5, 4.5, 20,
                         "9.5", "9.5", "9.5"),
        ],
        scenarios_good=["强势股确认", "板块启动信号"],
        scenarios_bad=["追涨停风险高"],
        combinations=["N日涨幅", "均线多头排列"],
        combo_model="涨停板选股模型",
        risks=["涨停次日可能高开低走", "流动性风险"],
        experience="近期有涨停的票说明有资金关注、有题材驱动。"
                   "涨停后首次缩量回踩是经典的接力买点。",
    ),
    ConditionIndicator.KLINE_COMBO: ConditionInsight(
        name="K线组合",
        category="Kline",
        roles=[ConditionRole.ENTRY_TRIGGER],
        description="多根K线组合形态识别（如红三兵、晨星等）。",
        formula="多根K线的组合模式匹配",
        trigger="匹配指定K线组合模式",
        parameters=[
            ParamInsight("pattern", "组合类型", "K线组合名称",
                         "morning_star", None, None, "", "", ""),
        ],
        scenarios_good=["经典底部形态确认", "反转信号"],
        scenarios_bad=["机械匹配容易过拟合"],
        combinations=["缩量调整", "回踩MA20"],
        combo_model="K线形态反转模型",
        risks=["K线组合识别有主观性", "历史形态不代表未来"],
        experience="K线组合需配合位置（支撑位/均线附近）使用才有意义。"
                   "孤立的K线形态信号可靠性较低。",
    ),
}