"""Market 市场环境 & Exit 退出 & 其他条件 Insight 数据"""
from ...constant import ConditionIndicator
from ..schema import ConditionInsight, ConditionRole, ParamInsight

MARKET_INSIGHTS = {
    ConditionIndicator.MARKET_INDEX_TREND: ConditionInsight(
        name="指数趋势",
        category="Market",
        roles=[ConditionRole.RISK_FILTER],
        description="判断大盘指数是否处于上升趋势，控制系统性风险。",
        formula="指数Close > 指数MA(N)",
        trigger="指数站上均线",
        parameters=[
            ParamInsight("ma_period", "指数MA周期", "指数均线周期", 20, 5, 60,
                         "10-20", "20", "20"),
        ],
        scenarios_good=["牛市/震荡市中做多", "系统性风险过滤"],
        scenarios_bad=["指数滞后于个股"],
        combinations=["所有买入条件"],
        combo_model="市场环境开关",
        risks=["指数均线是滞后指标"],
        experience="大盘在MA20上方时做多胜率显著提升。"
                   "大盘跌破MA20时应降低仓位或停止买入。",
    ),
    ConditionIndicator.MARKET_INDEX_MA: ConditionInsight(
        name="指数均线状态",
        category="Market",
        roles=[ConditionRole.RISK_FILTER],
        description="判断指数均线排列状态（多头/空头/震荡）。",
        formula="指数MA5 vs MA10 vs MA20排列",
        trigger="指数均线多头排列",
        parameters=[],
        scenarios_good=["确认大盘处于多头环境"],
        scenarios_bad=["震荡市中均线缠绕"],
        combinations=["所有买入条件"],
        combo_model="市场环境确认",
        risks=["大盘均线状态转换有延迟"],
        experience="指数MA5>MA10>MA20时市场整体偏多，个股操作胜率更高。",
    ),
    ConditionIndicator.MARKET_UP_RATIO: ConditionInsight(
        name="涨跌比例",
        category="Market",
        roles=[ConditionRole.RISK_FILTER],
        description="当日上涨家数与下跌家数的比例，衡量市场广度。",
        formula="涨跌比 = 上涨家数 / (上涨家数 + 下跌家数)",
        trigger="涨跌比 >= threshold",
        parameters=[
            ParamInsight("min_ratio", "最低涨跌比", "上涨占比下限", 0.5, 0, 1,
                         "0.4-0.5", "0.5-0.6", "0.5"),
        ],
        scenarios_good=["确认市场整体偏多"],
        scenarios_bad=["结构性行情中涨跌比失效"],
        combinations=["指数趋势"],
        combo_model="市场广度确认",
        risks=["权重股拉指数但多数票下跌时涨跌比更有效"],
        experience="超过60%的票上涨时市场情绪积极。低于40%时谨慎。",
    ),
    ConditionIndicator.MARKET_LIMIT_UP: ConditionInsight(
        name="市场涨停数",
        category="Market",
        roles=[ConditionRole.RISK_FILTER],
        description="当日市场涨停家数，衡量市场活跃度和情绪温度。",
        formula="count(涨停股)",
        trigger="涨停数 >= min_count",
        parameters=[
            ParamInsight("min_count", "最少涨停数", "市场最少涨停家数", 30, 0, 200,
                         "20-30", "30-50", "30"),
        ],
        scenarios_good=["短线活跃行情确认"],
        scenarios_bad=["量化指标，需要全市场数据"],
        combinations=["强势股评分"],
        combo_model="市场情绪温度计",
        risks=["涨停数多不代表自己的票一定涨"],
        experience="涨停>50家为活跃市场，<20家为冰点。",
    ),
    ConditionIndicator.MARKET_RISK: ConditionInsight(
        name="市场风险状态",
        category="Market",
        roles=[ConditionRole.RISK_FILTER],
        description="综合指数趋势、涨跌比、波动率等判断市场风险级别。",
        formula="综合评估 = 指数趋势 + 涨跌比 + 波动率",
        trigger="风险等级 <= max_risk",
        parameters=[],
        scenarios_good=["全局风控开关"],
        scenarios_bad=["需要全市场实时数据"],
        combinations=["所有买入策略"],
        combo_model="全局风控模型",
        risks=["综合判断存在主观性"],
        experience="市场风险高时应减少仓位或停止新开仓。",
    ),
}

EXIT_INSIGHTS = {
    ConditionIndicator.TRAILING_STOP: ConditionInsight(
        name="移动止损",
        category="Exit",
        roles=[ConditionRole.EXIT_SIGNAL],
        description="从最高点回撤超过指定幅度时触发卖出。",
        formula="回撤 = (最高价 - 当前价) / 最高价 × 100",
        trigger="回撤 >= stop_pct",
        parameters=[
            ParamInsight("stop_pct", "止损幅度%", "从高点回撤多少止损", 8.0, 2, 30,
                         "5-8", "8-15-10"),
        ],
        scenarios_good=["保护利润", "控制回撤"],
        scenarios_bad=["波动大的票容易被震出"],
        combinations=["趋势未破坏"],
        combo_model="移动止损保护",
        risks=["止损过紧容易被震出", "止损过松保护不够"],
        experience="8-10%移动止损适合多数趋势股。强势股可放宽到12-15%。",
    ),
    ConditionIndicator.STOP_LOSS: ConditionInsight(
        name="固定止损",
        category="Exit",
        roles=[ConditionRole.EXIT_SIGNAL],
        description="价格跌破买入价一定幅度时无条件止损。",
        formula="亏损 = (买入价 - 当前价) / 买入价 × 100",
        trigger="亏损 >= stop_pct",
        parameters=[
            ParamInsight("stop_pct", "止损幅度%", "最大允许亏损", 5.0, 1, 20,
                         "3-5", "5-8", "5"),
        ],
        scenarios_good=["严格风控", "纪律性止损"],
        scenarios_bad=["正常回调被止损出局"],
        combinations=[],
        combo_model="固定止损模型",
        risks=["止损后可能反弹"],
        experience="固定止损是最后防线。5%止损适合短线，8%适合波段。",
    ),
    ConditionIndicator.TAKE_PROFIT: ConditionInsight(
        name="止盈目标",
        category="Exit",
        roles=[ConditionRole.EXIT_SIGNAL],
        description="盈利达到目标幅度时触发卖出。",
        formula="盈利 = (当前价 - 买入价) / 买入价 × 100",
        trigger="盈利 >= target_pct",
        parameters=[
            ParamInsight("target_pct", "目标盈利%", "止盈目标", 20.0, 5, 100,
                         "10-15", "20-30", "15-20"),
        ],
        scenarios_good=["锁定利润", "短线快进快出"],
        scenarios_bad=["可能错过大趋势"],
        combinations=["移动止损（二选一或组合）"],
        combo_model="止盈模型",
        risks=["固定止盈会截断利润"],
        experience="短线10-15%止盈，波段20-30%。趋势股建议用移动止损。",
    ),
    ConditionIndicator.MAX_HOLD_DAYS: ConditionInsight(
        name="时间止损",
        category="Exit",
        roles=[ConditionRole.EXIT_SIGNAL],
        description="持仓超过指定天数且未达到盈利目标时卖出。",
        formula="持仓天数 >= max_days 且 盈利 < min_profit",
        trigger="超时未盈利",
        parameters=[
            ParamInsight("max_days", "最大天数", "最长持仓天数", 10, 3, 60,
                         "5-10", "10-20", "10"),
            ParamInsight("min_profit", "最低盈利%", "时间止损豁免盈利", 5.0, 0, 30,
                         "3-5", "5-10", "5"),
        ],
        scenarios_good=["避免资金被长期占用", "提高资金效率"],
        scenarios_bad=["慢牛股需要耐心持有"],
        combinations=["固定止损"],
        combo_model="时间止损模型",
        risks=["可能卖在启动前"],
        experience="短线10日未达预期离场。资金效率比胜率更重要。",
    ),
}