"""Momentum 动量类条件 Insight 数据"""
from ...constant import ConditionIndicator
from ..schema import ConditionInsight, ConditionRole, ParamInsight

MOMENTUM_INSIGHTS = {
    ConditionIndicator.MACD_GOLDEN: ConditionInsight(
        name="MACD金叉",
        category="Momentum",
        roles=[ConditionRole.ENTRY_TRIGGER, ConditionRole.CONFIRMATION],
        description="MACD的DIF线从下方穿越DEA线，是经典的动量转多信号。",
        formula="DIF(today) > DEA(today) 且 DIF(yesterday) <= DEA(yesterday)",
        trigger="DIF上穿DEA",
        parameters=[
            ParamInsight("fast", "快线周期", "EMA快线周期", 12, 5, 30,
                         "12", "12", "12"),
            ParamInsight("slow", "慢线周期", "EMA慢线周期", 26, 10, 60,
                         "26", "26", "26"),
            ParamInsight("signal", "信号线", "DEA平滑周期", 9, 5, 20,
                         "9", "9", "9"),
        ],
        scenarios_good=["趋势启动确认", "底部反转信号", "回调结束"],
        scenarios_bad=["震荡行情频繁金叉死叉", "下跌中继反弹"],
        combinations=["均线多头排列", "放量上涨"],
        combo_model="动量确认趋势模型",
        risks=["震荡市金叉信号频繁且失败率高",
               "MACD是滞后指标，信号出现时可能已涨一段"],
        experience="零轴上方金叉比零轴下方更有意义。"
                   "配合趋势方向使用可大幅提高成功率。",
    ),
    ConditionIndicator.MACD_DEATH: ConditionInsight(
        name="MACD死叉",
        category="Momentum",
        roles=[ConditionRole.EXIT_SIGNAL, ConditionRole.RISK_FILTER],
        description="MACD的DIF线从上方穿越DEA线，动量转弱信号。",
        formula="DIF(today) < DEA(today) 且 DIF(yesterday) >= DEA(yesterday)",
        trigger="DIF下穿DEA",
        parameters=[
            ParamInsight("fast", "快线周期", "EMA快线周期", 12, 5, 30,
                         "12", "12", "12"),
            ParamInsight("slow", "慢线周期", "EMA慢线周期", 26, 10, 60,
                         "26", "26", "26"),
            ParamInsight("signal", "信号线", "DEA平滑周期", 9, 5, 20,
                         "9", "9", "9"),
        ],
        scenarios_good=["卖出信号", "风险过滤（不买MACD死叉的票）"],
        scenarios_bad=["强势趋势中的短暂回调"],
        combinations=["跌破均线", "放量阴线"],
        combo_model="动量衰竭卖出模型",
        risks=["强势趋势中死叉可能是假信号", "滞后性明显"],
        experience="零轴上方死叉是减仓信号。零轴下方死叉是空头确认。",
    ),
    ConditionIndicator.RSI_RANGE: ConditionInsight(
        name="RSI范围",
        category="Momentum",
        roles=[ConditionRole.RISK_FILTER, ConditionRole.ENTRY_TRIGGER],
        description="相对强弱指标，衡量价格上涨动能占比。",
        formula="RSI = 100 × avg_gain / (avg_gain + avg_loss)",
        trigger="min_rsi <= RSI <= max_rsi",
        parameters=[
            ParamInsight("period", "RSI周期", "计算周期", 14, 5, 30,
                         "6-14", "14", "14"),
            ParamInsight("min_rsi", "RSI下限", "最小RSI值", 30, 0, 100,
                         "30-40", "40-50", "30"),
            ParamInsight("max_rsi", "RSI上限", "最大RSI值", 70, 0, 100,
                         "70-80", "60-70", "70"),
        ],
        scenarios_good=["超卖反弹（RSI<30）", "过滤超买（RSI>70）"],
        scenarios_bad=["强势趋势中RSI可以持续高位"],
        combinations=["回踩MA10", "缩量阴线"],
        combo_model="超卖反弹+技术形态模型",
        risks=["强势股RSI可以长期>70不回落",
               "RSI<30不代表一定反弹"],
        experience="RSI在50以上是多头市场特征。"
                   "RSI<30后配合K线止跌信号更有效。",
    ),
    ConditionIndicator.RETURN_N_DAYS: ConditionInsight(
        name="N日收益率",
        category="Momentum",
        roles=[ConditionRole.TREND_FILTER, ConditionRole.RISK_FILTER],
        description="计算近N日累计涨跌幅，衡量动量强度。",
        formula="收益率 = (Close - Close[-N]) / Close[-N] × 100",
        trigger="收益率 >= min_return",
        parameters=[
            ParamInsight("n", "天数N", "收益率计算天数", 10, 1, 120,
                         "5-10", "10-20", "10-20"),
            ParamInsight("min_return", "最小收益(%)", "最小涨幅阈值", 5.0, -50, 100,
                         "5-10", "10-30", "5-15"),
        ],
        scenarios_good=["筛选动量股", "过滤超涨风险"],
        scenarios_bad=["动量反转的极端行情"],
        combinations=["均线多头排列", "缩量回调"],
        combo_model="动量+回调买入模型",
        risks=["过去收益不代表未来收益", "追涨风险"],
        experience="20日涨幅20-50%为强势股特征。"
                   "超过50%要警惕回调风险。",
    ),
}