"""Pullback 回调类条件 Insight 数据"""
from ...constant import ConditionIndicator
from ..schema import ConditionInsight, ConditionRole, ParamInsight

PULLBACK_INSIGHTS = {
    ConditionIndicator.PULLBACK_FROM_HIGH: ConditionInsight(
        name="从高点回撤",
        category="Pullback",
        roles=[ConditionRole.ENTRY_TRIGGER],
        description="计算当前价格与近N日最高价的回撤幅度，筛选回调到位的股票。",
        formula="回撤% = (max(High[-N:]) - Close) / max(High[-N:]) × 100",
        trigger="min_pct <= 回撤% <= max_pct",
        parameters=[
            ParamInsight("period", "回看周期", "计算最高价的回看天数", 20, 5, 60,
                         "10-20", "20-60", "20-30"),
            ParamInsight("min_pct", "最小回撤%", "最小回撤幅度", 3, 0, 30,
                         "3-5", "5-10", "3-8"),
            ParamInsight("max_pct", "最大回撤%", "最大允许回撤", 10, 1, 50,
                         "8-12", "10-20", "8-15"),
        ],
        scenarios_good=["强势股正常回调", "趋势中回撤买入"],
        scenarios_bad=["趋势破坏后的下跌", "无趋势的随机波动"],
        combinations=["均线多头排列", "缩量调整", "趋势未破坏"],
        combo_model="强势回调低吸模型",
        risks=["回撤幅度不代表已止跌", "弱势股可能继续下跌"],
        experience="强势股回撤5-10%是常见低吸区间。"
                   "超过15%的回撤需要重新评估趋势是否破坏。",
    ),
    ConditionIndicator.PULLBACK_TO_MA5: ConditionInsight(
        name="回踩MA5",
        category="Pullback",
        roles=[ConditionRole.ENTRY_TRIGGER],
        description="价格回调到5日均线附近，适合超短线强势股的快速回踩买入。",
        formula="abs(Close - MA5) / MA5 × 100",
        trigger="距离MA5 <= max_distancepct",
        parameters=[
            ParamInsight("max_distance_pct", "最大距离%", "距离MA5最大偏离",
                         1.0, 0, 5, "0.5-1", "1-2", "1-1.5"),
        ],
        scenarios_good=["超短线强势股", "连板后首次回踩", "龙头股T+1"],
        scenarios_bad=["MA5已走平或拐头", "趋势不明确"],
        combinations=["均线多头排列", "MA斜率向上"],
        combo_model="超短回踩模型",
        risks=["MA5太短，噪音大", "跌破MA5速度快，止损要果断"],
        experience="回踩MA5适合最强势的股票，一般持股1-3天。"
                   "MA5走平后回踩失效率高。",
    ),
    ConditionIndicator.PULLBACK_TO_MA10: ConditionInsight(
        name="回踩MA10",
        category="Pullback",
        roles=[ConditionRole.ENTRY_TRIGGER],
        description="价格回调到10日均线附近，经典的短线回踩买点。",
        formula="abs(Close - MA10) / MA10 × 100",
        trigger="距离MA10 <= max_distance_pct",
        parameters=[
            ParamInsight("max_distance_pct", "最大距离%", "距离MA10最大偏离",
                         2.0, 0, 8, "1-2", "2-3", "1.5-2.5"),
        ],
        scenarios_good=["短线趋势股", "首次回踩MA10", "放量后缩量回踩"],
        scenarios_bad=["MA10走平或拐头向下", "下跌趋势"],
        combinations=["缩量阴线", "均线多头排列", "趋势未破坏"],
        combo_model="缩量回踩MA10模型",
        risks=["回踩MA10不一定止跌", "需确认MA10斜率向上"],
        experience="回踩MA10是最常用的短线买点。配合缩量阴线效果最好。"
                   "首次回踩成功率高于多次回踩。",
    ),
    ConditionIndicator.PULLBACK_TO_MA20: ConditionInsight(
        name="回踩MA20",
        category="Pullback",
        roles=[ConditionRole.ENTRY_TRIGGER],
        description="价格回调到20日均线附近，中线买入点。",
        formula="abs(Close - MA20) / MA20 × 100",
        trigger="距离MA20 <= max_distance_pct",
        parameters=[
            ParamInsight("max_distance_pct", "最大距离%", "距离MA20最大偏离",
                         2.0, 0, 8, "1.5-2.5", "2-4", "2-3"),
        ],
        scenarios_good=["中线趋势股", "波段底部", "第一次回踩MA20"],
        scenarios_bad=["MA20走平或拐头", "均线粘合无方向"],
        combinations=["MA斜率向上", "缩量调整", "趋势持续天数"],
        combo_model="中线回踩低吸模型",
        risks=["MA20是中期生命线，跌破后短期难恢复",
               "横盘时MA20支撑不明显"],
        experience="MA20是中期趋势的生命线。"
                   "第一次回踩MA20且MA20斜率向上，是经典中线买点。",
    ),
    ConditionIndicator.PULLBACK_TO_MA30: ConditionInsight(
        name="回踩MA30",
        category="Pullback",
        roles=[ConditionRole.ENTRY_TRIGGER],
        description="价格回调到30日均线附近，更稳健的中线买入机会。",
        formula="abs(Close - MA30) / MA30 × 100",
        trigger="距离MA30 <= max_distance_pct",
        parameters=[
            ParamInsight("max_distance_pct", "最大距离%", "距离MA30最大偏离",
                         3.0, 0, 10, "2-3", "3-5", "2-4"),
        ],
        scenarios_good=["中线波段操作", "深度回调后企稳"],
        scenarios_bad=["趋势已破坏", "均线系统混乱"],
        combinations=["MA20斜率向上", "缩量调整"],
        combo_model="深度回调低吸模型",
        risks=["回踩MA30说明回调幅度较大，需更严格确认"],
        experience="回踩MA30一般是较深的回调，风险比MA10/MA20大。"
                   "但如果MA30仍向上，往往是较好的中线加仓点。",
    ),
    ConditionIndicator.MA_DISTANCEPCT: ConditionInsight(
        name="距离均线百分比",
        category="Pullback",
        roles=[ConditionRole.ENTRY_TRIGGER, ConditionRole.RISK_FILTER],
        description="计算收盘价与指定均线的距离百分比，通用的回踩距离条件。",
        formula="distance_pct = (Close - MA(N)) / MA(N) × 100",
        trigger="abs(distance_pct) <= max_pct",
        parameters=[
            ParamInsight("ma_period", "MA周期", "均线周期", 10, 5, 60,
                         "5-10", "10-20", "10-20"),
            ParamInsight("max_pct", "最大距离%", "最大允许偏离", 2.0, 0, 15,
                         "1-2", "2-5", "2-3"),
        ],
        scenarios_good=["精确控制回踩位置", "自定义均线回踩"],
        scenarios_bad=["均线走平时距离意义不大"],
        combinations=["MA斜率向上", "缩量调整"],
        combo_model="精确回踩模型",
        risks=["距离近不代表已止跌"],
        experience="距离MA10在2%以内是较精确的回踩位置。"
                   "配合缩量+阴线可以进一步确认。",
    ),
    ConditionIndicator.RETRACEMENT_PCT: ConditionInsight(
        name="回撤幅度",
        category="Pullback",
        roles=[ConditionRole.ENTRY_TRIGGER, ConditionRole.RISK_FILTER],
        description="从近期高点的回撤百分比，控制回调深度。",
        formula="回撤% = (High_max - Close) / High_max × 100",
        trigger="min_pct <= 回撤% <= max_pct",
        parameters=[
            ParamInsight("period", "高点回看", "计算最高价的窗口", 10, 3, 60,
                         "5-10", "10-20", "10-20"),
            ParamInsight("min_pct", "最小回撤%", "回撤下限", 3, 0, 20,
                         "3-5", "5-8", "3-5"),
            ParamInsight("max_pct", "最大回撤%", "回撤上限", 10, 1, 50,
                         "8-12", "10-15", "8-12"),
        ],
        scenarios_good=["控制回调深度", "寻找合理回撤的股票"],
        scenarios_bad=["无明确前高", "趋势破坏后"],
        combinations=["均线多头排列", "缩量调整"],
        combo_model="合理回撤买入模型",
        risks=["回撤可能继续加深"],
        experience="强势股正常回撤5-10%。超过15%需重新评估趋势健康度。",
    ),
    ConditionIndicator.FIRST_PULLBACK: ConditionInsight(
        name="首次回踩",
        category="Pullback",
        roles=[ConditionRole.ENTRY_TRIGGER],
        description="判断是否为突破或启动后的第一次回踩，首次回踩成功率最高。",
        formula="突破后首次触及MA(N)",
        trigger="前N日存在突破且当前为首次回踩",
        parameters=[
            ParamInsight("lookback", "突破回看", "检查突破的回看天数", 10, 3, 30,
                         "5-10", "10-20", "10"),
        ],
        scenarios_good=["突破后首次回踩", "涨停后首次回踩", "放量突破后"],
        scenarios_bad=["多次回踩后", "无明确突破事件"],
        combinations=["缩量调整", "回踩MA10", "趋势未破坏"],
        combo_model="突破首踩模型",
        risks=["假突破后的回踩会失败", "需确认突破有效性"],
        experience="突破后首次缩量回踩是最佳买点。"
                   "第二次、第三次回踩成功率逐步降低。",
    ),
    ConditionIndicator.SHRINK_PULLBACK: ConditionInsight(
        name="缩量回调",
        category="Pullback",
        roles=[ConditionRole.ENTRY_TRIGGER, ConditionRole.CONFIRMATION],
        description="回调过程中成交量显著萎缩，确认卖压减弱。",
        formula="volume < MA(volume, vol_period) × max_vol_ratio",
        trigger="回调日量能 < 均量 × max_vol_ratio",
        parameters=[
            ParamInsight("pullback_days", "回调天数", "回调持续的最少天数", 3, 1, 10,
                         "2-3", "3-5", "3"),
            ParamInsight("vol_period", "均量周期", "均量计算天数", 10, 3, 20,
                         "5-10", "10-20", "10"),
            ParamInsight("max_vol_ratio", "缩量比例", "缩量阈值(当日量/均量上限)", 0.7, 0.2, 1.0,
                         "0.5-0.7", "0.6-0.8", "0.6-0.7"),
        ],
        scenarios_good=["趋势中回调惜售", "洗盘确认"],
        scenarios_bad=["放量下跌", "持续缩量无买盘"],
        combinations=["回踩MA10", "阴线", "均线多头排列"],
        combo_model="缩量回调低吸模型",
        risks=["缩量不等于止跌", "空头市场中缩量无意义"],
        experience="缩量回调是经典买入条件之一。"
                   "核心逻辑：下跌无量=惜售=洗盘。必须在上升趋势中使用。",
    ),
    ConditionIndicator.YIN_PULLBACK: ConditionInsight(
        name="阴线回调",
        category="Pullback",
        roles=[ConditionRole.CONFIRMATION],
        description="回调以阴线形态呈现，确认调整性质。",
        formula="close < open (连续N根阴线)",
        trigger="最近yin_count根K线为阴线",
        parameters=[
            ParamInsight("yin_count", "阴线数", "连续阴线根数", 1, 1, 5,
                         "1-2", "1-3", "1-2"),
        ],
        scenarios_good=["温和阴线回调", "小阴线洗盘"],
        scenarios_bad=["大阴线破位", "连续大阴"],
        combinations=["缩量回调", "回踩MA10"],
        combo_model="缩量阴线回踩模型",
        risks=["大阴线可能是破位信号", "需要配合量能和幅度判断"],
        experience="1-2根小阴线缩量回调是最理想的低吸形态。"
                   "大阴线或连续3根以上阴线要警惕趋势变化。",
    ),
    ConditionIndicator.STRONG_PULLBACK_SCORE: ConditionInsight(
        name="强势回调评分",
        category="Pullback",
        roles=[ConditionRole.ENTRY_TRIGGER],
        description="综合回调幅度、量能、K线形态等计算回调质量评分。",
        formula="score = 幅度分×0.3 + 量能分×0.3 + K线分×0.2 + 位置分×0.2",
        trigger="score >= min_score",
        parameters=[
            ParamInsight("min_score", "最低评分", "触发买入的最低评分", 70, 0, 100,
                         "60-70", "70-80", "70-80"),
        ],
        scenarios_good=["综合评估回调质量", "替代多个回调条件的AND组合"],
        scenarios_bad=["需要精确控制某个维度时"],
        combinations=["均线多头排列", "趋势评分"],
        combo_model="综合回调评分模型",
        risks=["评分权重是主观设定", "不同市场环境可能需要调整"],
        experience="评分>=80为优质回调。60-80为一般回调。"
                   "评分模式比纯AND逻辑更灵活，容忍部分维度稍弱。",
    ),
}