"""Strength 强势股类条件 Insight 数据"""
from ...constant import ConditionIndicator
from ..schema import ConditionInsight, ConditionRole, ParamInsight

STRENGTH_INSIGHTS = {
    ConditionIndicator.STRENGTH_RETURN_N: ConditionInsight(
        name="N日涨幅",
        category="Strength",
        roles=[ConditionRole.TREND_FILTER],
        description="计算近N日累计涨幅，筛选阶段性强势股。",
        formula="涨幅 = (Close - Close[-N]) / Close[-N] × 100",
        trigger="涨幅 >= min_pct",
        parameters=[
            ParamInsight("n", "天数N", "计算涨幅天数", 20, 5, 120,
                         "10-20", "20-60", "20"),
            ParamInsight("min_return", "最低涨幅%", "最小涨幅要求", 20.0, 0, 200,
                         "15-30", "20-50", "15-30"),
        ],
        scenarios_good=["筛选强势股", "确认动量"],
        scenarios_bad=["追涨过高位置"],
        combinations=["缩量回调", "回踩MA10"],
        combo_model="强势股回调模型",
        risks=["涨幅过大可能面临回调", "过去涨幅不代表未来"],
        experience="20日涨幅>20%为强势特征。配合回调使用避免追高。",
    ),
    ConditionIndicator.STRENGTH_MAX_GAIN: ConditionInsight(
        name="最大涨幅",
        category="Strength",
        roles=[ConditionRole.TREND_FILTER, ConditionRole.RISK_FILTER],
        description="计算近N日内最大涨幅（从最低到最高），衡量爆发力。",
        formula="max_gain = (max(High[-N:]) - min(Low[-N:])) / min(Low[-N:]) × 100",
        trigger="max_gain >= threshold",
        parameters=[
            ParamInsight("period", "天数", "回看天数", 20, 5, 60,
                         "10-20", "20-60", "20"),
        ],
        scenarios_good=["确认有爆发力", "选择活跃度高的票"],
        scenarios_bad=["最大涨幅过高可能已到末期"],
        combinations=["从高点回撤", "缩量回调"],
        combo_model="强势回调模型",
        risks=["最大涨幅过大说明波动大，风险也高"],
        experience="最大涨幅30-50%且目前回调10%以内是较好的回调标的。",
    ),
    ConditionIndicator.STRENGTH_STAGE_HIGH: ConditionInsight(
        name="阶段新高",
        category="Strength",
        roles=[ConditionRole.CONFIRMATION],
        description="判断当前价格是否接近或创出近N日新高。",
        formula="Close >= max(High[-N:]) × (1 - tolerance)",
        trigger="价格接近或突破阶段高点",
        parameters=[
            ParamInsight("period", "天数", "阶段回看天数", 60, 10, 250,
                         "20-60", "60-120", "60"),
        ],
        scenarios_good=["突破确认", "强势股筛选"],
        scenarios_bad=["远离高点时不满足"],
        combinations=["放量上涨", "均线多头排列"],
        combo_model="突破新高模型",
        risks=["新高后可能获利盘涌出"],
        experience="创60日新高是中期突破信号，配合量能确认更可靠。",
    ),
    ConditionIndicator.STRENGTH_LIMIT_UP_COUNT: ConditionInsight(
        name="涨停次数",
        category="Strength",
        roles=[ConditionRole.TREND_FILTER],
        description="统计近N日内涨停板次数，衡量题材活跃度。",
        formula="count(涨幅 >= 9.5%, last N days)",
        trigger="涨停次数 >= min_count",
        parameters=[
            ParamInsight("n", "天数N", "统计窗口", 20, 5, 60,
                         "10-20", "20", "20"),
            ParamInsight("min_count", "最少次数", "最少涨停次数", 1, 1, 10,
                         "1-2", "1", "1"),
        ],
        scenarios_good=["筛选题材股", "确认资金关注度"],
        scenarios_bad=["追涨停风险"],
        combinations=["缩量回调", "回踩MA10"],
        combo_model="涨停股首阴低吸模型",
        risks=["涨停股波动大", "可能有监管风险"],
        experience="近20日有涨停说明有题材和资金驱动。"
                   "涨停后首次缩量回踩是经典接力买点。",
    ),
    ConditionIndicator.STRENGTH_BIG_YANG_COUNT: ConditionInsight(
        name="大阳线次数",
        category="Strength",
        roles=[ConditionRole.TREND_FILTER],
        description="统计近N日内大阳线（涨幅>5%）次数。",
        formula="count(涨幅 >= min_pct%, last N days)",
        trigger="大阳线次数 >= min_count",
        parameters=[
            ParamInsight("n", "天数N", "统计窗口", 20, 5, 60,
                         "10-20", "20", "20"),
            ParamInsight("min_count", "最少次数", "最少大阳次数", 2, 1, 10,
                         "2-3", "2", "2"),
            ParamInsight("min_pct", "大阳定义%", "大阳线最小涨幅", 5.0, 1, 15,
                         "5", "5-7", "5"),
        ],
        scenarios_good=["确认多方力量强劲", "筛选活跃股"],
        scenarios_bad=["大阳过多可能已到高位"],
        combinations=["缩量回调", "均线多头排列"],
        combo_model="强势股筛选模型",
        risks=["大阳线过多说明波动大"],
        experience="20日内2-3根大阳线说明多方力量活跃。",
    ),
    ConditionIndicator.STRENGTH_VOL_BREAK: ConditionInsight(
        name="放量突破",
        category="Strength",
        roles=[ConditionRole.ENTRY_TRIGGER],
        description="价格突破前高且成交量显著放大，经典突破信号。",
        formula="High > max(High[-N:]) 且 volume > MA(vol,5) × ratio",
        trigger="价格新高 + 量能放大",
        parameters=[
            ParamInsight("n", "回看天数", "前高回看窗口", 20, 5, 60,
                         "10-20", "20-60", "20"),
        ],
        scenarios_good=["平台突破", "趋势加速启动"],
        scenarios_bad=["假突破风险", "高位突破"],
        combinations=["均线多头排列", "均粘合"],
        combo_model="放量突破模型",
        risks=["假突破风险高，需观察突破后能否站稳",
               "追突破需设置止损"],
        experience="量能>=1.5倍的突破更可靠。"
                   "突破后缩量回踩不破前高是最佳加仓点。",
    ),
    ConditionIndicator.STRENGTH_SCORE: ConditionInsight(
        name="强势股评分",
        category="Strength",
        roles=[ConditionRole.TREND_FILTER],
        description="综合涨幅、涨停次数、大阳线等计算强势度评分。",
        formula="加权评分 = 涨幅得分 + 涨停得分 + 大阳得分 + ...",
        trigger="评分 >= min_score",
        parameters=[
            ParamInsight("n", "天数N", "评分统计窗口", 20, 5, 60,
                         "10-20", "20", "20"),
        ],
        scenarios_good=["快速筛选强势股池"],
        scenarios_bad=["需精确控制单一强度指标时"],
        combinations=["缩量回调", "回踩MA10"],
        combo_model="强势股评分+回调模型",
        risks=["评分标准需持续优化"],
        experience="强势评分>80的票活跃度高，适合短线操作。",
    ),
}