"""Trend 趋势类条件 Insight 数据"""
from ...constant import ConditionIndicator
from ..schema import ConditionInsight, ConditionRole, ParamInsight

TREND_INSIGHTS = {
    ConditionIndicator.MA_SLOPE: ConditionInsight(
        name="MA斜率向上",
        category="Trend",
        roles=[ConditionRole.TREND_FILTER, ConditionRole.CONFIRMATION],
        description="判断指定周期均线的斜率是否为正，确认价格趋势方向向上。",
        formula="MA_slope = MA(today) - MA(N日前)",
        trigger="MA_slope > min_slope",
        parameters=[
            ParamInsight("ma_period", "MA周期", "均线计算周期", 20, 5, 120,
                         "5-10", "20-60", "10-30"),
            ParamInsight("slope_window", "斜率窗口", "比较间隔天数", 10, 1, 30,
                         "3-5", "5-10", "5-10"),
            ParamInsight("min_slope", "最小斜率", "斜率阈值(0=向上即可)", 0.0, 0, 5,
                         "0", "0", "0"),
        ],
        scenarios_good=["趋势启动确认", "均线拐头向上", "底部反转初期"],
        scenarios_bad=["横盘震荡期", "急涨末期均线钝化"],
        combinations=["均线多头排列", "价格站上均线", "缩量回调"],
        combo_model="趋势跟踪模型",
        risks=["均线是滞后指标，趋势反转初期可能误判",
               "短周期均线噪音大，长周期反应慢"],
        experience="MA20斜率向上是中期趋势最基本的确认信号。"
                   "建议配合价格站上均线一起使用，双重确认。",
    ),
    ConditionIndicator.WEEKLY_MA_SLOPE: ConditionInsight(
        name="13周均线向上",
        category="Trend",
        roles=[ConditionRole.TREND_FILTER],
        description="周线级别均线斜率向上，确认中期（季度级别）趋势方向。",
        formula="Weekly_MA(13).slope > 0",
        trigger="周线MA斜率 > 0",
        parameters=[
            ParamInsight("ma_period", "周线MA周期", "周线均线周期", 13, 5, 52,
                         "5-8周", "13-26周", "13-20周"),
            ParamInsight("slope_window", "斜率回看", "比较间隔周数", 5, 1, 13,
                         "3", "5", "5"),
            ParamInsight("min_slope", "最小斜率", "斜率阈值(0=向上即可)", 0.0, 0, 5,
                         "0", "0", "0"),
        ],
        scenarios_good=["中线持股策略", "波段底部确认", "过滤短期噪音"],
        scenarios_bad=["超短线策略", "快速轮动行情"],
        combinations=["日线回踩MA10", "日线缩量阴线"],
        combo_model="周线趋势+日线择时模型",
        risks=["周线级别信号滞后较大，约1-2周延迟",
               "不适合快节奏短线交易"],
        experience="13周约一个季度，是机构常用的中期趋势判断周期。"
                   "周线向上+日线回踩是经典的中线买入时机。",
    ),
    ConditionIndicator.MA_ALIGNMENT: ConditionInsight(
        name="均线多头排列",
        category="Trend",
        roles=[ConditionRole.TREND_FILTER, ConditionRole.CONFIRMATION],
        description="判断多条均线呈现多头排列（短期在上、长期在下），确认强势上升趋势。",
        formula="MA5 > MA10 > MA20 > MA30",
        trigger="所有相邻均线严格递减排列",
        parameters=[
            ParamInsight("periods", "均线列表", "参与排列判断的均线周期",
                         [5, 10, 20, 60], None, None,
                         "[5,10,20]", "[5,10,20,30,60]", "[10,20,30]"),
            ParamInsight("max_gap_pct", "间距上限%", "相邻均线最大允许间距(0=不限)",
                         0.0, 0, 10, "0", "3-5", "0"),
        ],
        scenarios_good=["强势上涨趋势", "趋势确认后追涨", "排除震荡票"],
        scenarios_bad=["震荡市中很难满足", "刚启动的趋势（均线尚未完全排列）"],
        combinations=["价格站上均线", "缩量回调", "放量突破"],
        combo_model="强势趋势跟踪模型",
        risks=["多头排列形成时往往已涨了一段，追高风险",
               "均线发散过大时趋势可能接近尾声"],
        experience="MA5>MA10>MA20>MA30是经典多头排列。"
                   "加入MA60可以更严格过滤，但满足条件的票更少。"
                   "建议配合max_gap_pct限制间距，避免选入过度发散的票。",
    ),
    ConditionIndicator.TREND_STRENGTH: ConditionInsight(
        name="均线趋势强度",
        category="Trend",
        roles=[ConditionRole.TREND_FILTER],
        description="综合均线排列、斜率、价格相对位置，计算趋势强度评分(0-100)。",
        formula="score = 排列得分×0.4 + 斜率得分×0.3 + 位置得分×0.3",
        trigger="score >= 阈值",
        parameters=[
            ParamInsight("periods", "均线列表", "评估用均线周期",
                         [5, 10, 20, 30], None, None,
                         "[5,10,20]", "[5,10,20,30]", "[10,20,30]"),
        ],
        scenarios_good=["量化趋势质量", "替代多个趋势条件的AND组合"],
        scenarios_bad=["需要精确控制单一趋势指标时"],
        combinations=["回踩MA10", "缩量阴线"],
        combo_model="趋势评分+择时模型",
        risks=["评分体系是主观权重，不同市场可能需要调整"],
        experience="80分以上为强趋势，60-80中等。"
                   "评分模式比纯AND逻辑更灵活，允许部分维度稍弱。",
    ),
    ConditionIndicator.PRICE_ABOVE_MA: ConditionInsight(
        name="价格站上均线",
        category="Trend",
        roles=[ConditionRole.TREND_FILTER],
        description="判断当日收盘价在指定均线上方，最基础的趋势方向确认。",
        formula="Close > MA(N)",
        trigger="收盘价 > N日均线",
        parameters=[
            ParamInsight("ma_period", "MA周期", "均线周期", 20, 5, 120,
                         "5-10", "20-60", "10-30"),
        ],
        scenarios_good=["趋势方向基本确认", "配合其他条件使用"],
        scenarios_bad=["单独使用信号太弱", "均线附近频繁穿越时"],
        combinations=["MA斜率向上", "均线多头排列"],
        combo_model="多重趋势确认模型",
        risks=["均线附近频繁穿越会产生大量假信号",
               "建议配合斜率或持续天数过滤"],
        experience="Close>MA20是最常用的中期趋势判断。"
                   "单独使用噪音大，建议至少配合一个斜率或排列条件。",
    ),
    ConditionIndicator.TREND_DAYS: ConditionInsight(
        name="趋势持续天数",
        category="Trend",
        roles=[ConditionRole.TREND_FILTER],
        description="统计价格连续站上均线的天数，过滤刚突破的弱信号。",
        formula="count(连续 Close > MA(N)的天数)",
        trigger="持续天数 >= min_days",
        parameters=[
            ParamInsight("ma_period", "MA周期", "均线周期", 20, 5, 60,
                         "5-10", "20", "20"),
            ParamInsight("min_days", "最少天数", "连续站上的最少天数", 5, 1, 60,
                         "3-5", "5-10", "5-10"),
        ],
        scenarios_good=["过滤假突破", "确认趋势已建立"],
        scenarios_bad=["趋势刚启动时无法满足"],
        combinations=["价格站上均线", "均线多头排列"],
        combo_model="趋势成熟度过滤",
        risks=["天数要求越高，入场越晚，可能错过启动段"],
        experience="连续5天站上MA20基本可以确认趋势建立。配合斜率向上使用效果更好。",
    ),
    ConditionIndicator.TREND_INTACT: ConditionInsight(
        name="趋势未破坏",
        category="Trend",
        roles=[ConditionRole.TREND_FILTER, ConditionRole.RISK_FILTER],
        description="判断近期最低价未跌破指定均线，确认趋势完整性。",
        formula="min(Low[-N:]) > MA(period)",
        trigger="近N日最低价 > 均线",
        parameters=[
            ParamInsight("ma_period", "MA周期", "保护均线", 20, 5, 60,
                         "10", "20", "20-30"),
        ],
        scenarios_good=["趋势健康度确认", "回调后判断是否仍在趋势中"],
        scenarios_bad=["趋势转折初期"],
        combinations=["回踩MA10", "缩量回调"],
        combo_model="趋势保护回调买入",
        risks=["影线刺穿均线不一定代表趋势破坏",
               "需要根据品种波动调整容忍度"],
        experience="趋势未破坏是回调策略的前提条件。"
                   "如果低点已经跌破MA20，回调买入的风险显著上升。",
    ),
    ConditionIndicator.MA_BINDONG: ConditionInsight(
        name="均线粘合",
        category="Trend",
        roles=[ConditionRole.CONFIRMATION],
        description="多条均线距离极小，筹码高度集中，即将选择突破方向。",
        formula="(max(MA_list) - min(MA_list)) / avg(MA_list) < threshold",
        trigger="均线离散度 < max_gap_pct",
        parameters=[
            ParamInsight("periods", "均线列表", "参与判断的均线",
                         [5, 10, 20], None, None, "", "", ""),
            ParamInsight("max_spreadpct", "粘合阈值%", "最大允许离散度",
                         2.0, 0.5, 5.0, "1.5-2", "2-3", "2-3"),
        ],
        scenarios_good=["突破前夕选股", "长期整理末期"],
        scenarios_bad=["趋势已经明确时", "快速下跌中"],
        combinations=["放量突破", "N日新高"],
        combo_model="粘合突破模型",
        risks=["粘合后突破方向不确定，可能向下",
               "需要配合量能确认突破方向"],
        experience="均线粘合是变盘前兆。配合放量阳线突破确认方向。"
                   "单纯粘合不是买入信号，必须等待方向选择。",
    ),
    ConditionIndicator.TREND_SCORE: ConditionInsight(
        name="趋势综合评分",
        category="Trend",
        roles=[ConditionRole.TREND_FILTER],
        description="综合多个趋势因子计算评分(0-100)，替代多个趋势条件的AND组合。",
        formula="加权评分 = Σ(各趋势因子得分 × 权重)",
        trigger="总评分 >= min_score",
        parameters=[],
        scenarios_good=["快速筛选趋势股", "容忍部分条件不满足"],
        scenarios_bad=["需要严格趋势确认时"],
        combinations=["回踩MA10", "缩量阴线", "放量突破"],
        combo_model="趋势评分择时模型",
        risks=["评分标准是静态的，极端行情可能失效"],
        experience="评分模式比AND更灵活。80分以上=强趋势，适合激进策略。"
                   "60-80分=中等趋势，适合稳健策略。",
    ),
    ConditionIndicator.NEW_HIGH_N: ConditionInsight(
        name="N日新高突破",
        category="Trend",
        roles=[ConditionRole.ENTRY_TRIGGER],
        description="判断今日最高价创近N日新高，经典突破买入信号。",
        formula="High(today) >= max(High[-N:])",
        trigger="今日最高价 = N日内最高",
        parameters=[
            ParamInsight("n", "回看天数", "新高回看窗口", 20, 5, 250,
                         "10-20", "20-60", "20-60"),
        ],
        scenarios_good=["突破买入", "趋势启动", "平台整理后突破"],
        scenarios_bad=["连续新高末期", "缩量假突破"],
        combinations=["放量上涨", "均线多头排列"],
        combo_model="放量突破模型",
        risks=["假突破风险高，必须配合量能确认",
               "追高买入需要严格止损保护"],
        experience="20日新高是短线突破标准。60日新高更可靠但机会更少。"
                   "突破时量能至少1.5倍以上才有效。",
    ),
}