"""Volume 成交量类条件 Insight 数据"""
from ...constant import ConditionIndicator
from ..schema import ConditionInsight, ConditionRole, ParamInsight

VOLUME_INSIGHTS = {
    ConditionIndicator.VOLUME_PRICE_UP: ConditionInsight(
        name="放量上涨",
        category="Volume",
        roles=[ConditionRole.CONFIRMATION],
        description="识别价格上涨过程中成交量同步放大，确认上涨有资金支持。",
        formula="volume / MA(volume, N)",
        trigger="量比 >= min_ratio 且 涨幅 >= min_chg",
        parameters=[
            ParamInsight("period", "计算周期", "均量计算天数", 20, 5, 60,
                         "5-10", "20", "10-20"),
            ParamInsight("min_ratio", "量比下限", "成交量放大倍数", 1.5, 1.0, 5.0,
                         "1.5-2", "2-3", "1.2-1.8"),
            ParamInsight("min_chg", "涨幅下限%", "最小涨幅要求", 1.0, 0, 10,
                         "1-3", "1-2", "0.5-1.5"),
        ],
        scenarios_good=["突破阶段确认", "强势股启动", "趋势延续确认"],
        scenarios_bad=["高位巨量（可能出货）", "连续上涨末期"],
        combinations=["均线多头排列", "缩量回调", "回踩MA10"],
        combo_model="强势股缩量回调模型",
        risks=["高位放量可能是资金派发", "连续放量后警惕衰竭"],
        experience="第一次放量突破后缩量回踩，通常风险收益比更优。"
                   "量比1.5-2倍是温和放量，>3倍为巨量需谨慎。",
    ),
    ConditionIndicator.VOLUME_RATIO: ConditionInsight(
        name="量比过滤",
        category="Volume",
        roles=[ConditionRole.CONFIRMATION, ConditionRole.RISK_FILTER],
        description="当日成交量与N日均量的比值，衡量当日交投活跃度。",
        formula="量比 = volume / MA(volume, N)",
        trigger="量比 >= min_ratio",
        parameters=[
            ParamInsight("period", "均量周期", "均量计算天数", 20, 3, 60,
                         "5", "10-20", "5-10"),
            ParamInsight("min_ratio", "最低量比", "量比下限", 1.5, 0, 5,
                         "1.0-1.5", "1.5-2", "1.5"),
        ],
        scenarios_good=["过滤地量无人关注票", "过滤异常巨量票"],
        scenarios_bad=["IPO新股波动期", "重大事件日"],
        combinations=["缩量阴线", "回踩MA10"],
        combo_model="量能状态过滤",
        risks=["量比异常高要警惕利好出尽或出货"],
        experience="量比<0.5属于极度缩量（无人关注）。"
                   "量比>5属于极端放量（可能异常波动）。",
    ),
    ConditionIndicator.VOLUME_SHRINK: ConditionInsight(
        name="缩量调整",
        category="Volume",
        roles=[ConditionRole.CONFIRMATION, ConditionRole.ENTRY_TRIGGER],
        description="回调时成交量萎缩，表明卖压减弱、筹码惜售。",
        formula="volume < MA(volume, N) × max_ratio",
        trigger="量比 < max_ratio",
        parameters=[
            ParamInsight("period", "均量周期", "均量计算天数", 20, 3, 60,
                         "5-10", "20", "10-20"),
            ParamInsight("max_ratio", "缩量比例", "低于均量的比例上限", 0.7, 0.2, 1.0,
                         "0.5-0.7", "0.6-0.8", "0.5-0.7"),
        ],
        scenarios_good=["强势股回调惜售", "趋势中缩量洗盘"],
        scenarios_bad=["持续下跌缩量（无买盘）", "地量后继续下跌"],
        combinations=["阴线", "回踩MA10", "均线多头排列"],
        combo_model="缩量回调低吸模型",
        risks=["缩量不一定止跌，只是卖压减弱",
               "空头趋势中缩量可能是无人接盘"],
        experience="缩量回调的核心逻辑：下跌无卖压=惜售。"
                   "必须在上升趋势中使用，空头趋势中缩量意义不同。",
    ),
    ConditionIndicator.VOLUME_LAYER: ConditionInsight(
        name="分层量能",
        category="Volume",
        roles=[ConditionRole.CONFIRMATION],
        description="对比上涨阶段和调整阶段的平均成交量，判断量价结构健康度。",
        formula="调整量均 / 上涨量均",
        trigger="调整量 < 上涨量 × max_ratio",
        parameters=[
            ParamInsight("up_window", "上涨窗口", "上涨阶段回看天数", 10, 3, 30,
                         "5-10", "10-20", "10"),
            ParamInsight("dn_window", "调整窗口", "调整阶段回看天数", 5, 2, 20,
                         "3-5", "5-10", "5"),
            ParamInsight("max_ratio", "量能比阈值", "调整量/上涨量的最大比例",
                         0.6, 0.2, 1.0, "0.5-0.7", "0.6", "0.5-0.7"),
        ],
        scenarios_good=["确认量价结构健康", "判断回调是洗盘还是出货"],
        scenarios_bad=["震荡行情量能无序"],
        combinations=["均线多头排列", "缩量阴线"],
        combo_model="量价结构健康度模型",
        risks=["需要足够历史数据区分上涨/调整阶段"],
        experience="上涨放量+调整缩量=量价配合良好。"
                   "如果调整阶段量能接近上涨阶段，可能是出货行为。",
    ),
    ConditionIndicator.VOLUME_UP_PHASE: ConditionInsight(
        name="上涨阶段量能",
        category="Volume",
        roles=[ConditionRole.CONFIRMATION],
        description="统计上涨阶段的平均成交量，确认上涨有持续资金推动。",
        formula="avg(volume where close > open, last N days)",
        trigger="上涨日均量 >= 总均量 × min_ratio",
        parameters=[
            ParamInsight("n", "计算周期", "回看天数", 20, 5, 60,
                         "10-20", "20", "10-20"),
            ParamInsight("min_ratio", "放量比例", "上涨日均量/总均量", 1.3, 1.0, 3.0,
                         "1.2-1.5", "1.5-2", "1.2-1.5"),
        ],
        scenarios_good=["确认上涨有资金支持", "排除无量空涨"],
        scenarios_bad=["量能不规则的个股"],
        combinations=["缩量调整", "均线多头排列"],
        combo_model="量价配合趋势模型",
        risks=["短期数据量不足时统计不准确"],
        experience="上涨日放量、调整日缩量是最健康的量价结构。",
    ),
    ConditionIndicator.VOLUME_TREND: ConditionInsight(
        name="成交量趋势",
        category="Volume",
        roles=[ConditionRole.CONFIRMATION],
        description="判断成交量整体趋势方向（温和放大或持续萎缩）。",
        formula="MA(volume, short) vs MA(volume, long)",
        trigger="短期均量 > 长期均量 × ratio",
        parameters=[
            ParamInsight("short_period", "短均量", "短期均量周期", 5, 3, 20,
                         "5", "5-10", "5"),
            ParamInsight("long_period", "长均量", "长期均量周期", 20, 10, 60,
                         "20", "20-60", "20"),
        ],
        scenarios_good=["量能逐步放大", "筹码活跃度上升"],
        scenarios_bad=["突然巨量（非趋势性放量）"],
        combinations=["MA斜率向上", "均线多头排列"],
        combo_model="量价共振模型",
        risks=["量能趋势的变化比价格趋势更快，可能提前结束"],
        experience="量在价先——成交量先于价格放大往往是趋势启动信号。",
    ),
    ConditionIndicator.FUND_INTENSITY: ConditionInsight(
        name="资金介入强度",
        category="Volume",
        roles=[ConditionRole.CONFIRMATION],
        description="综合量能水平和价格表现估算资金介入程度。",
        formula="(上涨量 - 下跌量) / 总量 × 振幅",
        trigger="资金强度 >= min_score",
        parameters=[
            ParamInsight("n", "计算周期", "统计天数", 10, 3, 30,
                         "5-10", "10-20", "10"),
            ParamInsight("min_score", "最低评分", "资金强度阈值", 0.5, 0, 1.0,
                         "0.3-0.5", "0.5-0.7", "0.5"),
        ],
        scenarios_good=["主力资金进场确认", "底部放量启动"],
        scenarios_bad=["高位放量（可能出货）"],
        combinations=["均线多头排列", "N日新高"],
        combo_model="资金驱动突破模型",
        risks=["无法区分买入和卖出资金方向", "只是估算"],
        experience="资金强度上升+趋势向上=主力积极做多。"
                   "资金强度是辅助指标，不能单独作为买入依据。",
    ),
}