from pathlib import Path
import py_compile

p = Path(r"C:\Users\11229\Documents\GitHub\vnpy\vnpy\app\batch_research\ui\stock_pool_editor.py")
src = p.read_text(encoding="utf-8")

part5 = (
    '    # ---- event handlers -----------------------------------\n'
    '\n'
    '    def _on_input_enter(self) -> None:\n'
    '        text = self._input_edit.text().strip()\n'
    '        if not text:\n'
    '            return\n'
    '        symbols = self._parser.parse(text)\n'
    '        if symbols:\n'
    '            added = self.add_symbols(symbols)\n'
    '            if added:\n'
    '                self._input_edit.clear()\n'
    '            else:\n'
    '                self._input_edit.selectAll()\n'
    '        else:\n'
    '            self._input_edit.setStyleSheet("border: 1px solid #FF5555;")\n'
    '            QtCore.QTimer.singleShot(\n'
    '                800, lambda: self._input_edit.setStyleSheet("")\n'
    '            )\n'
    '\n'
    '    def _on_paste_clipboard(self) -> None:\n'
    '        text = QtWidgets.QApplication.clipboard().text()\n'
    '        if not text.strip():\n'
    '            return\n'
    '        symbols = self._parser.parse(text)\n'
    '        if not symbols:\n'
    '            QtWidgets.QMessageBox.information(\n'
    '                self, "\u7c98\u8d34\u7ed3\u679c",\n'
    '                "\u672a\u80fd\u8bc6\u522b\u5230\u6709\u6548\u80a1\u7968\u4ee3\u7801\u3002\n\n"\n'
    '                "\u652f\u6301\u683c\u5f0f\uff1a6\u4f4d\u4ee3\u7801\u3001vt_symbol\u3001Tushare \u683c\u5f0f"\n'
    '            )\n'
    '            return\n'
    '        added   = self.add_symbols(symbols)\n'
    '        skipped = len(symbols) - added\n'
    '        msg = f"\u8bc6\u522b\u5230 {len(symbols)} \u4e2a\u4ee3\u7801\uff0c\u65b0\u589e {added} \u4e2a"\n'
    '        if skipped:\n'
    '            msg += f"\uff0c\u8df3\u8fc7\u91cd\u590d {skipped} \u4e2a"\n'
    '        self._counter_label.setText(msg)\n'
    '        QtCore.QTimer.singleShot(3000, self._update_counter)\n'
    '\n'
    '    def _on_sort(self) -> None:\n'
    '        self._load_rows(sorted(self.get_symbols()))\n'
    '\n'
    '    def _on_dedup(self) -> None:\n'
    '        seen: set[str] = set()\n'
    '        unique: list[str] = []\n'
    '        for s in self.get_symbols():\n'
    '            if s not in seen:\n'
    '                seen.add(s)\n'
    '                unique.append(s)\n'
    '        self._load_rows(unique)\n'
    '\n'
    '    def _on_clear(self) -> None:\n'
    '        n = self._table.rowCount()\n'
    '        if n == 0:\n'
    '            return\n'
    '        reply = QtWidgets.QMessageBox.question(\n'
    '            self, "\u786e\u8ba4\u6e05\u7a7a",\n'
    '            f"\u786e\u5b9a\u8981\u6e05\u7a7a\u5168\u90e8 {n} \u53ea\u80a1\u7968\u5417\uff1f",\n'
    '            QtWidgets.QMessageBox.StandardButton.Yes\n'
    '            | QtWidgets.QMessageBox.StandardButton.No,\n'
    '            QtWidgets.QMessageBox.StandardButton.No,\n'
    '        )\n'
    '        if reply == QtWidgets.QMessageBox.StandardButton.Yes:\n'
    '            self.clear()\n'
    '\n'
    '    def _on_double_click(self, index: QtCore.QModelIndex) -> None:\n'
    '        row = index.row()\n'
    '        self._table.removeRow(row)\n'
    '        self._renumber()\n'
    '        self._update_counter()\n'
    '        self.symbols_changed.emit(self.get_symbols())\n'
    '\n'
    '    def _table_key_press(self, event: QtGui.QKeyEvent) -> None:\n'
    '        if event.key() in (\n'
    '            QtCore.Qt.Key.Key_Delete, QtCore.Qt.Key.Key_Backspace\n'
    '        ):\n'
    '            self._delete_selected()\n'
    '        else:\n'
    '            QtWidgets.QTableWidget.keyPressEvent(self._table, event)\n'
    '\n'
    '    def _delete_selected(self) -> None:\n'
    '        rows = sorted(\n'
    '            {idx.row() for idx in self._table.selectedIndexes()},\n'
    '            reverse=True,\n'
    '        )\n'
    '        for row in rows:\n'
    '            self._table.removeRow(row)\n'
    '        if rows:\n'
    '            self._renumber()\n'
    '            self._update_counter()\n'
    '            self.symbols_changed.emit(self.get_symbols())\n'
    '\n'
    '    def _copy_selected(self) -> None:\n'
    '        rows = sorted({idx.row() for idx in self._table.selectedIndexes()})\n'
    '        lines = []\n'
    '        for row in rows:\n'
    '            item = self._table.item(row, _COL_SYMBOL)\n'
    '            if item:\n'
    '                lines.append(item.text())\n'
    '        if lines:\n'
    '            QtWidgets.QApplication.clipboard().setText("\\n".join(lines))\n'
    '\n'
    '    def _show_context_menu(self, pos: QtCore.QPoint) -> None:\n'
    '        self._ctx_menu.exec_(self._table.mapToGlobal(pos))\n'
    '\n'
    '    def keyPressEvent(self, event: QtGui.QKeyEvent) -> None:\n'
    '        ctrl = QtCore.Qt.KeyboardModifier.ControlModifier\n'
    '        if event.key() == QtCore.Qt.Key.Key_V and event.modifiers() == ctrl:\n'
    '            self._on_paste_clipboard()\n'
    '        elif event.key() == QtCore.Qt.Key.Key_A and event.modifiers() == ctrl:\n'
    '            self._table.selectAll()\n'
    '        else:\n'
    '            super().keyPressEvent(event)\n'
)

p.write_text(src + part5, encoding="utf-8")
total_lines = len((src + part5).splitlines())
print(f"part5 ok: {total_lines} total lines")

py_compile.compile(str(p), doraise=True)
print("syntax OK: stock_pool_editor.py")
