from pathlib import Path

p = Path(r"C:\Users\11229\Documents\GitHub\vnpy\vnpy\app\batch_research\ui\stock_pool_editor.py")
src = p.read_text(encoding="utf-8")

lines = [
    '    # ---- UI construction ----------------------------------',
    '',
    '    def _init_ui(self) -> None:',
    '        self._input_edit = QtWidgets.QLineEdit()',
    '        self._input_edit.setPlaceholderText(',
    '            "\u8f93\u5165\u4ee3\u7801\u540e\u6309 Enter \u6dfb\u52a0\uff0c\u652f\u6301\u9017\u53f7/\u7a7a\u683c\u5206\u9694\u591a\u4e2a"',
    '        )',
    '        self._input_edit.returnPressed.connect(self._on_input_enter)',
    '',
    '        btn_paste = QtWidgets.QPushButton("\u7c98\u8d34")',
    '        btn_sort  = QtWidgets.QPushButton("\u6392\u5e8f")',
    '        btn_dedup = QtWidgets.QPushButton("\u53bb\u91cd")',
    '        btn_clear = QtWidgets.QPushButton("\u6e05\u7a7a")',
    '        btn_paste.setToolTip("\u4ece\u526a\u8d34\u677f\u6279\u91cf\u7c98\u8d34\uff08Excel/CSV/\u540c\u82b1\u987a/Tushare\uff09")',
    '        btn_paste.clicked.connect(self._on_paste_clipboard)',
    '        btn_sort.clicked.connect(self._on_sort)',
    '        btn_dedup.clicked.connect(self._on_dedup)',
    '        btn_clear.clicked.connect(self._on_clear)',
    '',
    '        toolbar = QtWidgets.QHBoxLayout()',
    '        toolbar.setSpacing(6)',
    '        toolbar.addWidget(self._input_edit, 1)',
    '        for btn in (btn_paste, btn_sort, btn_dedup, btn_clear):',
    '            toolbar.addWidget(btn)',
    '',
    '        self._table = QtWidgets.QTableWidget(0, 2)',
    '        self._table.setHorizontalHeaderLabels(["\u5e8f\u53f7", "\u80a1\u7968\u4ee3\u7801 (vt_symbol)"])',
    '        hh = self._table.horizontalHeader()',
    '        hh.setSectionResizeMode(_COL_IDX,    QtWidgets.QHeaderView.ResizeMode.Fixed)',
    '        hh.setSectionResizeMode(_COL_SYMBOL, QtWidgets.QHeaderView.ResizeMode.Stretch)',
    '        self._table.setColumnWidth(_COL_IDX, 52)',
    '        self._table.verticalHeader().setVisible(False)',
    '        self._table.setEditTriggers(',
    '            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)',
    '        self._table.setSelectionBehavior(',
    '            QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)',
    '        self._table.setSelectionMode(',
    '            QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)',
    '        self._table.setStyleSheet(_STYLE_TABLE)',
    '        self._table.setAlternatingRowColors(False)',
    '        self._table.verticalHeader().setDefaultSectionSize(26)',
    '        self._table.doubleClicked.connect(self._on_double_click)',
    '        self._table.keyPressEvent = self._table_key_press  # type: ignore',
    '',
    '        self._counter_label = QtWidgets.QLabel("\u5171 0 \u53ea\u80a1\u7968")',
    '        self._counter_label.setStyleSheet(_STYLE_COUNTER)',
    '        hint = QtWidgets.QLabel(',
    '            "\u63d0\u793a\uff1a\u53ef\u76f4\u63a5\u7c98\u8d34 Excel/CSV/\u540c\u82b1\u987a/Tushare\uff1b\u53cc\u51fb\u884c\u53ef\u5220\u9664"',
    '        )',
    '        hint.setStyleSheet(_STYLE_HINT)',
    '',
    '        status_row = QtWidgets.QHBoxLayout()',
    '        status_row.addWidget(self._counter_label)',
    '        status_row.addStretch()',
    '        status_row.addWidget(hint)',
    '',
    '        vbox = QtWidgets.QVBoxLayout(self)',
    '        vbox.setContentsMargins(0, 0, 0, 0)',
    '        vbox.setSpacing(6)',
    '        vbox.addLayout(toolbar)',
    '        vbox.addWidget(self._table, 1)',
    '        vbox.addLayout(status_row)',
    '',
]

p.write_text(src + "\n".join(lines) + "\n", encoding="utf-8")
print("part B written, total lines:", len((src + "\n".join(lines)).splitlines()))
