"""
system_console/__init__.py
"""
from .app    import SystemConsoleApp
from .engine import SystemConsoleEngine
from .constant import (
    APP_NAME, MODULE_REGISTRY, MODULE_KEYS,
    ModuleState, ConsoleStatus, SystemLayer,
)
from .event import (
    EVENT_CONSOLE_STARTED, EVENT_CONSOLE_STOPPED,
    EVENT_MODULE_STARTING, EVENT_MODULE_STARTED,
    EVENT_MODULE_STOPPING, EVENT_MODULE_STOPPED,
    EVENT_MODULE_ERROR, EVENT_MODULE_STATE_CHANGED,
    EVENT_SYSTEM_STATE_UPDATED, EVENT_ALL_STARTED,
    EVENT_ALL_STOPPED, EVENT_DASHBOARD_TICK, EVENT_CONSOLE_LOG,
)

__all__ = [
    "SystemConsoleApp", "SystemConsoleEngine",
    "APP_NAME", "MODULE_REGISTRY", "MODULE_KEYS",
    "ModuleState", "ConsoleStatus", "SystemLayer",
    "EVENT_CONSOLE_STARTED", "EVENT_CONSOLE_STOPPED",
    "EVENT_MODULE_STARTING", "EVENT_MODULE_STARTED",
    "EVENT_MODULE_STOPPING", "EVENT_MODULE_STOPPED",
    "EVENT_MODULE_ERROR", "EVENT_MODULE_STATE_CHANGED",
    "EVENT_SYSTEM_STATE_UPDATED", "EVENT_ALL_STARTED",
    "EVENT_ALL_STOPPED", "EVENT_DASHBOARD_TICK", "EVENT_CONSOLE_LOG",
]
