from pathlib import Path
p = Path(r"C:\Users\11229\Documents\GitHub\vnpy\vnpy\app\batch_research\ui\stock_pool_editor.py")
src = p.read_text(encoding="utf-8")

part2 = (
    '\n'
    'class StockPoolEditor(QtWidgets.QWidget):\n'
    '    """Embeddable stock-pool editor.\n\n'
    '    Signals:\n'
    '        symbols_changed(list[str]): emitted whenever the list changes.\n'
    '    """\n'
    '\n'
    '    symbols_changed: QtCore.Signal = QtCore.Signal(list)\n'
    '\n'
    '    def __init__(\n'
    '        self,\n'
    '        parent: QtWidgets.QWidget | None = None,\n'
    '        name_resolver: Callable[[str], str] | None = None,\n'
    '    ) -> None:\n'
    '        super().__init__(parent)\n'
    '        self._parser        = SymbolParser()\n'
    '        self._name_resolver = name_resolver or (lambda _: "")\n'
    '        self._init_ui()\n'
    '        self._init_menu()\n'
    '\n'
    '    # ---- public API ----------------------------------------\n'
    '\n'
    '    def get_symbols(self) -> list[str]:\n'
    '        """Return current vt_symbol list (preserving display order)."""\n'
    '        result: list[str] = []\n'
    '        for row in range(self._table.rowCount()):\n'
    '            item = self._table.item(row, _COL_SYMBOL)\n'
    '            if item:\n'
    '                result.append(item.text())\n'
    '        return result\n'
    '\n'
    '    def set_symbols(self, symbols: list[str]) -> None:\n'
    '        """Replace the entire list (auto de-duplicates)."""\n'
    '        normalized = self._parser.parse("\\n".join(symbols))\n'
    '        self._load_rows(normalized)\n'
    '\n'
    '    def add_symbols(self, symbols: list[str]) -> int:\n'
    '        """Append, skipping duplicates. Returns count added."""\n'
    '        existing = set(self.get_symbols())\n'
    '        new_ones = [s for s in symbols if s not in existing]\n'
    '        if new_ones:\n'
    '            self._load_rows(self.get_symbols() + new_ones)\n'
    '        return len(new_ones)\n'
    '\n'
    '    def clear(self) -> None:\n'
    '        """Clear all symbols."""\n'
    '        self._table.setRowCount(0)\n'
    '        self._update_counter()\n'
    '        self.symbols_changed.emit([])\n'
    '\n'
    '    def count(self) -> int:\n'
    '        """Current symbol count."""\n'
    '        return self._table.rowCount()\n'
    '\n'
)
p.write_text(src + part2, encoding="utf-8")
print("part2 ok:", len((src + part2).splitlines()), "total lines")
