from pathlib import Path
p = Path(r"C:\Users\11229\Documents\GitHub\vnpy\vnpy\app\batch_research\ui\stock_pool_editor.py")
src = p.read_text(encoding="utf-8")

part3 = (
    '    # ---- UI construction ----------------------------------\n'
    '\n'
    '    def _init_ui(self) -> None:\n'
    '        # --- input bar ---\n'
    '        self._input_edit = QtWidgets.QLineEdit()\n'
    '        self._input_edit.setPlaceholderText(\n'
    '            "\u8f93\u5165\u4ee3\u7801\u540e\u6309 Enter \u6dfb\u52a0\uff0c\u652f\u6301\u9017\u53f7/\u7a7a\u683c\u5206\u9694\u591a\u4e2a"\n'
    '        )\n'
    '        self._input_edit.returnPressed.connect(self._on_input_enter)\n'
    '\n'
    '        btn_paste = QtWidgets.QPushButton("\u7c98\u8d34")\n'
    '        btn_sort  = QtWidgets.QPushButton("\u6392\u5e8f")\n'
    '        btn_dedup = QtWidgets.QPushButton("\u53bb\u91cd")\n'
    '        btn_clear = QtWidgets.QPushButton("\u6e05\u7a7a")\n'
    '        btn_paste.setToolTip("\u4ece\u526a\u8d34\u677f\u6279\u91cf\u7c98\u8d34\uff08\u652f\u6301 Excel/CSV/\u540c\u82b1\u987a/Tushare\uff09")\n'
    '        btn_paste.clicked.connect(self._on_paste_clipboard)\n'
    '        btn_sort.clicked.connect(self._on_sort)\n'
    '        btn_dedup.clicked.connect(self._on_dedup)\n'
    '        btn_clear.clicked.connect(self._on_clear)\n'
    '\n'
    '        toolbar = QtWidgets.QHBoxLayout()\n'
    '        toolbar.setSpacing(6)\n'
    '        toolbar.addWidget(self._input_edit, 1)\n'
    '        for btn in (btn_paste, btn_sort, btn_dedup, btn_clear):\n'
    '            toolbar.addWidget(btn)\n'
    '\n'
    '        # --- table ---\n'
    '        self._table = QtWidgets.QTableWidget(0, 2)\n'
    '        self._table.setHorizontalHeaderLabels(["\u5e8f\u53f7", "\u80a1\u7968\u4ee3\u7801 (vt_symbol)"])\n'
    '        hh = self._table.horizontalHeader()\n'
    '        hh.setSectionResizeMode(_COL_IDX,    QtWidgets.QHeaderView.ResizeMode.Fixed)\n'
    '        hh.setSectionResizeMode(_COL_SYMBOL, QtWidgets.QHeaderView.ResizeMode.Stretch)\n'
    '        self._table.setColumnWidth(_COL_IDX, 52)\n'
    '        self._table.verticalHeader().setVisible(False)\n'
    '        self._table.setEditTriggers(\n'
    '            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)\n'
    '        self._table.setSelectionBehavior(\n'
    '            QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)\n'
    '        self._table.setSelectionMode(\n'
    '            QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)\n'
    '        self._table.setStyleSheet(_STYLE_TABLE)\n'
    '        self._table.setAlternatingRowColors(False)\n'
    '        self._table.verticalHeader().setDefaultSectionSize(26)\n'
    '        self._table.doubleClicked.connect(self._on_double_click)\n'
    '        self._table.keyPressEvent = self._table_key_press  # type: ignore\n'
    '\n'
    '        # --- status bar ---\n'
    '        self._counter_label = QtWidgets.QLabel("\u5171 0 \u53ea\u80a1\u7968")\n'
    '        self._counter_label.setStyleSheet(_STYLE_COUNTER)\n'
    '        hint = QtWidgets.QLabel(\n'
    '            "\u63d0\u793a\uff1a\u53ef\u76f4\u63a5\u7c98\u8d34 Excel/CSV/\u540c\u82b1\u987a/Tushare\uff1b\u53cc\u51fb\u884c\u53ef\u5220\u9664"\n'
    '        )\n'
    '        hint.setStyleSheet(_STYLE_HINT)\n'
    '\n'
    '        status_row = QtWidgets.QHBoxLayout()\n'
    '        status_row.addWidget(self._counter_label)\n'
    '        status_row.addStretch()\n'
    '        status_row.addWidget(hint)\n'
    '\n'
    '        vbox = QtWidgets.QVBoxLayout(self)\n'
    '        vbox.setContentsMargins(0, 0, 0, 0)\n'
    '        vbox.setSpacing(6)\n'
    '        vbox.addLayout(toolbar)\n'
    '        vbox.addWidget(self._table, 1)\n'
    '        vbox.addLayout(status_row)\n'
    '\n'
)
p.write_text(src + part3, encoding="utf-8")
print("part3 ok:", len((src + part3).splitlines()), "total lines")
