from pathlib import Path
p = Path(r"C:\Users\11229\Documents\GitHub\vnpy\vnpy\app\batch_research\ui\stock_pool_editor.py")
src = p.read_text(encoding="utf-8")

part4 = (
    '    def _init_menu(self) -> None:\n'
    '        self._table.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)\n'
    '        self._table.customContextMenuRequested.connect(self._show_context_menu)\n'
    '        self._ctx_menu = QtWidgets.QMenu(self)\n'
    '        for label, slot, sc in [\n'
    '            ("\u5220\u9664\u9009\u4e2d",             self._delete_selected, "Delete"),\n'
    '            ("\u590d\u5236\u9009\u4e2d\u4ee3\u7801", self._copy_selected,   "Ctrl+C"),\n'
    '        ]:\n'
    '            act = QtGui.QAction(label, self)\n'
    '            if sc:\n'
    '                act.setShortcut(sc)\n'
    '            act.triggered.connect(slot)\n'
    '            self._ctx_menu.addAction(act)\n'
    '        self._ctx_menu.addSeparator()\n'
    '        act_all = QtGui.QAction("\u5168\u9009", self)\n'
    '        act_all.setShortcut("Ctrl+A")\n'
    '        act_all.triggered.connect(self._table.selectAll)\n'
    '        self._ctx_menu.addAction(act_all)\n'
    '        self._ctx_menu.addSeparator()\n'
    '        act_clr = QtGui.QAction("\u6e05\u7a7a\u5168\u90e8", self)\n'
    '        act_clr.triggered.connect(self._on_clear)\n'
    '        self._ctx_menu.addAction(act_clr)\n'
    '\n'
    '    # ---- internal helpers ----------------------------------\n'
    '\n'
    '    def _load_rows(self, symbols: list[str]) -> None:\n'
    '        self._table.setRowCount(0)\n'
    '        self._table.setRowCount(len(symbols))\n'
    '        for row, sym in enumerate(symbols):\n'
    '            idx_item = QtWidgets.QTableWidgetItem(str(row + 1))\n'
    '            idx_item.setTextAlignment(\n'
    '                QtCore.Qt.AlignmentFlag.AlignCenter\n'
    '                | QtCore.Qt.AlignmentFlag.AlignVCenter)\n'
    '            idx_item.setForeground(QtGui.QColor("#888888"))\n'
    '            self._table.setItem(row, _COL_IDX, idx_item)\n'
    '            sym_item = QtWidgets.QTableWidgetItem(sym)\n'
    '            sym_item.setTextAlignment(\n'
    '                QtCore.Qt.AlignmentFlag.AlignLeft\n'
    '                | QtCore.Qt.AlignmentFlag.AlignVCenter)\n'
    '            self._table.setItem(row, _COL_SYMBOL, sym_item)\n'
    '        self._update_counter()\n'
    '        self.symbols_changed.emit(self.get_symbols())\n'
    '\n'
    '    def _renumber(self) -> None:\n'
    '        for row in range(self._table.rowCount()):\n'
    '            item = self._table.item(row, _COL_IDX)\n'
    '            if item:\n'
    '                item.setText(str(row + 1))\n'
    '\n'
    '    def _update_counter(self) -> None:\n'
    '        n = self._table.rowCount()\n'
    '        self._counter_label.setText(f"\u5171 {n} \u53ea\u80a1\u7968")\n'
    '\n'
)

p.write_text(src + part4, encoding="utf-8")
print("part4 ok:", len((src + part4).splitlines()), "total lines")
