from pathlib import Path
import py_compile

p = Path(r"C:\Users\11229\Documents\GitHub\vnpy\vnpy\app\batch_research\ui\stock_pool_editor.py")
src = p.read_text(encoding="utf-8")

lines = [
    '    # ---- event handlers -----------------------------------',
    '',
    '    def _on_input_enter(self) -> None:',
    '        text = self._input_edit.text().strip()',
    '        if not text:',
    '            return',
    '        symbols = self._parser.parse(text)',
    '        if symbols:',
    '            added = self.add_symbols(symbols)',
    '            if added:',
    '                self._input_edit.clear()',
    '            else:',
    '                self._input_edit.selectAll()',
    '        else:',
    '            self._input_edit.setStyleSheet("border: 1px solid #FF5555;")',
    '            QtCore.QTimer.singleShot(',
    '                800, lambda: self._input_edit.setStyleSheet("")',
    '            )',
    '',
    '    def _on_paste_clipboard(self) -> None:',
    '        text = QtWidgets.QApplication.clipboard().text()',
    '        if not text.strip():',
    '            return',
    '        symbols = self._parser.parse(text)',
    '        if not symbols:',
    '            QtWidgets.QMessageBox.information(',
    '                self,',
    '                "\u7c98\u8d34\u7ed3\u679c",',
    '                "\u672a\u80fd\u8bc6\u522b\u5230\u6709\u6548\u80a1\u7968\u4ee3\u7801\u3002\\n\\n"',
    '                "\u652f\u6301\uff1a6\u4f4d\u4ee3\u7801\u3001vt_symbol\u3001Tushare \u683c\u5f0f",',
    '            )',
    '            return',
    '        added   = self.add_symbols(symbols)',
    '        skipped = len(symbols) - added',
    '        msg = f"\u8bc6\u522b\u5230 {len(symbols)} \u4e2a\u4ee3\u7801\uff0c\u65b0\u589e {added} \u4e2a"',
    '        if skipped:',
    '            msg += f"\uff0c\u8df3\u8fc7\u91cd\u590d {skipped} \u4e2a"',
    '        self._counter_label.setText(msg)',
    '        QtCore.QTimer.singleShot(3000, self._update_counter)',
    '',
    '    def _on_sort(self) -> None:',
    '        self._load_rows(sorted(self.get_symbols()))',
    '',
    '    def _on_dedup(self) -> None:',
    '        seen: set[str] = set()',
    '        unique: list[str] = []',
    '        for s in self.get_symbols():',
    '            if s not in seen:',
    '                seen.add(s)',
    '                unique.append(s)',
    '        self._load_rows(unique)',
    '',
    '    def _on_clear(self) -> None:',
    '        n = self._table.rowCount()',
    '        if n == 0:',
    '            return',
    '        reply = QtWidgets.QMessageBox.question(',
    '            self,',
    '            "\u786e\u8ba4\u6e05\u7a7a",',
    '            f"\u786e\u5b9a\u8981\u6e05\u7a7a\u5168\u90e8 {n} \u53ea\u80a1\u7968\u5417\uff1f",',
    '            QtWidgets.QMessageBox.StandardButton.Yes',
    '            | QtWidgets.QMessageBox.StandardButton.No,',
    '            QtWidgets.QMessageBox.StandardButton.No,',
    '        )',
    '        if reply == QtWidgets.QMessageBox.StandardButton.Yes:',
    '            self.clear()',
    '',
    '    def _on_double_click(self, index: QtCore.QModelIndex) -> None:',
    '        row = index.row()',
    '        self._table.removeRow(row)',
    '        self._renumber()',
    '        self._update_counter()',
    '        self.symbols_changed.emit(self.get_symbols())',
    '',
    '    def _table_key_press(self, event: QtGui.QKeyEvent) -> None:',
    '        if event.key() in (',
    '            QtCore.Qt.Key.Key_Delete, QtCore.Qt.Key.Key_Backspace',
    '        ):',
    '            self._delete_selected()',
    '        else:',
    '            QtWidgets.QTableWidget.keyPressEvent(self._table, event)',
    '',
    '    def _delete_selected(self) -> None:',
    '        rows = sorted(',
    '            {idx.row() for idx in self._table.selectedIndexes()},',
    '            reverse=True,',
    '        )',
    '        for row in rows:',
    '            self._table.removeRow(row)',
    '        if rows:',
    '            self._renumber()',
    '            self._update_counter()',
    '            self.symbols_changed.emit(self.get_symbols())',
    '',
    '    def _copy_selected(self) -> None:',
    '        rows = sorted({idx.row() for idx in self._table.selectedIndexes()})',
    '        lines: list[str] = []',
    '        for row in rows:',
    '            item = self._table.item(row, _COL_SYMBOL)',
    '            if item:',
    '                lines.append(item.text())',
    '        if lines:',
    '            QtWidgets.QApplication.clipboard().setText("\\n".join(lines))',
    '',
    '    def _show_context_menu(self, pos: QtCore.QPoint) -> None:',
    '        self._ctx_menu.exec_(self._table.mapToGlobal(pos))',
    '',
    '    def keyPressEvent(self, event: QtGui.QKeyEvent) -> None:',
    '        ctrl = QtCore.Qt.KeyboardModifier.ControlModifier',
    '        if event.key() == QtCore.Qt.Key.Key_V and event.modifiers() == ctrl:',
    '            self._on_paste_clipboard()',
    '        elif event.key() == QtCore.Qt.Key.Key_A and event.modifiers() == ctrl:',
    '            self._table.selectAll()',
    '        else:',
    '            super().keyPressEvent(event)',
]

final = src + "\n".join(lines) + "\n"
p.write_text(final, encoding="utf-8")
total = len(final.splitlines())
print(f"part D written, total lines: {total}")

py_compile.compile(str(p), doraise=True)
print("syntax OK: stock_pool_editor.py")
