from pathlib import Path

p = Path(r"C:\Users\11229\Documents\GitHub\vnpy\vnpy\app\batch_research\ui\stock_pool_editor.py")
src = p.read_text(encoding="utf-8")

lines = [
    '    def _init_menu(self) -> None:',
    '        self._table.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)',
    '        self._table.customContextMenuRequested.connect(self._show_context_menu)',
    '        self._ctx_menu = QtWidgets.QMenu(self)',
    '        for label, slot, sc in [',
    '            ("\u5220\u9664\u9009\u4e2d",             self._delete_selected, "Delete"),',
    '            ("\u590d\u5236\u9009\u4e2d\u4ee3\u7801", self._copy_selected,   "Ctrl+C"),',
    '        ]:',
    '            act = QtGui.QAction(label, self)',
    '            if sc:',
    '                act.setShortcut(sc)',
    '            act.triggered.connect(slot)',
    '            self._ctx_menu.addAction(act)',
    '        self._ctx_menu.addSeparator()',
    '        act_all = QtGui.QAction("\u5168\u9009", self)',
    '        act_all.setShortcut("Ctrl+A")',
    '        act_all.triggered.connect(self._table.selectAll)',
    '        self._ctx_menu.addAction(act_all)',
    '        self._ctx_menu.addSeparator()',
    '        act_clr = QtGui.QAction("\u6e05\u7a7a\u5168\u90e8", self)',
    '        act_clr.triggered.connect(self._on_clear)',
    '        self._ctx_menu.addAction(act_clr)',
    '',
    '    # ---- internal helpers ----------------------------------',
    '',
    '    def _load_rows(self, symbols: list[str]) -> None:',
    '        self._table.setRowCount(0)',
    '        self._table.setRowCount(len(symbols))',
    '        for row, sym in enumerate(symbols):',
    '            idx_item = QtWidgets.QTableWidgetItem(str(row + 1))',
    '            idx_item.setTextAlignment(',
    '                QtCore.Qt.AlignmentFlag.AlignCenter',
    '                | QtCore.Qt.AlignmentFlag.AlignVCenter)',
    '            idx_item.setForeground(QtGui.QColor("#888888"))',
    '            self._table.setItem(row, _COL_IDX, idx_item)',
    '            sym_item = QtWidgets.QTableWidgetItem(sym)',
    '            sym_item.setTextAlignment(',
    '                QtCore.Qt.AlignmentFlag.AlignLeft',
    '                | QtCore.Qt.AlignmentFlag.AlignVCenter)',
    '            self._table.setItem(row, _COL_SYMBOL, sym_item)',
    '        self._update_counter()',
    '        self.symbols_changed.emit(self.get_symbols())',
    '',
    '    def _renumber(self) -> None:',
    '        for row in range(self._table.rowCount()):',
    '            item = self._table.item(row, _COL_IDX)',
    '            if item:',
    '                item.setText(str(row + 1))',
    '',
    '    def _update_counter(self) -> None:',
    '        n = self._table.rowCount()',
    '        self._counter_label.setText(f"\u5171 {n} \u53ea\u80a1\u7968")',
    '',
]

p.write_text(src + "\n".join(lines) + "\n", encoding="utf-8")
print("part C written, total lines:", len((src + "\n".join(lines)).splitlines()))
