import sys
from pathlib import Path

p = Path(r"C:\Users\11229\Documents\GitHub\vnpy\vnpy\app\batch_research\ui\stock_pool_editor.py")

lines = [
    '"""',
    'ui/stock_pool_editor.py',
    '',
    'StockPoolEditor -- embeddable stock list editor widget.',
    '"""',
    'from __future__ import annotations',
    'from typing import Callable',
    'from vnpy.trader.ui import QtCore, QtGui, QtWidgets',
    'from ..utils.symbol_parser import SymbolParser',
    '',
    '_STYLE_TABLE = """',
    'QTableWidget {',
    '    background-color: #1E1E1E; gridline-color: #3A3A3A;',
    '    color: #FFFFFF; font-size: 13px;',
    '    selection-background-color: #2A5298; selection-color: #FFFFFF;',
    '    border: 1px solid #3A3A3A;',
    '}',
    'QTableWidget::item { padding: 3px 8px; border-bottom: 1px solid #2A2A2A; }',
    'QHeaderView::section {',
    '    background-color: #1E3A5F; color: #FFFFFF;',
    '    padding: 4px; border: 1px solid #2A4A7F; font-weight: bold;',
    '}',
    '"""',
    '_STYLE_COUNTER = "color: #AAAAAA; font-size: 12px; padding: 2px 4px;"',
    '_STYLE_HINT    = "color: #888888; font-size: 11px;"',
    '_COL_IDX    = 0',
    '_COL_SYMBOL = 1',
    '',
    '',
    'class StockPoolEditor(QtWidgets.QWidget):',
    '    """Embeddable stock-pool editor.',
    '',
    '    Signals:',
    '        symbols_changed(list[str]): emitted whenever the list changes.',
    '    """',
    '',
    '    symbols_changed: QtCore.Signal = QtCore.Signal(list)',
    '',
    '    def __init__(',
    '        self,',
    '        parent: QtWidgets.QWidget | None = None,',
    '        name_resolver: Callable[[str], str] | None = None,',
    '    ) -> None:',
    '        super().__init__(parent)',
    '        self._parser        = SymbolParser()',
    '        self._name_resolver = name_resolver or (lambda _: "")',
    '        self._init_ui()',
    '        self._init_menu()',
    '',
    '    # ---- public API ----------------------------------------',
    '',
    '    def get_symbols(self) -> list[str]:',
    '        """Return current vt_symbol list (preserving display order)."""',
    '        result: list[str] = []',
    '        for row in range(self._table.rowCount()):',
    '            item = self._table.item(row, _COL_SYMBOL)',
    '            if item:',
    '                result.append(item.text())',
    '        return result',
    '',
    '    def set_symbols(self, symbols: list[str]) -> None:',
    '        """Replace the entire list (auto de-duplicates)."""',
    '        normalized = self._parser.parse("\\n".join(symbols))',
    '        self._load_rows(normalized)',
    '',
    '    def add_symbols(self, symbols: list[str]) -> int:',
    '        """Append, skipping duplicates. Returns count added."""',
    '        existing = set(self.get_symbols())',
    '        new_ones = [s for s in symbols if s not in existing]',
    '        if new_ones:',
    '            self._load_rows(self.get_symbols() + new_ones)',
    '        return len(new_ones)',
    '',
    '    def clear(self) -> None:',
    '        """Clear all symbols."""',
    '        self._table.setRowCount(0)',
    '        self._update_counter()',
    '        self.symbols_changed.emit([])',
    '',
    '    def count(self) -> int:',
    '        """Current symbol count."""',
    '        return self._table.rowCount()',
    '',
]

p.write_text("\n".join(lines) + "\n", encoding="utf-8")
print("part A written:", len(lines), "lines")
